version: "3.9"
name: media

networks:
  t2_proxy:
    external: true

services:
  ############################# SERVER #############################
  # jellyfin:
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   restart: $MEDIA_RESTART_POLICY
  #   # profiles:
  #   # - media
  #   networks:
  #     - t2_proxy
  #   ports:
  #     - "8096:8096"
  #   # devices:
  #   #   - /dev/dri:/dev/dri # for harware transcoding
  #   security_opt:
  #     - no-new-privileges:true
  #   #  deploy:
  #   #    resources:
  #   #      limits:
  #   #        cpus: '0.4'
  #   #        memory: 276M
  #   #      reservations:
  #   #        cpus: '0.25'
  #   #        memory: 128M
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     UMASK: 022
  #   volumes:
  #     - $DOCKERDIR/appdata/jellyfin:/config
  #     - $DATADIR/jellyfin/metadata:/config/data/metadata
  #     - $DATADIR/downloads:/data/downloads
  #     - $MEDIADIR:/data/local
  #     - $ONEDRIVEDIR:/data/onedrive
  #     # - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
  #     - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.jellyfin-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
  #     - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
  
  jellyfin:
    image: jellyfin/jellyfin:latest  # TODO: ghcr.io
    container_name: jellyfin
    # cpus: "0.5"
    mem_reservation: "4096M"
    mem_limit: "4096M"
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    ports:
      - "8096:8096"
    security_opt:
      - no-new-privileges:true
    # user: $PGID:$PUID
    user: 0:0
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DOCKERDIR/appdata/jellyfin/cache:/cache
      - $DATADIR/jellyfin/metadata:/config/metadata
      - $DATADIR/downloads:/media/downloads:ro
      - $MEDIADIR:/media/local:ro
      - $ONEDRIVEDIR:/media/onedrive:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
    
  jellyseerr:
    image: fallenbagel/jellyseerr:latest  # TODO: ghcr.io
    container_name: jellyseerr
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - jellyfin
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/jellyseerr:/app/config
    environment:
      # - PUID=$PUID
      # - PGID=$PGID
      - TZ=$TZ
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyseerr-rtr.entrypoints=https"
      - "traefik.http.routers.jellyseerr-rtr.rule=Host(`jellyseerr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jellyseerr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.jellyseerr-rtr.service=jellyseerr-svc"
      - "traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055"

  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    container_name: feishin
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - jellyfin
    networks:
      - t2_proxy
    # ports:
    #   - "9180:9180"
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      # - "traefik.http.routers.feishin-rtr.entrypoints=https"
      - "traefik.http.routers.feishin-rtr.rule=Host(`music.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.feishin-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.feishin-rtr.service=feishin-svc"
      - "traefik.http.services.feishin-svc.loadbalancer.server.port=9180"


  ############################# DOWNLOAD #############################
  # For torrent VPN
  # gluetun:
  #   image: qmcgaw/gluetun
  #   container_name: gluetun
  #   # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8888:8888/tcp # HTTP proxy
  #     - 8388:8388/tcp # Shadowsocks
  #     - 8388:8388/udp # Shadowsocks
  #     # qbittorrent ports
  #     - 8080:8080
  #     - 6881:6881
  #     - 6881:6881/udp
  #   restart: unless-stopped
  #   volumes:
  #     - /tmp:/gluetun
  #   environment:
  #     # See https://github.com/qdm12/gluetun/wiki
  #     - VPN_SERVICE_PROVIDER=private internet access
  #     - VPN_TYPE=openvpn
  #     - OPENVPN_USER=redacted
  #     - OPENVPN_PASSWORD=redacted
  #     - SERVER_REGIONS=US California

  # Default user-pass: admin / adminadmin
  # qbittorrent-lscr:
  #   image: lscr.io/linuxserver/qbittorrent
  #   container_name: qbittorrent-lscr
  #   restart: $MEDIA_RESTART_POLICY
  #   # network_mode: "service:gluetun"
  #   # depends_on:
  #   #   - gluetun
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/qbittorrent:/config
  #     - $MEDIADIR/Downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     WEBUI_PORT: 8080
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.qbittorrent-lscr-rtr.entrypoints=https"
  #     - "traefik.http.routers.qbittorrent-lscr-rtr.rule=Host(`qtorrent.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.qbittorrent-lscr-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.qbittorrent-lscr-rtr.service=qbittorrent-lscr-svc"
  #     - "traefik.http.services.qbittorrent-lscr-svc.loadbalancer.server.port=8080"
  #     # - traefik.http.services.qbittorrent-lscr-svc.loadbalancer.passhostheader=false # Not needed
  
  # Default user-pass: admin / adminadmin
  # Tools -> Options -> Web UI -> Click use alternative Web UI
  # qbittorrent:
  #   image: cr.hotio.dev/hotio/qbittorrent
  #   container_name: qbittorrent
  #   # cpus: "0.5"
  #   mem_reservation: "4096M"
  #   mem_limit: "4096M"
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/qbittorrent:/config
  #     - $MEDIADIR/Downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     WEBUI_PORT: 8080
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
  #     - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qtorrent.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
  #     - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080"

  # jdownloader:
  #   image: jlesage/jdownloader-2:latest
  #   container_name: jdownloader
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   # ports:
  #   #   - 5800:5800
  #   volumes:
  #     - $DOCKERDIR/appdata/jdownloader:/config:rw
  #     - $MEDIADIR/Downloads:/output:rw
  #   environment:
  #     USER_ID: $PUID
  #     GROUP_ID: $PGID
  #     TZ: $TZ
  #     UMASK: 002
  #     KEEP_APP_RUNNING: 1
  #     CLEAN_TMP_DIR: 1
  #     DISPLAY_WIDTH: 2560
  #     DISPLAY_HEIGHT: 1440
  #   #      VNC_PASSWORD: $JDOWN_VNC_PASSWD
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.jdownloader-rtr.entrypoints=https"
  #     - "traefik.http.routers.jdownloader-rtr.rule=Host(`download.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.jdownloader-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.jdownloader-rtr.service=jdownloader-svc"
  #     - "traefik.http.services.jdownloader-svc.loadbalancer.server.port=5800"

# NOTE: only works on localhost because of RPC server issue
  # aria2:
  #   image: abcminiuser/docker-aria2-with-webui:latest
  #   container_name: aria2
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  # #  expose:
  # #    - 6800
  #   ports:
  #     - 6800:6800
  #     - 6880:80
  #   volumes:
  #     - $DOCKERDIR/appdata/aria2:/conf
  #     - $MEDIADIR/Downloads:/data
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #   #  SECRET: aria
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.aria2-rtr.entrypoints=https"
  #     - "traefik.http.routers.aria2-rtr.rule=Host(`aria2.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.aria2-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.aria2-rtr.service=aria2-svc"
  #     - "traefik.http.services.aria2-svc.loadbalancer.server.port=80"

  # Diffent GUIs in web home:
  # /combustion-release/ -- /transmission-web-control/ -- /kettu/ -- /flood-for-transmission/
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    # cpus: "0.5"
    mem_reservation: "4096M"
    mem_limit: "4096M"
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
#      t2_proxy:
#        ipv4_address: 192.168.90.160
#    ports:
#      - "9091:9091"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/transmission:/config
      - $MEDIADIR/Downloads:/data/downloads
      # - $MEDIADIR/Downloads/test:/downloads
      # If not set, tranmission creates reduntant volumes
      - $MEDIADIR/Downloads/torrent_files:/watch
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # TRANSMISSION_WEB_HOME: /flood-for-transmission (Not working > 4.0.0)
#      USER: username
#      PASS: password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.transmission-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-rtr.rule=Host(`torrent.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.transmission-rtr.middlewares=chain-authelia@file"
#      - "traefik.http.routers.transmission-rtr.middlewares=middlewares-rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-rtr.service=transmission-svc"
      - "traefik.http.services.transmission-svc.loadbalancer.server.port=9091"

  ############################# INDEXERS #############################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - transmission
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    #  t2_proxy:
    #    ipv4_address: 192.168.90.161
    ports:
      - "9696:9696"
    security_opt:
      - no-new-privileges:true
    volumes:
       - $DOCKERDIR/appdata/prowlarr:/config
       - $MEDIADIR/Downloads:/data/downloads
       - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.prowlarr-rtr.entrypoints=https"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.prowlarr-rtr.service=prowlarr-svc"
      - "traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696"

  # # NZBHydra2 - NZB meta search
  # hydra:
  #   image: lscr.io/linuxserver/nzbhydra2:latest
  #   container_name: hydra
  #   restart: $MEDIA_RESTART_POLICY
  #   # profiles:
  #   # - media
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   # ports:
  #   #   - "$NZBHYDRA_PORT:5076"
  #   volumes:
  #     - $DOCKERDIR/appdata/hydra2:/config
  #     - $DATADIR/downloads:/data/downloads
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.hydra-rtr.entrypoints=https"
  #     - "traefik.http.routers.hydra-rtr.rule=Host(`hydra.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.hydra-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.hydra-rtr.service=hydra-svc"
  #     - "traefik.http.services.hydra-svc.loadbalancer.server.port=5076"

  ############################## PVRS #############################

  buildarr:
    image: callum027/buildarr:latest
    container_name: buildarr
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - prowlarr
      - radarr
      # - sonarr
    networks:
      - t2_proxy
    volumes:
      - $CONFIGDIR/buildarr:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BUILDARR_LOG_LEVEL: INFO
      BUILDARR_INSTALL_PACKAGES: "buildarr-prowlarr buildarr-radarr"

  # # Lidarr - Music Management
  # # Set url_base in lidarr settings if using PathPrefix
  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: lidarr
  #   restart: $MEDIA_RESTART_POLICY
  #   # profiles:
  #   # - media
  #   networks:
  #     t2_proxy:
  #       ipv4_address: 192.168.90.163
  #   security_opt:
  #     - no-new-privileges:true
  #   # ports:
  #   #  - "$LIDARR_PORT:8686"
  #   volumes:
  #     - $DOCKERDIR/appdata/lidarr:/config
  #     # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
  #     - $DATADIR/lidarr/MediaCover:/config/MediaCover
  #     - $DATADIR/downloads:/data/downloads
  #     - $DATADIR/media/music:/data/media/music
  #     - "/etc/localtime:/etc/localtime:ro"
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth Bypass
  #     - "traefik.http.routers.lidarr-rtr-bypass.entrypoints=https"
  #     - "traefik.http.routers.lidarr-rtr-bypass.rule=Host(`lidarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$LIDARR_API_KEY`) || Query(`apikey`, `$LIDARR_API_KEY`))"
  #     - "traefik.http.routers.lidarr-rtr-bypass.priority=100"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.lidarr-rtr.entrypoints=https"
  #     - "traefik.http.routers.lidarr-rtr.rule=Host(`lidarr.$DOMAINNAME`)"
  #     - "traefik.http.routers.lidarr-rtr.priority=99"
  #     ## Middlewares
  #     - "traefik.http.routers.lidarr-rtr-bypass.middlewares=chain-no-auth@file"
  #     - "traefik.http.routers.lidarr-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.lidarr-rtr.service=lidarr-svc"
  #     - "traefik.http.routers.lidarr-rtr-bypass.service=lidarr-svc"
  #     - "traefik.http.services.lidarr-svc.loadbalancer.server.port=8686"

  # Movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - transmission
      # - prowlarr
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    #  t2_proxy:
    #    ipv4_address: 192.168.90.162
    ports:
      - "7878:7878"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      # - $CONFIGDIR/radarr:/config
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      # - $DATADIR/radarr/MediaCover:/config/MediaCover
      - $MEDIADIR/Downloads:/data/downloads
      - $MEDIADIR/Movies_Radarr:/data/media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      #- "traefik.http.routers.radarr-rtr-bypass.entrypoints=https"
      #- "traefik.http.routers.radarr-rtr-bypass.rule=Host(`radarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$RADARR_API_KEY`) || Query(`apikey`, `$RADARR_API_KEY`))"
      #- "traefik.http.routers.radarr-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.radarr-rtr.entrypoints=https"
      - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.$DOMAINNAME`)"
      #- "traefik.http.routers.radarr-rtr.priority=99"
      ## Middlewares
      # - "traefik.http.routers.radarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.radarr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      #- "traefik.http.routers.radarr-rtr-bypass.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"

  #  TV Shows management
  # Set url_base in sonarr settings if using PathPrefix
  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   restart: $MEDIA_RESTART_POLICY
  #   # profiles:
  #   # - media
  #   networks:
  #     t2_proxy:
  #       ipv4_address: 192.168.90.167
  #   security_opt:
  #     - no-new-privileges:true
  #   # ports:
  #   #  - "$SONARR_PORT:8989"
  #   volumes:
  #     - $DOCKERDIR/appdata/sonarr:/config
  #     # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
  #     - $DATADIR/sonarr/MediaCover:/config/MediaCover
  #     - $DATADIR/downloads:/data/downloads
  #     - $DATADIR/media:/data/media
  #     - "/etc/localtime:/etc/localtime:ro"
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth Bypass
  #     - "traefik.http.routers.sonarr-rtr-bypass.entrypoints=https"
  #     - "traefik.http.routers.sonarr-rtr-bypass.rule=Host(`sonarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$SONARR_API_KEY`) || Query(`apikey`, `$SONARR_API_KEY`))"
  #     - "traefik.http.routers.sonarr-rtr-bypass.priority=100"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.sonarr-rtr.entrypoints=https"
  #     - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.$DOMAINNAME`)"
  #     - "traefik.http.routers.sonarr-rtr.priority=99"
  #     ## Middlewares
  #     - "traefik.http.routers.sonarr-rtr-bypass.middlewares=chain-no-auth@file"
  #     - "traefik.http.routers.sonarr-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
  #     - "traefik.http.routers.sonarr-rtr-bypass.service=sonarr-svc"
  #     - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"

  # Books management
  # # Set url_base in readarr settings if using PathPrefix
  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/readarr:/config
  #     # - /path/to/books:/books #optional
  #     - $MEDIADIR/Downloads:/downloads
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     # UMASK: 002
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.readarr-rtr.entrypoints=https"
  #     - "traefik.http.routers.readarr-rtr.rule=Host(`readarr.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.readarr-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.readarr-rtr.service=readarr-svc"
  #     - "traefik.http.services.readarr-svc.loadbalancer.server.port=8787"

  # Ebooks and Management
  # lazylibrarian:
  #   image: lscr.io/linuxserver/lazylibrarian
  #   container_name: lazylibrarian
  #   restart: unless-stopped
  #   # profiles:
  #   # - media
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   # ports:
  #   #  - "$LAZYLIBRARIAN_PORT:5299"
  #   volumes:
  #     - $DOCKERDIR/appdata/lazylibrarian:/config
  #     - $DATADIR/downloads:/data/downloads
  #     - $DOCKERDIR/appdata/calibre/books:/books:rw
  #     - "/etc/localtime:/etc/localtime:ro"
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     DOCKER_MODS: linuxserver/calibre-web:calibre # set the path to converter tool to /app/calibre/ebook-convert
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.lazylibrarian-rtr.entrypoints=https"
  #     - "traefik.http.routers.lazylibrarian-rtr.rule=Host(`lazy.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.lazylibrarian-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.lazylibrarian-rtr.service=lazylibrarian-svc"
  #     - "traefik.http.services.lazylibrarian-svc.loadbalancer.server.port=5299"

  ############################### YOUTUBE ###############################
#   metube:
#     image: alexta69/metube:latest
#     container_name: metube
#     restart: $MEDIA_RESTART_POLICY
#     networks:
#       - t2_proxy
#     security_opt:
#       - no-new-privileges:true
#     volumes:
#       - $MEDIADIR/Youtube:/downloads
# #      - /path/to/cookies:/cookies
#     environment:
#       OUTPUT_TEMPLATE: '%(title)s [%(id)s].%(ext)s'
#       YTDL_OPTIONS: '{"writethumbnail": true, "writeinfojson": true}'  # "writeinfojson": true,
#       # - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
#     labels:
#       - "traefik.enable=true"
#       ## HTTP Routers Auth
#       - "traefik.http.routers.metube-rtr.entrypoints=https"
#       - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME`)"
#       ## Middlewares
#       - "traefik.http.routers.metube-rtr.middlewares=chain-authelia@file"
#       ## HTTP Services
#       - "traefik.http.routers.metube-rtr.service=metube-svc"
#       - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"

  # docker exec -u abc -it ytdl-sub /bin/bash
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      # - $CONFIGDIR/ytdl-sub/config:/config
      - $CONFIGDIR/ytdl-sub/config.yaml:/config/config.yaml
      - $CONFIGDIR/ytdl-sub/subscriptions.yaml:/config/subscriptions.yaml
      - $CONFIGDIR/ytdl-sub/download_yt.sh:/config/download_yt.sh
      - $MEDIADIR/Youtube_Sub:/tv_shows
      # - MEDIADIR/Movies:/movies # optional
      # - <path/to/music_videos>:/music_videos # optional
      # - MEDIADIR/Music:/music # optional
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.ytdl-rtr.entrypoints=https"
      - "traefik.http.routers.ytdl-rtr.rule=Host(`ytdl.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.ytdl-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      # - "traefik.http.routers.ytdl-rtr.service=ytdl-svc"
      # - "traefik.http.services.ytdl-svc.loadbalancer.server.port=8081"

  # tubearchivist:
  #   image: bbilly1/tubearchivist:latest
  #   container_name: tubearchivist
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $MEDIADIR/Youtube:/youtube
  #   environment:
  #     - TA_USERNAME=admin
  #     - TA_PASSWORD=admin
  #     - HOST_UID=$PUID
  #     - HOST_GID=$PGID
  #     - TZ=$TZ
  #     - ELASTIC_PASSWORD=admin
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.tubearchivist-rtr.entrypoints=https"
  #     - "traefik.http.routers.tubearchivist-rtr.rule=Host(`tubearch.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.tubearchivist-rtr.middlewares=chain-authelia@file"
  #   #  - "traefik.http.routers.transmission-rtr.middlewares=middlewares-rate-limit@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.tubearchivist-rtr.service=tubearchivist-svc"
  #     - "traefik.http.services.tubearchivist-svc.loadbalancer.server.port=8000"

  # tubesync:
  #   image: ghcr.io/meeb/tubesync:latest
  #   container_name: tubesync
  #   restart: $MEDIA_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/tubesync:/config
  #     - $MEDIADIR/Youtube:/downloads
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     # - HTTP_USER=admin
  #     # - HTTP_PASS=admin
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.tubesync-rtr.entrypoints=https"
  #     - "traefik.http.routers.tubesync-rtr.rule=Host(`tubesync.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.tubesync-rtr.middlewares=chain-authelia@file"
  # #      - "traefik.http.routers.transmission-rtr.middlewares=middlewares-rate-limit@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.tubesync-rtr.service=tubesync-svc"
  #     - "traefik.http.services.tubesync-svc.loadbalancer.server.port=4848"

  ############################### OTHERS ###############################

  podgrab:
    image: akhilrex/podgrab:latest
    container_name: podgrab
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/podgrab:/config
      - $MEDIADIR/Podcasts:/assets
    environment:
      - CHECK_FREQUENCY=240
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.podgrab-rtr.entrypoints=https"
      - "traefik.http.routers.podgrab-rtr.rule=Host(`podgrab.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.podgrab-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.podgrab-rtr.service=podgrab-svc"
      - "traefik.http.services.podgrab-svc.loadbalancer.server.port=8080"
    
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: deemix
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/deemix:/config # TODO: Move to config folder
      - $MEDIADIR/Music/Deemix:/downloads
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.deemix-rtr.entrypoints=https"
      - "traefik.http.routers.deemix-rtr.rule=Host(`deemix.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.deemix-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.deemix-rtr.service=deemix-svc"
      - "traefik.http.services.deemix-svc.loadbalancer.server.port=6595"

  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      # - $CONFIGDIR/beets/config.yaml:/config/config.yaml # FIXME: not working
      - $DOCKERDIR/appdata/beets:/config
      - $MEDIADIR/Music/Beets_TEST/Music:/music
      - $MEDIADIR/Music/Beets_TEST/Downloads:/downloads
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.beets-rtr.entrypoints=https"
      - "traefik.http.routers.beets-rtr.rule=Host(`beets.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.beets-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.beets-rtr.service=beets-svc"
      - "traefik.http.services.beets-svc.loadbalancer.server.port=8337"


  stirlingpdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/stirlingpdf/ocr_train_data:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - $DOCKERDIR/appdata/stirlingpdf:/configs
    environment:
      - APP_LOCALE=en_GB
      - APP_HOME_NAME=Stirling PDF
      # - APP_HOME_DESCRIPTION=Your locally hosted one-stop-shop for all your PDF needs.
      # - APP_NAVBAR_NAME=Stirling PDF
      # - APP_ROOT_PATH=/
      # - ALLOW_GOOGLE_VISIBILITY=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.stirlingpdf-rtr.entrypoints=https"
      - "traefik.http.routers.stirlingpdf-rtr.rule=Host(`pdf.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.stirlingpdf-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.stirlingpdf-rtr.service=stirlingpdf-svc"
      - "traefik.http.services.stirlingpdf-svc.loadbalancer.server.port=8080"

  stremio:
    image: stremio/server:latest
    container_name: stremio
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    ports:
      - "11470:11470"
      - "12470:12470"
    security_opt:
      - no-new-privileges:true
    environment:
      - NO_CORS=1
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.stremio-rtr.entrypoints=https"
      - "traefik.http.routers.stremio-rtr.rule=Host(`stremio.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.stremio-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.stremio-rtr.service=stremio-svc"
      - "traefik.http.services.stremio-svc.loadbalancer.server.port=11470"
      #  ## HTTP Routers Auth
      # - "traefik.http.routers.stremio-rtr2.entrypoints=https"
      # - "traefik.http.routers.stremio-rtr2.rule=Host(`stremio.$DOMAINNAME`)"
      # ## Middlewares
      # - "traefik.http.routers.stremio-rtr2.middlewares=chain-authelia@file"
      # ## HTTP Services
      # - "traefik.http.routers.stremio-rtr2.service=stremio-svc2"
      # - "traefik.http.services.stremio-svc2.loadbalancer.server.port=12470"

  ############################### Transcode ###############################

  # Handbrake - Video Conversion (Transcoding and compression)
  # handbrake:
  #   container_name: handbrake
  #   image: jlesage/handbrake:latest
  #   <<: *common-keys-apps # See EXTENSION FIELDS at the top
  #   ports:
  #     - "5801:5800"
  #   volumes:
  #     - $DATADIR/downloads:/data/downloads
  #     - $DOCKERDIR/appdata/handbrake/config:/config
  #     - $DOCKERDIR/appdata/handbrake/watch:/watch
  #   environment:
  #     USER_ID: $PUID
  #     GROUP_ID: $PGID
  #     UMASK: 002
  #     TZ: $TZ
  #     KEEP_APP_RUNNING: 1
  #     CLEAN_TMP_DIR: 1
  #     DISPLAY_WIDTH: 1600
  #     DISPLAY_HEIGHT: 960
  #     AUTOMATED_CONVERSION_KEEP_SOURCE: 1
  #     VNC_PASSWORD: $HANDBRAKE_VNC_PASSWD

  # NOTE: Not working with traefik yet
  # tdarr:
  #   container_name: tdarr
  #   image: ghcr.io/haveagitgat/tdarr:latest
  #   restart: $MEDIA_RESTART_POLICY
  #   # network_mode: bridge
  #   networks:
  #     - t2_proxy
  #   ports:
  #     # - 8265:8265 # webUI port
  #     - 8266:8266 # server port
  #     # - 8267:8267 # Internal node port
  #     # - 8268:8268 # Example extra node port
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/tdarr/server:/app/server
  #     - $CONFIGDIR/tdarr:/app/configs
  #     - $DOCKERDIR/logs/tdarr:/app/logs
  #     - /transcode_cache:/temp
  #     - $MEDIADIR/Movies_Radarr:/media
  #   environment:
  #     - TZ=$TZ
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - UMASK_SET=002
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - webUIPort=8265
  #     - internalNode=true
  #     - inContainer=true
  #     - nodeName=MyInternalNode
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.tdarr-rtr.entrypoints=https"
  #     - "traefik.http.routers.tdarr-rtr.rule=Host(`tdarr.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.tdarr-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.tdarr-rtr.service=tdarr-svc"
  #     - "traefik.http.services.tdarr-svc.loadbalancer.server.port=8265"

  # # NOTE: Not working with traefik yet
  # tdarr-node:
  #   container_name: tdarr-node
  #   image: ghcr.io/haveagitgat/tdarr_node:latest
  #   restart: $MEDIA_RESTART_POLICY
  #   network_mode: service:tdarr
  #   # networks:
  #   #   - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $CONFIGDIR/tdarr:/app/configs
  #     - $DOCKERDIR/logs/tdarr:/app/logs
  #     - /transcode_cache:/temp
  #     - $MEDIADIR/Movies_Radarr:/media
  #   environment:
  #     - TZ=$TZ
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - UMASK_SET=002
  #     - nodeName=MainNode
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - inContainer=true