[project]
name = "homeserver-jupyter"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "ipykernel>=7.1.0",
  "jupyterlab==4.6.3",
]

[tool.uv]
environments = [
  "sys_platform == 'linux' and platform_machine == 'aarch64'",
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
