technology:
  preset: "yt_video"
  youtube:
    video_url: "https://www.youtube.com/watch?v=gtY_KPgHCWE&list=WL"
  overrides:
    tv_show_name: "Technology"

# a_ride_through_mcu:
# # rick_a_music_video_playlist:
#   preset: "yt_playlist"
#   youtube:
#     # playlist_url: "https://www.youtube.com/playlist?list=PLlaN88a7y2_plecYoJxvRFTLHVbIVAOoc"
#     playlist_url: "https://youtube.com/playlist?list=PLpT1Gph26DnTXXPEcl-havUPokmJGR-lh"
#   overrides:
#     tv_show_name: "A Ride Thorough MCU"

# rick_a_channel:
#   preset: "yt_channel_recent"
#   youtube:
#     channel_url: "https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw"
#   overrides:
#     tv_show_name: "Rick Astley"