name: remoteserver

networks:
  default:
    driver: bridge
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.19/32"
          gateway: "192.168.1.1"

########################### SECRETS
secrets:
  # authelia_jwt_secret:
  #   file: $DOCKERDIR/secrets/authelia_jwt_secret
  # authelia_session_secret:
  #   file: $DOCKERDIR/secrets/authelia_session_secret
  # authelia_storage_encryption_key:
  #   file: $DOCKERDIR/secrets/authelia_storage_encryption_key
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  # firefly_app_key:
  #   file: $DOCKERDIR/secrets/firefly_app_key
  # mysql_root_password:
  #   file: $DOCKERDIR/secrets/mysql_root_password
  # mysql_password:
  #   file: $DOCKERDIR/secrets/mysql_password
  rustic_password:
    file: $DOCKERDIR/secrets/rustic_password

include:
  ########################### SERVICES
  #### CORE ####
  - compose/adguardhome.yml
  - compose/crowdsec.yml
  - compose/copyparty.yml
  - compose/gotify.yml
  - compose/headscale.yml
  - compose/homepage.yml
  # - compose/glance.yml
  - compose/komodo-periphery.yml
  # - compose/pocket-id.yml
  - compose/socket-proxy.yml
  - compose/tinyauth.yml
  - compose/traefik.yml
  # - compose/vaultwarden.yml
  #### DESKTOP APPS ####
  # - compose/firefox.yml
  #### MACHINE LEARNING ####
  ###### MAINTENANCE ####
  - compose/bentopdf.yml
  # - compose/code-server.yml
  - compose/convertx.yml
  # - compose/docker-gc.yml
  # - compose/dozzle.yml
  - compose/gatus.yml
  - compose/it-tools.yml
  - compose/omni-tools.yml
  - compose/syncthing.yml
  # - compose/uptime-kuma.yml
  - compose/whoami.yml
  - compose/withoutbg.yml
  #### MEDIA ####
  - compose/bitplay.yml
  - compose/mazanoke.yml
  - compose/stremio.yml
  # - compose/transmission.yml
  - compose/zipline.yml
  #### ML ####
  - compose/open-webui.yml
  - compose/searxng.yml
  #### MONITORING ####
  - compose/beszel-agent.yml
  - compose/rybbit.yml
  #### PHOTO ####
  #### READING ####
  # - compose/obsidian.yml
  # - compose/silverbullet.yml
  # - compose/quartz.yml
  #### OTHERS ####
  # - compose/enclosed.yml
