name: homeserver

networks:
  default:
    driver: bridge
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp18s0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.19/32"
          gateway: "192.168.1.1"

########################### SECRETS
secrets:
  cloudflare_email:
    file: $DOCKERDIR/secrets/cloudflare_email
  cloudflare_api_key:
    file: $DOCKERDIR/secrets/cloudflare_api_key
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
#  authelia_duo_api_secret_key:
#    file: $DOCKERDIR/secrets/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password
  mysql_password:
    file: $DOCKERDIR/secrets/mysql_password
  rustic_password:
    file: $DOCKERDIR/secrets/rustic_password
  # firefly_app_key:
  #   file: $DOCKERDIR/secrets/firefly_app_key

include:
  ########################### SERVICES
  #### CORE ####
  # - compose/adguardhome.yml
  - compose/authelia.yml
  - compose/crowdsec.yml
  - compose/dufs.yml
  - compose/filebrowser.yml
  - compose/homepage.yml
  - compose/glance.yml
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/vaultwarden.yml
  #### DESKTOP APPS ####
  - compose/krita.yml
  # - compose/firefox.yml
  - compose/gimp.yml
  #### MACHINE LEARNING ####
  - compose/open-webui.yml
  ###### MAINTENANCE ####
  - compose/code-server.yml
  - compose/convertx.yml
  - compose/docker-gc.yml
  - compose/dozzle.yml
  - compose/it-tools.yml
  - compose/localstack-s3.yml
  - compose/restfox.yml
  - compose/syncthing.yml
  # - compose/uptime-kuma.yml
  - compose/whoami.yml
  # - compose/windows.yml
  # - compose/watchtower.yml
  #### MEDIA ####
  - compose/feishin.yml
  - compose/jellyfin.yml
  # - compose/jellyfin-vue.yml
  - compose/jellysearch.yml
  - compose/jellyseerr.yml
  - compose/mkvtoolnix.yml
  - compose/pinchflat.yml
  - compose/transmission.yml
  #### ML ####
  # - compose/sd-next.yml
  #### MONITORING ####
  - compose/beszel.yml
  - compose/changedetection.yml
  # - compose/netdata.yml
  # - compose/watchyourlan.yml
  #### PHOTO ####
  - compose/immich.yml
  #### READING ####
  - compose/flatnotes.yml
  - compose/linkwarden.yml
  # - compose/miniflux.yml
  - compose/obsidian.yml
  - compose/pdfding.yml
  - compose/rsshub.yml