http:
  middlewares:
    chain-tinyauth:
      chain:
        middlewares:
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-tinyauth

    chain-tinyauth-relaxed:
      chain:
        middlewares:
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed
          - middlewares-tinyauth

    chain-tinyauth-original:
      chain:
        middlewares:
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers-original
          - middlewares-tinyauth

    chain-tinyauth-arcane:
      chain:
        middlewares:
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers-arcane
          - middlewares-tinyauth