http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          # - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers

    chain-no-auth-relaxed:
      chain:
        middlewares:
          # - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed

    chain-no-auth-no-crowdsec:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers