http:
  middlewares:
    chain-silverbullet-no-auth:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-silverbullet-headers

    chain-silverbullet-tinyauth:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-silverbullet-headers
          - middlewares-tinyauth
