http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          # - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia

    chain-authelia-relaxed:
      chain:
        middlewares:
          # - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed
          - middlewares-authelia