http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers

    chain-no-auth-relaxed:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed

    chain-no-auth-no-crowdsec:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers