http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia

    chain-authelia-relaxed:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed
          - middlewares-authelia