http:
  middlewares:
    chain-tinyauth:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-tinyauth

    chain-tinyauth-headers:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-tinyauth-headers

    chain-tinyauth-relaxed:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed
          - middlewares-tinyauth

    chain-tinyauth-headers-relaxed:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-relaxed
          - middlewares-tinyauth-headers

    chain-tinyauth-original:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-original
          - middlewares-tinyauth

    chain-tinyauth-arcane:
      chain:
        middlewares:
{{if env "CROWDSEC_TRAEFIK_BOUNCER_API_KEY"}}
          - middlewares-cf-real-ip
          - middlewares-crowdsec-bouncer
{{end}}
          - middlewares-rate-limit
          - middlewares-secure-headers-arcane
          - middlewares-tinyauth
