http:
  middlewares:
    middlewares-cf-real-ip:
      plugin:
        ## NOTE: For  github.com/fma965/cloudflarewarp
        cf-real-ip:
          disableDefault: false
          trustip: # Trust IPS not required if disableDefault is false - we will allocate Cloud Flare IPs automatically, can be used to add additional CIDR's like LAN networks
{{- range $cidr := splitList "," (env "LOCAL_IPS") }}
{{- if ne (trim $cidr) "" }}
            - {{ trim $cidr | quote }}
{{- end }}
{{- end }}

        ## NOTE: For  github.com/jramsgz/traefik-real-ip
        # cf-real-ip:
        #   excludednets:
        #     - "1.1.1.1/24"

    # NOTE: NOt used but for explainability
    middlewares-origin-allow-cloudflare-trusted:
      ipAllowList:
        sourceRange:
{{- range $cidr := splitList "," (env "CLOUDFLARE_IPS") }}
{{- if ne (trim $cidr) "" }}
          - {{ trim $cidr | quote }}
{{- end }}
{{- end }}
{{- range $cidr := splitList "," (env "LOCAL_IPS") }}
{{- if ne (trim $cidr) "" }}
          - {{ trim $cidr | quote }}
{{- end }}
{{- end }}
