http:
  middlewares:
    middlewares-tinyauth:
      forwardAuth:
        address: "http://tinyauth:3000/api/auth/traefik"
        ## NOTE: For traefik>=3.6.9
        # maxResponseBodySize: -1 # Disable response body size limit
        maxResponseBodySize: 1048576
