visible_hostname egress-proxy

acl allowed_domains dstdomain "/etc/squid/allow-domains.txt"
acl allowed_ips dst "/etc/squid/allow-ips.txt"
acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed_domains
http_access allow allowed_ips
http_access deny all

http_port 3128

cache deny all
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log

forwarded_for delete
