# NOTE: Not working
services:
  adguardian:
    image: ghcr.io/lissy93/adguardian:latest@sha256:e20e54ce8c72b8d111ee5234c3050253a913034a02028029aef59d3684ebf4ac
    container_name: adguardian
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      ADGUARD_IP: adguardhome
      ADGUARD_PORT: 80
      ADGUARD_USERNAME: $ADGUARD_USERNAME
      ADGUARD_PASSWORD: $ADGUARD_PASSWORD
      ADGUARD_PROTOCOL: http
      ADGUARD_UPDATE_INTERVAL: 2
