services:
  beszel-agent:
    image: henrygd/beszel-agent@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
    container_name: beszel-agent
    restart: $RESTART_POLICY_MAINTENANCE
    # network_mode: host
    networks:
      - t3_proxy
      - socket_proxy
    volumes:
      - $REPO_PATH/appdata/beszel_agent:/var/lib/beszel-agent
    #   # monitor other disks / partitions by mounting a folder in /extra-filesystems
    #   # - /mnt/d:/extra-filesystems/sda1:ro
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy-read:2375
      LISTEN: 45876
      HUB_URL: https://beszel.gpu.$BASE_DOMAINNAME
      TOKEN: $BESZEL_AGENT_TOKEN
      KEY: $BESZEL_AGENT_KEY
    profiles:
      - monitoring
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 5s
      interval: 1m
