services:
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest@sha256:5c29b290ae4cb00a8e77232596ea0e33f174695bde816a98f21b4b3935cd6875
    container_name: docker-gc
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - $REPO_PATH/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      TZ: $TZ
      DOCKER_HOST: tcp://docker-socket-proxy-write:2375
      CRON: 0 0 3 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
