services:
  enclosed:
    container_name: enclosed
    image: corentinth/enclosed:1.16.0@sha256:d1e78c34ae7027c0c7b7a9ba67f352520049b9f260560fb8a0b3b1c55488cdc8
    restart: $RESTART_POLICY_OTHERS
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.enclosed.entrypoints: "websecure"
      traefik.http.routers.enclosed.rule: "Host(`enclosed.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.enclosed.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.enclosed.service: "logseq-svc"
      traefik.http.services.logseq-svc.loadbalancer.server.port: "8787"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "Enclosed"
      homepage.icon: "enclosed.svg"
      homepage.href: "https://enclosed.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Minimalistic web app designed for sending private and secure notes."
    profiles:
      - others
