services:
  feishin:
    image: ghcr.io/jeffvli/feishin:1.11.0@sha256:1eed97d6272d29d0a7de4c3c1357d4bc9c08cf8e304aa1014089f9111d22619c
    container_name: feishin
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - jellyfin
    networks:
      - t3_proxy
    # ports:
    #   - "9180:9180"
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.feishin-rtr.entrypoints: "websecure"
      traefik.http.routers.feishin-rtr.rule: "Host(`feishin.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.feishin-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.feishin-rtr.service: "feishin-svc"
      traefik.http.services.feishin-svc.loadbalancer.server.port: "9180"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Feishin"
      homepage.icon: "feishin.webp"
      homepage.href: "https://feishin.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Music Streaming using Jellyfin"
      ####### GLANCE #######
      glance.name: "feishin"
      glance.description: "Music Streaming using Jellyfin"
      glance.parent: "jellyfin"
    profiles:
      - media
