services:
  # NOTE: First, create `filebrowser` folder in appdata.
  # For custom.css: change Global Settings->branding path to "config"
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.63.2@sha256:4dce87308b9f9cfbcf8d0a284fc9565d2b515530a6bae2d920b388161e093f26
    profiles:
      - media
    restart: $RESTART_POLICY_MEDIA
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/filebrowser:/config
      - $REPO_PATH/appdata/filebrowser:/database
      - $USERDIR:/srv/Home
      - $DIR_HARDDISKROOT:/srv/Harddisk
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FB_NOAUTH: true # NOTE: If you change it, remove and re-create database.db
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.filebrowser-rtr.entrypoints: "websecure"
      traefik.http.routers.filebrowser-rtr.rule: "Host(`filebrowser.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.filebrowser-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.filebrowser-rtr.service: "filebrowser-svc"
      traefik.http.services.filebrowser-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "FileBrowser"
      homepage.icon: "filebrowser.svg"
      homepage.href: "https://filebrowser.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Browser"
      ####### GLANCE #######
      glance.name: "FileBrowser"
      glance.icon: "sh:filebrowser"
      glance.url: "https://filebrowser.$DOMAINNAME"
      glance.description: "File Browser"
