services:
  freshrss:
    container_name: freshrss
    image: lscr.io/linuxserver/freshrss@sha256:4cf45b2c316286f446a3eb2d7034a300c8488147bb6deb434f196167facc46c2
    restart: $RESTART_POLICY_OTHERS
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/freshrss:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.freshrss-rtr.entrypoints: "websecure"
      traefik.http.routers.freshrss-rtr.rule: "Host(`freshrss.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.freshrss-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.freshrss-rtr.service: "freshrss-svc"
      traefik.http.services.freshrss-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "FreshRSS"
      homepage.icon: "freshrss.svg"
      homepage.href: "https://freshrss.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "RSS Reader"
    profiles:
      - reading
