services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake:v26.03.3@sha256:2b1eb1e34cf2edba2590c3ab768206a11cf8916fbe8a8a3391fe74d9eabcdce0
    volumes:
      - $REPO_PATH/data/downloads:/data/downloads
      - $REPO_PATH/appdata/handbrake/config:/config
      - $REPO_PATH/appdata/handbrake/watch:/watch
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      UMASK: 002
      TZ: $TZ
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      AUTOMATED_CONVERSION_KEEP_SOURCE: 1
      VNC_PASSWORD: $HANDBRAKE_VNC_PASSWD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.handbrake-rtr.entrypoints: "websecure"
      traefik.http.routers.handbrake-rtr.rule: "Host(`handbrake.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.handbrake-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.handbrake-rtr.service: "handbrake-svc"
      traefik.http.services.handbrake-svc.loadbalancer.server.port: "5800"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "handbrake"
      homepage.icon: "handbrake.svg"
      homepage.href: "https://handbrake.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Converting Video Platform"
    profiles:
      - media
