services:
  homeserver-api-redis:
    image: docker.io/valkey/valkey:9@sha256:8436e10bc65c94886a91d4415b6a6dfa9cb5a306fb3b996e5bb67cd2b4854193
    container_name: homeserver-api-redis
    restart: $RESTART_POLICY_OTHERS
    command: --requirepass "${HOMESERVER_API_REDIS_PASSWORD}"
    profiles:
      - others
      - homeserver-api
    networks:
      - t3_proxy
    expose:
      - 6379
    user: $PUID:$PGID
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      HOMESERVER_API_REDIS_PASSWORD: $HOMESERVER_API_REDIS_PASSWORD
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "valkey-cli --no-auth-warning -a $${HOMESERVER_API_REDIS_PASSWORD} ping | grep -q PONG",
        ]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 10s

  homeserver-api-rabbitmq:
    image: rabbitmq:4-management@sha256:e43ca03df740d48770641b56ce1a26913c74a31e47c1ed36a58e8d91c10731b9
    container_name: homeserver-api-rabbitmq
    restart: $RESTART_POLICY_OTHERS
    hostname: "homeserver-api-rabbitmq"
    profiles:
      - others
      - homeserver-api
    networks:
      - t3_proxy
    expose:
      - "5672" # RabbitMQ AMQP port
      - "15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: $HOMESERVER_API_RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $HOMESERVER_API_RABBITMQ_PASSWORD
      RABBITMQ_VHOST: "/"
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: "2GB"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homeserver-api-rabbitmq-rtr.entrypoints: "websecure"
      traefik.http.routers.homeserver-api-rabbitmq-rtr.rule: "Host(`api-rabbitmq.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homeserver-api-rabbitmq-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homeserver-api-rabbitmq-rtr.service: "homeserver-api-rabbitmq-svc"
      traefik.http.services.homeserver-api-rabbitmq-svc.loadbalancer.server.port: "15672"
      ####### TINYAUTH #######
      tinyauth.apps.api-rabbitmq.config.domain: "api-rabbitmq.$DOMAINNAME"
      tinyauth.apps.api-rabbitmq.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-rabbitmq"
      homepage.icon: "rabbitmq.png"
      homepage.href: "https://api-rabbitmq.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Homeserver API RabbitMQ"

  homeserver-api-head:
    image: homeserver-api:latest
    container_name: homeserver-api-head
    restart: $RESTART_POLICY_OTHERS
    tty: true
    depends_on:
      - homeserver-api-redis
      - homeserver-api-rabbitmq
    build:
      context: $DIR_MYREPOS/homeserver-api
      dockerfile: $DIR_MYREPOS/homeserver-api/docker/Dockerfile
      target: development
    profiles:
      - others
      - homeserver-api
      - custom-build
    networks:
      - t3_proxy
    expose:
      - "8000" # API port
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    command: ["uv", "run", "--module", "app.__main__"]
    volumes:
      - $DIR_MYREPOS/homeserver-api/app:/app/app
    env_file:
      - $DIR_MYREPOS/homeserver-api/.env
    environment:
      - INSTANCE_TYPE=API
      - HOST=0.0.0.0
      - PORT=8000
      - RABBITMQ_HOST=homeserver-api-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=homeserver-api-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$HOMESERVER_API_REDIS_PASSWORD
      #### OTEL Related ####
      # TODO: Ingegrate OATS Testing https://github.com/grafana/docker-otel-lgtm/tree/main/examples/python
      - OTEL_SERVICE_NAME=homeserver-api-head
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector-agent:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      ## TODO: Does below needed?
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=apps,service.instance.id=homeserver-api-head-$MY_HOSTNAME
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homeserver-api-head-rtr.entrypoints: "websecure"
      traefik.http.routers.homeserver-api-head-rtr.rule: "Host(`api.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homeserver-api-head-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homeserver-api-head-rtr.service: "homeserver-api-head-svc"
      traefik.http.services.homeserver-api-head-svc.loadbalancer.server.port: "8000"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-head"
      homepage.icon: "homeserver-api.png"
      homepage.href: "https://api.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Homeserver API Head"

  homeserver-api-worker:
    image: homeserver-api:latest
    container_name: homeserver-api-worker
    restart: $RESTART_POLICY_OTHERS
    tty: true
    depends_on:
      - homeserver-api-redis
      - homeserver-api-rabbitmq
    build:
      context: $DIR_MYREPOS/homeserver-api
      dockerfile: $DIR_MYREPOS/homeserver-api/docker/Dockerfile
      target: development
    profiles:
      - others
      - homeserver-api
      - custom-build
    networks:
      - t3_proxy
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    command:
      - "uv"
      - "run"
      - "--module"
      - "taskiq"
      - "worker"
      - "app.worker.broker:broker"
      - "--use-process-pool"
      - "--workers"
      - "5"
      - "-fsd"
      - "-tp"
      - "[app/worker/tasks/*.py]"
    # <<: *gpu-all-deploy
    volumes:
      - $DIR_MYREPOS/homeserver-api/app:/app/app
    env_file:
      - $DIR_MYREPOS/homeserver-api/.env
    environment:
      - INSTANCE_TYPE=WORKER
      - RABBITMQ_HOST=homeserver-api-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=homeserver-api-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$HOMESERVER_API_REDIS_PASSWORD
      #### OTEL Related ####
      - OTEL_SERVICE_NAME=homeserver-api-worker
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector-agent:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      ## TODO: Does below needed?
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=apps,service.instance.id=homeserver-api-worker-$MY_HOSTNAME
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-worker"
      homepage.icon: "homeserver-api.png"
      homepage.target: "_blank"
      homepage.description: "Homeserver API Worker"
