services:
  jellyfin-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable@sha256:15c779152b4d754c0959eaae7d1bf0fdd74f44fea9c124ff7187e34c5d127d98
    container_name: jellyfin-vue
    restart: $RESTART_POLICY_MEDIA
    # depends_on:
    #   - jellyfin
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # environment:
    #   - DEFAULT_SERVERS=demo.jellyfin.org,jellyfin:8096
    #   - DISABLE_SERVER_SELECTION=0
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.jellyfin-vue-rtr.entrypoints: "websecure"
      traefik.http.routers.jellyfin-vue-rtr.rule: "Host(`jellyfin_vue.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.jellyfin-vue-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.jellyfin-vue-rtr.service: "jellyfin-vue-svc"
      traefik.http.services.jellyfin-vue-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Jellyfin Vue"
      homepage.icon: "jellyfin.svg"
      homepage.href: "https://jellyfin_vue.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Jellyfin with Vue UI"
    profiles:
      - media
