# TODO: Harden
services:
  nzbdav:
    image: nzbdav/nzbdav:0.6.4@sha256:fc44a9d33adceddc4397eb660b4fcaf1917e23323fb80dea0645f56db129562f
    container_name: nzbdav
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - root
      - media
    networks:
      - t3_proxy
    expose:
      - "3000"
    # user: $PUID:$PGID
    # read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    pids_limit: 256
    cpus: "1.0"
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/nzbdav:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fsS",
          "--max-time",
          "3",
          "-o",
          "/dev/null",
          "http://127.0.0.1:3000/",
        ]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.nzbdav-rtr.entrypoints: "websecure"
      traefik.http.routers.nzbdav-rtr.rule: "Host(`nzbdav.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.nzbdav-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.nzbdav-rtr.service: "nzbdav-svc"
      traefik.http.services.nzbdav-svc.loadbalancer.server.port: "3000"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "nzbdav"
      homepage.icon: "nzbdav.png"
      homepage.href: "https://nzbdav.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Usenet streaming with a WebDAV server and a SABnzbd-compatible API"
      ####### GLANCE #######
      glance.name: "nzbdav"
      glance.icon: "sh:nzbdav"
      glance.url: "https://nzbdav.$DOMAINNAME"
      glance.description: "Usenet streaming with a WebDAV server and a SABnzbd-compatible API"
