services:
  perlite-build:
    container_name: perlite-build
    image: sec77/perlite:1.6.1@sha256:e4912b9a014b5f68b0f29386244e5600e935de09e66906fb13e849f54d2b300c
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - reading
    networks:
      - t3_proxy
    expose:
      - 9000 # for nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DIR_NOTES/Markdown:/var/www/perlite/Vault:ro
    environment:
      NOTES_PATH: Vault
      HIDE_FOLDERS: private,trash
      HIDDEN_FILE_ACCESS: false
      LINE_BREAKS: true
      ABSOLUTE_PATHS: false
      ALLOWED_FILE_LINK_TYPES: pdf,mp4
      DISABLE_POP_HOVER: false
      SHOW_TOC: true
      SHOW_LOCAL_GRAPH: true
      HOME_FILE: index
      FONT_SIZE: 15
      HTML_SAFE_MODE: true
      TEMP_PATH: /tmp
      SITE_TITLE: Digital.Garden
      SITE_TYPE: article
      SITE_URL: https://perlite.$DOMAINNAME
      SITE_IMAGE:
      SITE_DESC: Ilkerflix Digital Garden
      SITE_NAME: Perlite
      SITE_TWITTER:
      SITE_LOGO: perlite.svg
      SITE_HOMEPAGE:
      SITE_GITHUB: https://github.com/ilkersigirci

  perlite:
    container_name: perlite
    image: nginx:stable-alpine@sha256:0272e4604ed93c1792f03695a033a6e8546840f86e0de20a884bb17d2c924883
    restart: $RESTART_POLICY_OTHERS
    depends_on:
      - perlite-build
    profiles:
      - reading
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/perlite/web.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - perlite-build
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.perlite-rtr.entrypoints: "websecure"
      traefik.http.routers.perlite-rtr.rule: "Host(`perlite.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.perlite-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.perlite-rtr.service: "perlite-svc"
      traefik.http.services.perlite-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "Perlite"
      homepage.icon: "obsidian.svg"
      homepage.href: "https://perlite.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A web-based markdown viewer optimized for Obsidian"
