services:
  podgrab:
    image: akhilrex/podgrab:1.0.0@sha256:bce133f3f5111381f63d9341313fa7ce7e16209068e8a06e6db2c4ed33972b87
    container_name: podgrab
    restart: $RESTART_POLICY_MEDIA
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/podgrab:/config
      - $DIR_MEDIA/Podcasts:/assets
    environment:
      CHECK_FREQUENCY: 240
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.podgrab-rtr.entrypoints: "websecure"
      traefik.http.routers.podgrab-rtr.rule: "Host(`podgrab.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.podgrab-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.podgrab-rtr.service: "podgrab-svc"
      traefik.http.services.podgrab-svc.loadbalancer.server.port: "8080"
    profiles:
      - media
