services:
  # Default user-pass: admin / adminadmin
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent@sha256:8f7a1da9644340c737e3211ecc910a416d4295076e6b2824a4afcd1f4e3576e2
    container_name: qbittorrent
    restart: $RESTART_POLICY_MEDIA
    # network_mode: "service:gluetun"
    # depends_on:
    #   - gluetun
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/qbittorrent:/config
      - $DIR_MEDIA/Downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      WEBUI_PORT: 8080
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.qbittorrent-rtr.entrypoints: "websecure"
      traefik.http.routers.qbittorrent-rtr.rule: "Host(`torrent.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.qbittorrent-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.qbittorrent-rtr.service: "qbittorrent-svc"
      traefik.http.services.qbittorrent-svc.loadbalancer.server.port: "8080"
      # - traefik.http.services.qbittorrent-svc.loadbalancer.passhostheader=false # Not needed
      ####### TINYAUTH #######
      tinyauth.apps.qbittorrent.config.domain: "torrent.$DOMAINNAME"
      tinyauth.apps.qbittorrent.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "qBittorrent"
      homepage.icon: "qbittorrent.svg"
      homepage.href: "https://torrent.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Download Client"
    profiles:
      - media
