services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1.10360-ls300@sha256:b01097ad2d948c9f5eca39eb60bb529e2e55b0738c4bf7db09383bef0abab59d
    container_name: radarr
    depends_on:
      - prowlarr
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - arr
    networks:
      - t3_proxy
    #  t3_proxy:
    #    ipv4_address: 192.168.90.162
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/radarr:/config
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      # - $REPO_PATH/data/radarr/MediaCover:/config/MediaCover
      - $DIR_MEDIA/Downloads:/data/downloads
      - $DIR_MEDIA/Movies_Radarr:/data/media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      # HTTP Routers Auth Bypass
      traefik.http.routers.radarr-rtr-bypass.entrypoints: "websecure"
      #- "traefik.http.routers.radarr-rtr-bypass.rule=Host(`radarr.$DOMAINNAME`) && (Header(`X-Api-Key`, `$RADARR_API_KEY`) || Query(`apikey`, `$RADARR_API_KEY`))"
      traefik.http.routers.radarr-rtr-bypass.rule: "Host(`radarr.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth
      traefik.http.routers.radarr-rtr-bypass.priority: "100"
      # HTTP Routers Auth
      traefik.http.routers.radarr-rtr.entrypoints: "websecure"
      traefik.http.routers.radarr-rtr.rule: "Host(`radarr.$DOMAINNAME`)"
      traefik.http.routers.radarr-rtr.priority: "99"
      # Middlewares
      # traefik.http.routers.radarr-rtr-bypass.middlewares: "chain-no-auth@file"
      traefik.http.routers.radarr-rtr.middlewares: "chain-tinyauth@file"
      # HTTP Services
      traefik.http.routers.radarr-rtr.service: "radarr-svc"
      traefik.http.routers.radarr-rtr-bypass.service: "radarr-svc"
      traefik.http.services.radarr-svc.loadbalancer.server.port: "7878"
      ####### TINYAUTH #######
      tinyauth.apps.radarr.config.domain: "radarr.$DOMAINNAME"
      tinyauth.apps.radarr.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Radarr"
      homepage.icon: "radarr.svg"
      homepage.href: "https://radarr.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Movie Manager"
