services:
  remmina:
    image: lscr.io/linuxserver/remmina@sha256:d7eda098a069aaca7c125734f02b72a67e63b6ea3911b69ca6f59198d67f8bf4
    container_name: remmina
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/remmina:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.remmina-rtr.entrypoints: "websecure"
      traefik.http.routers.remmina-rtr.rule: "Host(`remmina.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.remmina-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.remmina-rtr.service: "remmina-svc"
      traefik.http.services.remmina-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.remmina.config.domain: "remmina.$DOMAINNAME"
      tinyauth.apps.remmina.ip.bypass: "$LOCAL_IPS"
