services:
  sd-next:
    container_name: sd-next
    image: vladmandic/sdnext-cuda:latest@sha256:392eb4538142ebc6c2d7b6bac2e951455e016e9a8778b65991ba4a5ab2209af6
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/sd-next:/mnt/data:rw
      - $MLMODELSDIR/sdnext:/mnt/models:ro
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sdnext-rtr.entrypoints: "websecure"
      traefik.http.routers.sdnext-rtr.rule: "Host(`sdnext.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sdnext-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.sdnext-rtr.service: "sdnext-svc"
      traefik.http.services.sdnext-svc.loadbalancer.server.port: "7860"
      ####### TINYAUTH #######
      tinyauth.apps.sdnext.config.domain: "sdnext.$DOMAINNAME"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]
