services:
  splitpro-db:
    image: postgres:18.3@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    container_name: splitpro-db
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - splitpro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - t3_proxy
    expose:
      - "5432"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /var/run/postgresql:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/data/splitpro-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  splitpro:
    image: ghcr.io/oss-apps/splitpro:v2.0.3@sha256:6e3cbc88dbd4c1b64dcb39b1c24ae8da71c8a475f1e012345da1d1ed0dd2cbe9
    container_name: splitpro
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      splitpro-db:
        condition: service_healthy
    profiles:
      - media
      - splitpro
    networks:
      - t3_proxy
    ports:
      - "1004:3000"
    security_opt:
      - no-new-privileges:true
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@splitpro-db:5432/postgres
      NEXTAUTH_URL: https://split.$BASE_DOMAINNAME
      NEXTAUTH_SECRET: $SPLITPRO_NEXTAUTH_SECRET
      ENABLE_SENDING_INVITES: false
      DISABLE_EMAIL_SIGNUP: true
      DEFAULT_HOMEPAGE: /balances
      # OIDC Setup - Don't mind the `Authentik` part, it works with Pocket ID
      AUTHENTIK_ID: $SPLITPRO_CLIENT_ID
      AUTHENTIK_SECRET: $SPLITPRO_CLIENT_SECRET
      AUTHENTIK_ISSUER: https://pocketid.$BASE_DOMAINNAME
    labels:
      # traefik.enable: "true"
      # ## HTTP Routers
      # traefik.http.routers.splitpro-rtr.entrypoints: websecure
      # traefik.http.routers.splitpro-rtr.rule: Host(`split.$DOMAINNAME`)
      # ## Middlewares
      # traefik.http.routers.splitpro-rtr.middlewares: "chain-tinyauth-relaxed@file"
      # ## HTTP Services
      # traefik.http.routers.splitpro-rtr.service: splitpro-svc
      # traefik.http.services.splitpro-svc.loadbalancer.server.port: "3000"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "splitpro"
      homepage.icon: "splitpro.png"
      homepage.href: "https://split.$BASE_DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Open source alternative to Splitwise"
      ####### GLANCE #######
      glance.name: "splitpro"
      glance.icon: "sh:splitpro"
      glance.url: "https://split.$BASE_DOMAINNAME"
      glance.description: "Open source alternative to Splitwise"
