services:
  sshwifty:
    container_name: sshwifty
    image: niruix/sshwifty:0.4.5-beta-release@sha256:676b4c32640183eeeb7e3785fa1d45eda756715c8c369efaceca0962e58ef605
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - $REPO_PATH/appdata/czkawka:/config:rw
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sshwifty-rtr.entrypoints: "websecure"
      traefik.http.routers.sshwifty-rtr.rule: "Host(`ssh.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sshwifty-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.sshwifty-rtr.service: "sshwifty-svc"
      traefik.http.services.sshwifty-svc.loadbalancer.server.port: "8182"
      ####### TINYAUTH #######
      tinyauth.apps.ssh.config.domain: "ssh.$DOMAINNAME"
      tinyauth.apps.ssh.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Sshwifty"
      homepage.icon: "sshwifty.svg"
      homepage.href: "https://sshwifty.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Web SSH - Telnet"
