services:
  sunshine:
    image: ghcr.io/lizardbyte/sunshine:latest-ubuntu-22.04@sha256:3e0e7644629547f06019512259e564739bec1b0edc74f7f6f1709980261d380b
    container_name: sunshine
    restart: $RESTART_POLICY_MAINTENANCE
    networks:
      - t3_proxy
    ports:
      # - "48010:48010"
      - "47984-47990:47984-47990/tcp"
      - "47998-48000:47998-48000/udp"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/sunshine:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sunshine-rtr.entrypoints: "websecure"
      traefik.http.routers.sunshine-rtr.rule: "Host(`sunshine.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sunshine-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.sunshine-rtr.service: "sunshine-svc"
      traefik.http.services.sunshine-svc.loadbalancer.server.port: "47990"
      ####### TINYAUTH #######
      tinyauth.apps.sunshine.config.domain: "sunshine.$DOMAINNAME"
      tinyauth.apps.sunshine.ip.bypass: "$LOCAL_IPS"
    profiles:
      - monitoring
