services:
  traefik-crowdsec-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer@sha256:e3e8f33923d2871069de08dd2931a9eb6c6760f76d6b9e3229d3b9c84211dd94
    container_name: traefik-crowdsec-bouncer
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      GIN_MODE: release # default is debug (more logs)
      CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_BOUNCER_TRAEFIK_API_KEY
      CROWDSEC_AGENT_HOST: $CROWDSEC_LAPI_HOST:$CROWDSEC_LAPI_PORT # CrowdSec host and port
