services:
  webfinger:
    image: nginx:latest@sha256:3acc8b9cc6421db48299559e937b2ade69ddd609453b4f44c21ccb239d614535
    container_name: webfinger
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/webfinger:/usr/share/nginx/html:ro
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.webfinger-rtr.entrypoints: "websecure"
      traefik.http.routers.webfinger-rtr.rule: "Host(`$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.webfinger-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.webfinger-rtr.service: "webfinger-svc"
      traefik.http.services.webfinger-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "webfinger"
      homepage.icon: "webfinger.png"
      homepage.href: "https://$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Webfinger OIDC provider"
      ####### GLANCE #######
      glance.name: "webfinger"
      glance.icon: "sh:webfinger"
      glance.url: "https://$DOMAINNAME"
      glance.description: "Webfinger OIDC provider"
