# Docs: https://games-on-whales.github.io/wolf/stable/user/quickstart.html
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable@sha256:ff82c125c9b79b2e9443de2b0eaec40c904edb03291680d408cccd57c1d59c76
    container_name: wolf
    environment:
      - NVIDIA_DRIVER_VOLUME_NAME=nvidia-driver-vol
      # - WOLF_LOG_LEVEL=DEBUG
      - HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - /etc/wolf/:/etc/wolf:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - nvidia-driver-vol:/usr/nvidia:rw
      - /mnt/udev:/run/udev:rw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2
      - /dev/nvidiactl
      - /dev/nvidia0
      - /dev/nvidia-modeset
    device_cgroup_rules:
      - "c 13:* rmw"
    network_mode: host
    restart: unless-stopped

# NOTE: Needs to be created beforehand
volumes:
  nvidia-driver-vol:
    external: true
