name: notes

networks:
  t2_proxy:
    external: true

services:
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    # TODO: Probably needed for connecting to phone
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/syncthing:/config
      # - $APKDIR:/apk
      - $NOTESDIR:/notes
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.syncthing-rtr.entrypoints=https"
      - "traefik.http.routers.syncthing-rtr.rule=Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.syncthing-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.syncthing-rtr.service=syncthing-svc"
      - "traefik.http.services.syncthing-svc.loadbalancer.server.port=8384"

  # TODO: Add local.ini
  # https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server.md#setup-couchdb-to-your-server
  # passphase: obsidian
  couchdb:
    container_name: couchdb
    image: couchdb:latest  # TODO: ghcr.io/
    restart: $BASE_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/couchdb:/opt/couchdb/data
      - $CONFIGDIR/couchdb/local.ini:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.couchdb-rtr.entrypoints=https"
      - "traefik.http.routers.couchdb-rtr.rule=Host(`couchdb.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.couchdb-rtr.middlewares=chain-couchdb@file" # NOTE: chain-authelia not working
      ## HTTP Services
      - "traefik.http.routers.couchdb-rtr.service=couchdb-svc"
      - "traefik.http.services.couchdb-svc.loadbalancer.server.port=5984"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -u admin:admin -s http://localhost:5984/_up | grep -Eo '\"status\":\"ok\"' || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3

  logseq:
    container_name: logseq
    image: ghcr.io/logseq/logseq-webapp:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
      # volumes:
      # - $NOTESDIR:/notes
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.logseq-rtr.entrypoints=https"
      - "traefik.http.routers.logseq-rtr.rule=Host(`logseq.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.logseq-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.logseq-rtr.service=logseq-svc"
      - "traefik.http.services.logseq-svc.loadbalancer.server.port=80"
  
  flatnotes:
    container_name: flatnotes
    # image: dullage/flatnotes:latest
    image: dullage/flatnotes:v3.0.0-rc.3
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FLATNOTES_AUTH_TYPE=none
      # - FLATNOTES_USERNAME="user"
      # - FLATNOTES_PASSWORD="changeMe!"
      - FLATNOTES_SECRET_KEY="change-stability-pushchair"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.notes-rtr.entrypoints=https"
      - "traefik.http.routers.notes-rtr.rule=Host(`notes.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.notes-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.notes-rtr.service=notes-svc"
      - "traefik.http.services.notes-svc.loadbalancer.server.port=8080"

  # TODO: Add wallabag
  # Link: https://github.com/wallabag/docker

  # TODO: Add shiori
  # Link: https://github.com/geekgonecrazy/shiori/tree/pwa-offline

  kavita:
    container_name: kavita
    image: kizaing/kavita:latest
    # image: ghcr.io/kareadita/kavita:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/kavita:/kavita/config
      - $MEDIADIR/Books:/book
      # - ./manga:/manga
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kavita-rtr.entrypoints=https"
      - "traefik.http.routers.kavita-rtr.rule=Host(`kavita.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.kavita-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.kavita-rtr.service=kavita-svc"
      - "traefik.http.services.kavita-svc.loadbalancer.server.port=5000"

  obsidian:
    container_name: obsidian
    image: lscr.io/linuxserver/obsidian:latest
    restart: $OTHERS_RESTART_POLICY
    shm_size: "1gb"
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/vaults
      # - /path/to/config:/config
    depends_on:
      couchdb:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TITLE=Obsidian
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.obsidian-rtr.entrypoints=https"
      - "traefik.http.routers.obsidian-rtr.rule=Host(`obsidian.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.obsidian-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.obsidian-rtr.service=obsidian-svc"
      - "traefik.http.services.obsidian-svc.loadbalancer.server.port=3000"
    # devices:
    #   - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3

  obsidian-custom:
    container_name: obsidian-custom
    image: obsidian-custom:latest
    build:
      context: $DESKTOPAPPDOCKERFILES/Obsidian
      dockerfile: $DESKTOPAPPDOCKERFILES/Obsidian/Dockerfile
      # dockerfile: $DESKTOPAPPDOCKERFILES/Obsidian/Dockerfile_Appimage
      # args:
      #   - OBSIDIAN_VERSION=1.5.12
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/vaults
      # - /path/to/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - DOCKER_MODS=linuxserver/mods:universal-git
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # For watchtower
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.obsidian-custom-rtr.entrypoints=https"
      - "traefik.http.routers.obsidian-custom-rtr.rule=Host(`obsidiancustom.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.obsidian-custom-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.obsidian-custom-rtr.service=obsidian-custom-svc"
      - "traefik.http.services.obsidian-custom-svc.loadbalancer.server.port=3000"
  
  # NOTE: For client app, change (for flatpak):
  #  nano ~/.var/app/com.librumreader.librum/config/Librum-Reader/Librum.conf
  # selfHosted=true
  # serverHost=https://$DOMAINNAME
  librum:
    container_name: librum
    build: $GITHUBREPOSDIR/Librum-Server
    image: librum:latest
    hostname: librum
    restart: $OTHERS_RESTART_POLICY
    depends_on:
      - librum_db
    networks:
      - t2_proxy
    # ports:
    #   - "5000:5000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $MEDIADIR/Books/Librum:/var/lib/librum-server/librum_storage
    environment:
      - JWTValidIssuer=exampleIssuer
      - JWTKey=exampleOfALongSecretToken
      - SMTPEndpoint=smtp.example.com
      - SMTPUsername=mailuser123
      - SMTPPassword=smtpUserPassword123
      - SMTPMailFrom=mailuser123@example.com
      - DBConnectionString=Server=librum_db;port=3306;Database=librum;Uid=librum;Pwd=mariadb;
      - AdminEmail=admin@mail.com
      - AdminPassword=strongPassword123
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.librum-rtr.entrypoints=https"
      - "traefik.http.routers.librum-rtr.rule=Host(`librum.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.librum-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.librum-rtr.service=librum-svc"
      - "traefik.http.services.librum-svc.loadbalancer.server.port=5000"

  librum_db:
    image: mariadb:latest
    container_name: librum_db
    hostname: librum_db
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/librum_db:/var/lib/mysql
    environment:
      - MARIADB_USER=librum
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=librum
      - MARIADB_ROOT_PASSWORD=mariadb
    
  
  # volglass:
  #   image: volglass:latest
  #   container_name: volglass
  #   build:
  #     # context: $GITHUBREPOSDIR/volglass
  #     # dockerfile: $GITHUBREPOSDIR/volglass/Dockerfile
  #     context: $DOCKERDIR/stacks/notes
  #     dockerfile: $DOCKERDIR/stacks/notes/Dockerfile_volglass
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $NOTESDIR/Markdown:/app/posts:ro
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     # - DOCKER_MODS=linuxserver/mods:universal-git
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.volglass-rtr.entrypoints=https"
  #     - "traefik.http.routers.volglass-rtr.rule=Host(`volglass.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.volglass-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.volglass-rtr.service=volglass-svc"
  #     - "traefik.http.services.volglass-svc.loadbalancer.server.port=3000"
