services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.0.1-openvino@sha256:d5561b55333f88ac4fe240f846c89f498693b0a9cedef6b1c45fcca0c7969cc4
    mem_limit: 1G
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      OMP_NUM_THREADS: 8
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
