services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5-openvino@sha256:71cd5a681823c4b818f4b24b3f05816eccc3d085559e7615f695bde77e64f1f2
    mem_limit: 1G
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      OMP_NUM_THREADS: 8
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
