services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.3.0-openvino@sha256:a79670d05f8da90c86f8074afe1beaf51abee53c58692ad45cae2efd9afd4aca
    mem_limit: 1G
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      OMP_NUM_THREADS: 8
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
