services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.0.2-cuda@sha256:cad0c6c38c60bd6a5a1929cbed01eecc105bcb58775682c137497632f8db5adc
    cpus: "4.0"
    mem_limit: 2G
    environment:
      MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]
