services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.2.4-cuda@sha256:b9fdebfe7f07ff71f77e9d67d509d83c5e055da486a07c12080669c82a80c65e
    cpus: "4.0"
    mem_limit: 2G
    environment:
      MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]
