services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v3.0.3-cuda@sha256:0d66acce99224495fda2288e2d8f52b459712b2e897e67b492729bce07775c08
    cpus: "4.0"
    mem_limit: 2G
    environment:
      MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]
