version: "3.9"
name: cloud

networks:
  t2_proxy:
    external: true

######################################### NEXTCLOUD ##########################################
services:
  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    hostname: mariadb
    networks:
      # t2_proxy:
      #   ipv4_address: 192.168.90.250
      - nextcloud
    security_opt:
      - no-new-privileges:true
    ports:
      - "$MARIADB_PORT:3306"
    volumes:
      - $DOCKERDIR/appdata/mariadb/data:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ      
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - FILE__MYSQL_PASSWORD=/run/secrets/mysql_password
      # Note FILE__ (double underscore) - Issue #127
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_password

  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ## NOT WORKING
    # entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru
    # command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "$REDIS_PORT:6379"
    networks:
      - nextcloud
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # environment:
    #   REDIS_PASSWORD: $REDIS_PASSWORD

  # # Redis Commander - Redis Management Tool
  # rediscommander:
  #   container_name: rediscommander
  #   image: rediscommander/redis-commander:latest
  #   restart: unless-stopped
  #   # profiles:
  #   # - apps
  #   networks:
  #     - t2_proxy
  #     - default
  #   security_opt:
  #     - no-new-privileges:true
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PASSWORD=$REDIS_PASSWORD
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.rediscommander-rtr.entrypoints=https"
  #     - "traefik.http.routers.rediscommander-rtr.rule=Host(`redis.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.rediscommander-rtr.middlewares=chain-no-auth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.rediscommander-rtr.service=rediscommander-svc"
  #     - "traefik.http.services.rediscommander-svc.loadbalancer.server.port=8081"

  # Nextcloud Docker Application
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    # Same as above
    hostname: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
      - t2_proxy
    ports:
      - 777:80
    # Persistent volumes with bind mounts to easily move/backup data
    volumes:
      - $DOCKERDIR/appdata/nextcloud/data:/var/www/html
      - $DOCKERDIR/appdata/nextcloud/cloud:/var/www/html/data
      # - $NEXTCLOUD_DIR:/var/www/html/data
    environment:
      # PUID: $PUID
      # PGID: $PGID
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAIN: $NEXTCLOUD_DOMAIN_NAME
      TRUSTED_PROXIES: 192.168.90.0/24
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`$NEXTCLOUD_DOMAIN_NAME`)"
      - "traefik.http.routers.nextcloud.tls=true"
      ## Middlewares
      - "traefik.http.routers.nextcloud.middlewares=chain-nextcloud@file"
      ## HTTP Services
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      ######################################################################################
      ## NOT_WORKING
      # ## TCP Routers
      # - "traefik.tcp.routers.nextcloud-tcp.entrypoints=https"
      # - "traefik.tcp.routers.nextcloud-tcp.rule=HostSNI(`nextcloud.$DOMAINNAME`)"
      # - "traefik.tcp.routers.nextcloud-tcp.tls=true"
      # # - "traefik.tcp.routers.nextcloud-tcp.tls.certresolver=dns-cloudflare"
      # - "traefik.tcp.routers.nextcloud-tcp.tls.passthrough=true"
      # ## TCP Services
      # - "traefik.tcp.routers.nextcloud-tcp.service=nextcloud-tcp-svc"
      # - "traefik.tcp.services.nextcloud-tcp-svc.loadbalancer.server.port=443"