---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Bookmarks

# - Developer:
#     - Homepage Official:
#         - abbr: GH
#           href: https://github.com/benphelps/homepage
#     - My Github:
#         - abbr: GH
#           href: https://github.com/ilkersigirci
#     - Runpod Playground:
#         - abbr: GH
#           href: https://github.com/ilkersigirci/runpod-playground
          

# - Social:
#     - My Blog:
#         - abbr: BL
#           href: https://blog.ilkerflix.com
#     - Reddit Selfhosted:
#         - abbr: RE
#           href: https://reddit.com/r/selfhosted
#     - Hacker News:
#         - abbr: HN
#           href: https://hn.svelte.dev

# - Entertainment:
#     - YouTube:
#         - abbr: YT
#           href: https://youtube.com/
#     - Twitter:
#         - abbr: TW
#           href: https://twitter.com/