---
# -------------------------------------------------------------------------
# PREREQUISITES:
# 1. Install Unofficial Bitwarden CLI ('rbw') https://github.com/doy/rbw
# 2. Ensure rbw is configured and unlocked (run 'rbw login' and 'rbw unlock')
# -------------------------------------------------------------------------

- name: Showcase Vaultwarden as Secret Manager
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if rbw is unlocked
      ansible.builtin.command: rbw unlocked
      changed_when: false
      register: rbw_check
      ignore_errors: true
      failed_when: false

    - name: Fail if rbw is not ready
      ansible.builtin.fail:
        msg: "rbw is not unlocked or configured. Please run 'rbw unlock'."
      # when: "'locked' in rbw_check.stderr or 'locked' in rbw_check.stdout"
      when: >
        rbw_check.rc is defined and rbw_check.rc != 0 or
        'locked' in (rbw_check.stderr | default('')) or
        'locked' in (rbw_check.stdout | default(''))

    - name: Set ansible credentials
      ansible.builtin.set_fact:
        ansible_user: "{{ lookup('pipe', 'rbw get  Ansible.Test --field username') }}"
        ansible_password: "{{ lookup('pipe', 'rbw get Ansible.Test') }}"

    - name: Display the retrieved username
      ansible.builtin.debug:
        msg: "The ansible user is: {{ ansible_user }}"
      failed_when: false

    - name: Display the retrieved password
      ansible.builtin.debug:
        msg: "The ansible password is: {{ ansible_password }}"
      failed_when: false
