services:
  backrest:
    container_name: backrest
    image: garethgeorge/backrest:latest-alpine
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
      - backup
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    hostname: backrest
    volumes:
      - $DOCKERDIR/appdata/backrest/data:/data
      - $DOCKERDIR/appdata/backrest/config:/config
      - $DOCKERDIR/appdata/backrest/cache:/cache
      - $NOTESDIR/Markdown:/userdata/Markdown:ro # [optional] mount local paths to backup here.
      # - /MY-REPOS:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
      - $CONFIGDIR/rclone:/root/.config/rclone:rw
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=$TZ
      # - RCLONE_CONFIG=/root/.config/rclone/rclone.conf
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.backrest-rtr.entrypoints=websecure"
      - "traefik.http.routers.backrest-rtr.rule=Host(`backrest.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.backrest-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.backrest-rtr.service=backrest-svc"
      - "traefik.http.services.backrest-svc.loadbalancer.server.port=9898"