# NOTE: For OIDC: PocketID -> Application Configuration -> Enable Emails Verified
services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: $MAINTENANCE_RESTART_POLICY
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/beszel:/beszel_data
    environment:
      TZ: $TZ
      USER_CREATION: false
      # NOTE: Can be uncomment this if OIDC is used.
      # DISABLE_PASSWORD_AUTH: true
    profiles:
      - monitoring
    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s
      interval: 1m
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.beszel-rtr.entrypoints: "websecure"
      traefik.http.routers.beszel-rtr.rule: "Host(`beszel.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.beszel-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.beszel-rtr.service: "beszel-svc"
      traefik.http.services.beszel-svc.loadbalancer.server.port: "8090"
      ####### TINYAUTH #######
      tinyauth.apps.beszel.config.domain: beszel.$DOMAINNAME
      tinyauth.apps.beszel.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: Monitoring
      homepage.name: Beszel
      homepage.icon: beszel.svg
      homepage.href: https://beszel.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Lightweight server monitoring hub with historical data, docker stats, and alerts
      homepage.widget.type: beszel
      homepage.widget.url: http://beszel:8090
      homepage.widget.username: $BESZEL_EMAIL
      homepage.widget.password: $BESZEL_PASSWORD
      # - homepage.widget.systemId=$MY_HOSTNAME
      homepage.widget.version: "2"
