services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: $MAINTENANCE_RESTART_POLICY
    # network_mode: host
    networks:
      - t3_proxy
      - socket_proxy
    # volumes:
    #   # monitor other disks / partitions by mounting a folder in /extra-filesystems
    #   # - /mnt/d:/extra-filesystems/sda1:ro
    environment:
      DOCKER_HOST: "tcp://docker-socket-proxy:2375"
      PORT: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICbYjtH7YvUc+kTFonrxuYC9B6UteA8ktzCsOTJWeUK1'
    profiles:
      - monitoring

  # NOTE: When adding the local agent on the same docker network, use its name: `beszel-agent` not the IP address.
  # That way, the agent doesn't need to expose the port.
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: $MAINTENANCE_RESTART_POLICY
    depends_on:
      - beszel-agent
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/beszel:/beszel_data
    environment:
      TZ: "${TZ}"
      USER_CREATION: "false"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.beszel-rtr.entrypoints=websecure"
      - "traefik.http.routers.beszel-rtr.rule=Host(`beszel.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.beszel-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.beszel-rtr.service=beszel-svc"
      - "traefik.http.services.beszel-svc.loadbalancer.server.port=8090"
      ####### HOMEPAGE #######
      - homepage.group=Monitoring
      - homepage.name=Beszel
      - homepage.icon=beszel.svg
      - homepage.href=https://beszel.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Lightweight server monitoring hub with historical data, docker stats, and alerts
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel:8090
      - homepage.widget.username=$BESZEL_EMAIL
      - homepage.widget.password=$BESZEL_PASSWORD
      # - homepage.widget.systemId=homeserver
      - homepage.widget.version=2
    profiles:
      - monitoring
