services:
  bichon:
    image: rustmailer/bichon:latest
    container_name: bichon
    restart: $MEDIA_RESTART_POLICY
    profiles:
      - media
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATADIR/bichon:/data
    environment:
      BICHON_HTTP_PORT: 15630
      BICHON_LOG_LEVEL: info
      BICHON_ROOT_DIR: /data
      BICHON_PUBLIC_URL: https://mailarchive.$DOMAINNAME
      BICHON_CORS_ORIGINS: https://mailarchive.$DOMAINNAME
      BICHON_ENCRYPT_PASSWORD: $BICHON_ENCRYPT_PASSWORD
      # BICHON_ENABLE_ACCESS_TOKEN: true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bichon-rtr.entrypoints: "websecure"
      traefik.http.routers.bichon-rtr.rule: "Host(`mailarchive.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bichon-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.bichon-rtr.service: "bichon-svc"
      traefik.http.services.bichon-svc.loadbalancer.server.port: "15630"
      ####### TINYAUTH #######
      tinyauth.apps.bichon.config.domain: mailarchive.$DOMAINNAME
      tinyauth.apps.bichon.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Bichon"
      homepage.icon: "bichon.svg"
      homepage.href: "https://mailarchive.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Lightweight mail archiver based on Rust"
      ####### GLANCE #######
      glance.name: "bichon"
      glance.icon: "sh:bichon"
      glance.url: "https://mailarchive.$DOMAINNAME"
      glance.description: "Lightweight mail archiver based on Rust"
