services: 
  chromium:
    container_name: chromium
    image: lscr.io/linuxserver/ungoogled-chromium:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    shm_size: "1gb"
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: chromium
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.chromium-rtr.entrypoints=websecure"
      - "traefik.http.routers.chromium-rtr.rule=Host(`chromium.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.chromium-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.chromium-rtr.service=chromium-svc"
      - "traefik.http.services.chromium-svc.loadbalancer.server.port=3000"
      ####### HOMEPAGE #######
      - homepage.group=DesktopApps
      - homepage.name=Ungoogled Chromium
      - homepage.icon=chromium.svg
      - homepage.href=https://chromium.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Ungoogled Chromium Browser
    # devices:
    #   - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 2m
      timeout: 5s
      retries: 3
    profiles:
      - desktop_apps