services:
  deemix:
    image: ghcr.io/bambanah/deemix:latest
    container_name: deemix
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/deemix:/config
      - $CONFIGDIR/deemix/config.json:/config/config.json
      - $CONFIGDIR/deemix/login.json:/config/login.json
      - $MEDIADIR/Music/Deemix:/downloads
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=022
      - DEEMIX_SINGLE_USER=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.deemix-rtr.entrypoints=websecure"
      - "traefik.http.routers.deemix-rtr.rule=Host(`deemix.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.deemix-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.deemix-rtr.service=deemix-svc"
      - "traefik.http.services.deemix-svc.loadbalancer.server.port=6595"
      ####### HOMEPAGE #######
      - homepage.group=Media
      - homepage.name=Deemix
      - homepage.icon=deemix.svg
      - homepage.href=https://deemix.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Deezer Music Downloader
    profiles:
      - media
