services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_FILTER: "status=running"
      # DOZZLE_ENABLE_SHELL: "true" # Enable shell access also in docker-socket-proxy
      DOZZLE_REMOTE_HOST: ${DOCKER_REMOTE_HOSTS:-"tcp://docker-socket-proxy:2375"}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      start_period: 45s
      interval: 1m
      timeout: 5s
      retries: 3
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.dozzle-rtr.entrypoints: "websecure"
      traefik.http.routers.dozzle-rtr.rule: "Host(`dozzle.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.dozzle-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.dozzle-rtr.service: "dozzle-svc"
      traefik.http.services.dozzle-svc.loadbalancer.server.port: "8080"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Dozzle"
      homepage.icon: "dozzle.svg"
      homepage.href: "https://dozzle.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Realtime log viewer for docker containers"
      ####### GLANCE #######
      glance.name: "dozzle"
      glance.icon: "sh:dozzle"
      glance.url: "https://dozzle.$DOMAINNAME"
      glance.description: "Realtime log viewer for docker containers"