services:
  # NOTE: First, create `filebrowser` folder in appdata.
  # For custom.css: change Global Settings->branding path to "config"
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest # TODO: ghcr.io/
    user: "$PUID:$PGID"
    profiles:
      - core
    depends_on:
      - traefik
    restart: $BASE_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/filebrowser:/config
      - $DOCKERDIR/appdata/filebrowser:/database
      - $USERDIR:/srv/Home
      - $HARDDISKROOTDIR:/srv/Harddisk
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FB_NOAUTH: true # NOTE: If you change it, remove and re-create database.db
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.filebrowser-rtr.entrypoints: "websecure"
      traefik.http.routers.filebrowser-rtr.rule: "Host(`filebrowser.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.filebrowser-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.filebrowser-rtr.service: "filebrowser-svc"
      traefik.http.services.filebrowser-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.filebrowser.config.domain: "filebrowser.$DOMAINNAME"
      tinyauth.apps.filebrowser.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "FileBrowser"
      homepage.icon: "filebrowser.svg"
      homepage.href: "https://filebrowser.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Browser"
      ####### GLANCE #######
      glance.name: "FileBrowser"
      glance.icon: "sh:filebrowser"
      glance.url: "https://filebrowser.$DOMAINNAME"
      glance.description: "File Browser"
