services:
  filerun_db:
    container_name: filerun_db
    image: linuxserver/mariadb:latest
    restart: $PHOTO_RESTART_POLICY
    hostname: filerun_db
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/filerun_db/data:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_DATABASE: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_ROOT_PASSWORD: filerun
      # - FILE__MYSQL_PASSWORD=/run/secrets/mysql_password
      # - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_password

  filerun:
    image: filerun/filerun
    container_name: filerun
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # user: $PGID:$PUID
    user: 0:0
    volumes:
      - $DOCKERDIR/appdata/filerun/html:/var/www/html
      - $HARDDISKROOTDIR:/user-files:ro
    depends_on:
      - filerun_db
    links:
      - filerun_db:db
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.filerun-rtr.entrypoints: "websecure"
      traefik.http.routers.filerun-rtr.rule: "Host(`filerun.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.filerun-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.filerun-rtr.service: "filerun-svc"
      traefik.http.services.filerun-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.filerun.config.domain: "filerun.$DOMAINNAME"
      tinyauth.apps.filerun.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "Filerun"
      homepage.icon: "filerun.svg"
      homepage.href: "https://filerun.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Manager"
