x-deploy: &gpu-deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [compute,video,graphics,utility]

services:
  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    <<: *gpu-deploy
    shm_size: "1gb"
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TITLE=Firefox
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefox-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.firefox-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=3000"
    # devices:
    #   - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - desktop_apps
