services:
  firefox:
    container_name: firefox
    image: firefox:latest
    build:
      context: $DOCKERDIR/Dockerfiles/DesktopApps/Firefox
      dockerfile: $DOCKERDIR/Dockerfiles/DesktopApps/Firefox/Dockerfile
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    shm_size: "1gb" #optional
    devices: #optional
      - /dev/dri:/dev/dri
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/firefox:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # For watchtower
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefox-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.firefox-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=3000"
    profiles:
      - desktop_apps
