services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    restart: $OTHERS_RESTART_POLICY
    profiles:
      - reading
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/data
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FLATNOTES_AUTH_TYPE: none
      # - FLATNOTES_USERNAME="user"
      # - FLATNOTES_PASSWORD="changeMe!"
      FLATNOTES_SECRET_KEY: "change-stability-pushchair"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.flatnotes-rtr.entrypoints: "websecure"
      traefik.http.routers.flatnotes-rtr.rule: "Host(`flatnotes.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.flatnotes-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.flatnotes-rtr.service: "flatnotes-svc"
      traefik.http.services.flatnotes-svc.loadbalancer.server.port: "8080"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "Flatnotes"
      homepage.icon: "flatnotes.svg"
      homepage.href: "https://flatnotes.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "No Directory Markdown Viewer/Editor"