services:
  gimp:
    container_name: gimp
    image: lscr.io/linuxserver/gimp:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Gimp
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.gimp-rtr.entrypoints: "websecure"
      traefik.http.routers.gimp-rtr.rule: "Host(`gimp.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.gimp-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.gimp-rtr.service: "gimp-svc"
      traefik.http.services.gimp-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.gimp.config.domain: "gimp.$DOMAINNAME"
      tinyauth.apps.gimp.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Gimp"
      homepage.icon: "gimp.svg"
      homepage.href: "https://gimp.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Image Manipulation Program"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 1m
      timeout: 5s
      retries: 3
    profiles:
      - desktop_apps
