services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: $BASE_RESTART_POLICY
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/glance/config:/app/config
      - $CONFIGDIR/glance/assets:/app/assets
    environment:
      TZ: $TZ
      MY_SECRET_TOKEN: "glance_secret_token"
      DOMAINNAME: $DOMAINNAME
      CHANGEDETECTION_API_KEY: $CHANGEDETECTION_API_KEY
      TMDB_API_READ_ACCESS_TOKEN: $TMDB_API_READ_ACCESS_TOKEN
      TAILSCALE_API_KEY: $TAILSCALE_KEY
      JELLYFIN_URL: http://jellyfin:8096
      JELLYFIN_USER_ID: $JELLYFIN_USER_ID
      JELLYFIN_KEY: $JELLYFIN_API_KEY
      WG_EASY_URL: https://wireguard.$BASE_DOMAINNAME
      WG_EASY_USERNAME: ${WG_EASY_USERNAME:-DUMMY} # NOTE: Not needed for wg-easy-14
      WG_EASY_PASSWORD: ${WG_EASY_PASSWORD:-DUMMY} # NOTE: Not needed for wg-easy-14
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.glance-rtr.entrypoints: "websecure"
      traefik.http.routers.glance-rtr.rule: "Host(`glance.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.glance-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.glance-rtr.service: "glance-svc"
      traefik.http.services.glance-svc.loadbalancer.server.port: "8080"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "glance"
      homepage.icon: "glance.png"
      homepage.href: "https://glance.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A self-hosted dashboard that puts all your feeds in one place"
      ####### GLANCE #######
      glance.name: "glance"
      glance.icon: "sh:glance"
      glance.url: "https://glance.$DOMAINNAME"
      glance.description: "A self-hosted dashboard that puts all your feeds in one place"