services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: $BASE_RESTART_POLICY
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/glance/config:/app/config
      - $CONFIGDIR/glance/assets:/app/assets
    environment:
      TZ: $TZ
      MY_SECRET_TOKEN: "glance_secret_token"
      BASE_DOMAINNAME: $BASE_DOMAINNAME
      DOMAINNAME: $DOMAINNAME
      CHANGEDETECTION_API_KEY: $CHANGEDETECTION_API_KEY
      GITHUB_DASHBOARD_TOKEN: $GITHUB_DASHBOARD_TOKEN
      HEADSCALE_API_KEY: $HEADSCALE_API_KEY
      TMDB_API_READ_ACCESS_TOKEN: $TMDB_API_READ_ACCESS_TOKEN
      JELLYFIN_URL: $JELLYFIN_URL
      JELLYFIN_USER_ID: $JELLYFIN_USER_ID
      JELLYFIN_KEY: $JELLYFIN_API_KEY
      TRAKT_USERNAME: $TRAKT_USERNAME
      TRAKT_CLIENT_ID: $TRAKT_CLIENT_ID
      HASS_URL: $HASS_URL
      HASS_API_KEY: $HASS_API_KEY
      SYNCTHING_URL: $SYNCTHING_URL
      SYNCTHING_API_KEY: $SYNCTHING_API_KEY
      SYNCTHING_NOTES_FOLDER_ID: $SYNCTHING_NOTES_FOLDER_ID
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.glance-rtr.entrypoints: "websecure"
      traefik.http.routers.glance-rtr.rule: "Host(`glance.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.glance-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.glance-rtr.service: "glance-svc"
      traefik.http.services.glance-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.glance.config.domain: "glance.$DOMAINNAME"
      tinyauth.apps.glance.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "glance"
      homepage.icon: "glance.png"
      homepage.href: "https://glance.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A self-hosted dashboard that puts all your feeds in one place"
      ####### GLANCE #######
      glance.name: "glance"
      glance.icon: "sh:glance"
      glance.url: "https://glance.$DOMAINNAME"
      glance.description: "A self-hosted dashboard that puts all your feeds in one place"
