services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake:latest
    volumes:
      - $DATADIR/downloads:/data/downloads
      - $DOCKERDIR/appdata/handbrake/config:/config
      - $DOCKERDIR/appdata/handbrake/watch:/watch
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      UMASK: 002
      TZ: $TZ
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      AUTOMATED_CONVERSION_KEEP_SOURCE: 1
      VNC_PASSWORD: $HANDBRAKE_VNC_PASSWD
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.handbrake-rtr.entrypoints=websecure"
      - "traefik.http.routers.handbrake-rtr.rule=Host(`handbrake.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.handbrake-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.handbrake-rtr.service=handbrake-svc"
      - "traefik.http.services.handbrake-svc.loadbalancer.server.port=5800"
        ####### HOMEPAGE #######
      - homepage.group=Media
      - homepage.name=handbrake
      - homepage.icon=handbrake.svg
      - homepage.href=https://handbrake.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Converting Video Platform
    profiles:
      - media
