services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/healthchecks/config:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SITE_NAME: Healthchecks
      # - SITE_LOGO_URL=https://s3.ilkerflix.com/IS.jpeg
      SITE_ROOT: http://localhost:8000
      SUPERUSER_EMAIL: admin@$BASE_DOMAINNAME
      SUPERUSER_PASSWORD: admin
      APPRISE_ENABLED: "True"
      DEBUG: "False"
      ALLOWED_HOSTS: localhost,healthchecks.$DOMAINNAME
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.healthchecks-rtr.entrypoints: "websecure"
      traefik.http.routers.healthchecks-rtr.rule: "Host(`healthchecks.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.healthchecks-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.healthchecks-rtr.service: "healthchecks-svc"
      traefik.http.services.healthchecks-svc.loadbalancer.server.port: "8000"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Healthchecks"
      homepage.icon: "healthchecks.svg"
      homepage.href: "https://healthchecks.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Cron job and Background Task Monitoring"