services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: $BASE_RESTART_POLICY
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy
    volumes:
      - $CONFIGDIR/homepage:/app/config
      - $CONFIGDIR/homepage/icons:/app/public/icons
      - $DOCKERDIR/logs/homepage:/app/config/logs
      # - /mnt/d:/mnt/d  # NOTE: Need for Disk usage widget
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_MY_HOSTNAME: $MY_HOSTNAME
      HOMEPAGE_ALLOWED_HOSTS: homepage.$DOMAINNAME
      HOMEPAGE_VAR_BASE_DOMAINNAME: $BASE_DOMAINNAME
      HOMEPAGE_VAR_DOMAINNAME: $DOMAINNAME
      # HOMEPAGE_VAR_TAILSCALE_KEY: $TAILSCALE_KEY
      # HOMEPAGE_VAR_TAILSCALE_DEVICE_IP: $TAILSCALE_DEVICE_IP
      # HOMEPAGE_VAR_TAILSCALE_DEVICE_ID: $TAILSCALE_DEVICE_ID
      # HOMEPAGE_VAR_CALENDAR_GMAIL_ICAL_SECRET_ADDRESS: $CALENDAR_GMAIL_ICAL_SECRET_ADDRESS
      # HOMEPAGE_VAR_FINNHUB_API_KEY: $FINNHUB_API_KEY
      # HOMEPAGE_VAR_BESZEL_EMAIL: $BESZEL_EMAIL
      # HOMEPAGE_VAR_BESZEL_PASSWORD: $BESZEL_PASSWORD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homepage-rtr.entrypoints: "websecure"
      traefik.http.routers.homepage-rtr.rule: "Host(`homepage.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homepage-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homepage-rtr.service: "homepage-svc"
      traefik.http.services.homepage-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.homepage.config.domain: homepage.$DOMAINNAME
      tinyauth.apps.homepage.ip.bypass: $LOCAL_IPS
      ####### GLANCE #######
      glance.name: "homepage"
      glance.icon: "si:homepage"
      glance.url: "https://homepage.$DOMAINNAME"
      glance.description: "Alternative homepage"