services:
  home-assistant-db:
    image: postgres:16.4
    container_name: home-assistant-db
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
      - home-assistant
    environment:
      PGDATA: /pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - t3_proxy
    ports:
      - "127.0.0.1:5400:5432"
    expose:
      - "5432"
    volumes:
      - $DATADIR/home-assistant-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: $MAINTENANCE_RESTART_POLICY
    depends_on:
      home-assistant-db:
        condition: service_healthy
    profiles:
      - maintenance
      - home-assistant
    network_mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    environment:
      TZ: $TZ
    labels:
      ####### HOMEPAGE #######
      homepage.group: Maintenance
      homepage.name: home-assistant
      homepage.icon: home-assistant.png
      homepage.href: https://smarthome.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Home automation
      ####### GLANCE #######
      glance.name: home-assistant
      glance.icon: sh:home-assistant
      glance.url: https://smarthome.$DOMAINNAME
      glance.description: Home automation

  home-assistant-proxied:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant-proxied
    restart: $MAINTENANCE_RESTART_POLICY
    depends_on:
      home-assistant-db:
        condition: service_healthy
    profiles:
      - not-used
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    environment:
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.home-assistant-rtr.entrypoints: websecure
      traefik.http.routers.home-assistant-rtr.rule: Host(`smarthome.$DOMAINNAME`)
      ## Middlewares
      traefik.http.routers.home-assistant-rtr.middlewares: chain-tinyauth-relaxed@file
      ## HTTP Services
      traefik.http.routers.home-assistant-rtr.service: home-assistant-svc
      traefik.http.services.home-assistant-svc.loadbalancer.server.port: "8123"
      ####### TINYAUTH #######
      tinyauth.apps.home-assistant.config.domain: smarthome.$DOMAINNAME
      tinyauth.apps.home-assistant.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: Maintenance
      homepage.name: home-assistant
      homepage.icon: home-assistant.png
      homepage.href: https://smarthome.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Home automation
      ####### GLANCE #######
      glance.name: home-assistant
      glance.icon: sh:home-assistant
      glance.url: https://smarthome.$DOMAINNAME
      glance.description: Home automation