services:
  jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/jdownloader:/config:rw
      - $MEDIADIR/Downloads:/output:rw
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    #      VNC_PASSWORD: $JDOWN_VNC_PASSWD
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jdownloader-rtr.entrypoints=websecure"
      - "traefik.http.routers.jdownloader-rtr.rule=Host(`download.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jdownloader-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.jdownloader-rtr.service=jdownloader-svc"
      - "traefik.http.services.jdownloader-svc.loadbalancer.server.port=5800"
      ####### HOMEPAGE #######
      - homepage.group=Media
      - homepage.name=Jdownloader
      - homepage.icon=jdownloader.svg
      - homepage.href=https://jdownloader.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Download Management Tool
    profiles:
      - media
