services:
  jellysearch-meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: jellysearch-meilisearch
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: "1234"
    profiles:
      - media
