services:
  jellyfin-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable.2023-11-30.5ff058d
    container_name: jellyfin-vue
    restart: $MEDIA_RESTART_POLICY
    # depends_on:
    #   - jellyfin
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-vue-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-vue-rtr.rule=Host(`jellyfin_vue.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jellyfin-vue-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.jellyfin-vue-rtr.service=jellyfin-vue-svc"
      - "traefik.http.services.jellyfin-vue-svc.loadbalancer.server.port=80"
    profiles:
      - media
