services:
  # FIXME: middlewares-secure-headers doesn't work for `feishin`
  jellyfin:
    image: jellyfin/jellyfin:latest # TODO: ghcr.io
    container_name: jellyfin
    # cpus: "0.5"
    mem_reservation: "4096M"
    mem_limit: "4096M"
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    ports:
      - "8096:8096"
    security_opt:
      - no-new-privileges:true
    # user: $PGID:$PUID
    user: 0:0
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DOCKERDIR/appdata/jellyfin/cache:/cache
      - $DATADIR/jellyfin/metadata:/config/metadata
      - $DATADIR/downloads:/media/downloads:ro
      - $MEDIADIR:/media/local:ro
      - $ONEDRIVEDIR:/media/onedrive:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
    profiles:
      - media
