services:
  kavita:
    container_name: kavita
    image: kizaing/kavita:latest
    # image: ghcr.io/kareadita/kavita:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/kavita:/kavita/config
      - $MEDIADIR/Books:/book
      # - ./manga:/manga
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kavita-rtr.entrypoints=websecure"
      - "traefik.http.routers.kavita-rtr.rule=Host(`kavita.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.kavita-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.kavita-rtr.service=kavita-svc"
      - "traefik.http.services.kavita-svc.loadbalancer.server.port=5000"
      ####### HOMEPAGE #######
      - homepage.group=Reading
      - homepage.name=Kavita
      - homepage.icon=kavita.svg
      - homepage.href=https://kavita.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Fast, feature rich, cross platform reading server
    profiles:
      - reading
