services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    restart: $MEDIA_RESTART_POLICY
    profiles:
      - media
      - youtube
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $MEDIADIR/Youtube:/downloads
      #      - /path/to/cookies:/cookies
    environment:
      OUTPUT_TEMPLATE: '%(title)s [%(id)s].%(ext)s'
      YTDL_OPTIONS: '{"writethumbnail": true, "writeinfojson": true}' # "writeinfojson": true,
      # - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.metube-rtr.entrypoints=websecure"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.metube-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"
      ####### HOMEPAGE #######
      - homepage.group=Media
      - homepage.name=metube
      - homepage.icon=metube.svg
      - homepage.href=https://metube.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Self-hosted YouTube downloader