services:
  obsidian:
    container_name: obsidian
    image: lscr.io/linuxserver/obsidian:latest
    restart: $OTHERS_RESTART_POLICY
    shm_size: "1gb"
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/vaults
      # - /path/to/config:/config
    depends_on:
      couchdb:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TITLE=Obsidian
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.obsidian-rtr.entrypoints=websecure"
      - "traefik.http.routers.obsidian-rtr.rule=Host(`obsidian.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.obsidian-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.obsidian-rtr.service=obsidian-svc"
      - "traefik.http.services.obsidian-svc.loadbalancer.server.port=3000"
    # devices:
    #   - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - reading
