services:
  # https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server.md#setup-couchdb-to-your-server
  obsidian-couchdb:
    container_name: obsidian-couchdb
    image: couchdb:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/couchdb:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.couchdb-rtr.entrypoints=websecure"
      - "traefik.http.routers.couchdb-rtr.rule=Host(`couchdb.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.couchdb-rtr.middlewares=obsidiancors" # NOTE: chain-no-auth and chain-authelia not working
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost,https://couchdb.$DOMAINNAME"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"
      ## HTTP Services
      - "traefik.http.routers.couchdb-rtr.service=couchdb-svc"
      - "traefik.http.services.couchdb-svc.loadbalancer.server.port=5984"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -u admin:admin -s http://localhost:5984/_up | grep -Eo '\"status\":\"ok\"' || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - reading

  obsidian:
    container_name: obsidian
    image: lscr.io/linuxserver/obsidian:latest
    restart: $OTHERS_RESTART_POLICY
    shm_size: "1gb"
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/vaults
      # - /path/to/config:/config
    depends_on:
      obsidian-couchdb:
        condition: service_healthy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TITLE=Obsidian
    # devices:
    #   - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - reading
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.obsidian-rtr.entrypoints=websecure"
      - "traefik.http.routers.obsidian-rtr.rule=Host(`obsidian.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.obsidian-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.obsidian-rtr.service=obsidian-svc"
      - "traefik.http.services.obsidian-svc.loadbalancer.server.port=3000"
      ####### HOMEPAGE #######
      - homepage.group=Reading
      - homepage.name=Obsidian
      - homepage.icon=obsidian.svg
      - homepage.href=https://obsidian.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Note Taking with Markdown