services:
  # NOTE: Recent file location: /config/.local/share/okular/docdata/
  okular:
    container_name: okular
    image: okular:latest
    build:
      context: $DOCKERDIR/Dockerfiles/DesktopApps/Okular
      dockerfile: $DOCKERDIR/Dockerfiles/DesktopApps/Okular/Dockerfile
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/okular:/config
      - $MEDIADIR/Books:/books
      - $HARDDISKROOTDIR/School/Thesis/Papers:/thesis
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.okular-rtr.entrypoints: "websecure"
      traefik.http.routers.okular-rtr.rule: "Host(`okular.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.okular-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.okular-rtr.service: "okular-svc"
      traefik.http.services.okular-svc.loadbalancer.server.port: "3000"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Okular"
      homepage.icon: "/icons/okular.png"
      homepage.href: "https://okular.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Pdf Viewing"
    profiles:
      - desktop_apps
