services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.omni-tools-rtr.entrypoints: websecure
      traefik.http.routers.omni-tools-rtr.rule: Host(`omni-tools.$DOMAINNAME`)
      ## Middlewares
      traefik.http.routers.omni-tools-rtr.middlewares: chain-tinyauth@file
      ## HTTP Services
      traefik.http.routers.omni-tools-rtr.service: omni-tools-svc
      traefik.http.services.omni-tools-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: Maintenance
      homepage.name: omni-tools
      homepage.icon: omni-tools.png
      homepage.href: https://omni-tools.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Web-based tools for everyday tasks
      ####### GLANCE #######
      glance.name: omni-tools
      glance.icon: sh:omni-tools
      glance.url: https://omni-tools.$DOMAINNAME
      glance.description: Web-based tools for everyday tasks