services:
  # searxng:
  #   container_name: searxng
  #   image: searxng/searxng:latest
  #   restart: $ML_RESTART_POLICY
  #   networks:
  #     - t3_proxy
  #   # ports:
  #   #   - "8080:8080"
  #   volumes:
  #     - $DOCKERDIR/appdata/searxng:/etc/searxng
  #   profiles:
  #     - ml

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    restart: $ML_RESTART_POLICY
    # depends_on:
    #   - searxng
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/open-webui:/app/backend/data
    environment:
      # WEBUI_AUTH: false
      ENABLE_OLLAMA_API: false
      USE_OLLAMA_DOCKER: false
      ENABLE_IMAGE_GENERATION: true
      IMAGE_SIZE: 1024x1024
      # - ENABLE_RAG_WEB_SEARCH=True
      # - RAG_WEB_SEARCH_ENGINE="searxng"
      # - RAG_WEB_SEARCH_RESULT_COUNT=3
      # - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      # - SEARXNG_QUERY_URL="http://searxng:8080/search?q=<query>"
      #### OPENAI API ####
      # - OPENAI_API_BASE_URL=$CUSTOM_OPENAI_BASE_URL
      # - OPENAI_API_KEY=DUMMY
      OPENAI_API_BASE_URLS: https://api.openai.com/v1;$OPENROUTER_API_BASE_URL
      OPENAI_API_KEYS: $OPENAI_API_KEY;$OPENROUTER_API_KEY
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.open-webui-rtr.entrypoints: "websecure"
      traefik.http.routers.open-webui-rtr.rule: "Host(`chat.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.open-webui-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.open-webui-rtr.service: "open-webui-svc"
      traefik.http.services.open-webui-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.open-webui.config.domain: chat.$DOMAINNAME
      tinyauth.apps.open-webui.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: "ML"
      homepage.name: "Open WebUI"
      homepage.icon: "open-webui-light.webp"
      homepage.href: "https://chat.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Selfhosted Chatgpt like App"
    profiles:
      - ml

  # NOTE: Change ENABLE_OAUTH_SIGNUP: true for the first run
  open-webui-betus:
    container_name: open-webui-betus
    image: ghcr.io/open-webui/open-webui:latest
    restart: $ML_RESTART_POLICY
    # depends_on:
    #   - searxng
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/open-webui-betus:/app/backend/data
    environment:
      # WEBUI_AUTH: false
      ENABLE_SIGNUP: false
      OPENAI_API_KEY: $OPENAI_API_KEY
      WEBUI_NAME: BetusGPT
      ## OIDC
      ENABLE_LOGIN_FORM: true
      ENABLE_OAUTH_SIGNUP: false
      OAUTH_CLIENT_ID: $OPEN_WEB_UI_BETUS_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OPEN_WEB_UI_BETUS_CLIENT_SECRET
      OPENID_PROVIDER_URL: https://pocketid.$BASE_DOMAINNAME/.well-known/openid-configuration
      OAUTH_PROVIDER_NAME: Pocketid
      OAUTH_SCOPES: openid email profile
      OPENID_REDIRECT_URI: https://betuschat.$DOMAINNAME/oauth/oidc/callback
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.open-webui-betus-rtr.entrypoints: "websecure"
      traefik.http.routers.open-webui-betus-rtr.rule: "Host(`betuschat.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.open-webui-betus-rtr.middlewares: "chain-no-auth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.open-webui-betus-rtr.service: "open-webui-betus-svc"
      traefik.http.services.open-webui-betus-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.open-webui-betus.config.domain: betuschat.$DOMAINNAME
      tinyauth.apps.open-webui-betus.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: "ML"
      homepage.name: "Open WebUI"
      homepage.icon: "open-webui-light.webp"
      homepage.href: "https://betuschat.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Selfhosted Chatgpt like App for my Betus"
    profiles:
      # - ml
      - not-used
