services:
  # FIXME: docker-socket-proxy NOT WORKING !
  # TODO: Authelia integration
  # https://www.authelia.com/integration/openid-connect/portainer/
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest # TODO: ghcr.io/
    depends_on:
      - traefik
    restart: $BASE_RESTART_POLICY
    profiles:
      - maintenance
    command: -H tcp://docker-socket-proxy:2375 # Use this instead, if you have Socket Proxy enabled.
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      ####### HOMEPAGE #######
      - homepage.group=Maintenance
      - homepage.name=Portainer
      - homepage.icon=portainer.svg
      - homepage.href=https://portainer.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Container Management
      # - homepage.widget.type=portainer
      # - homepage.widget.url=http://portainer:9000
      # - homepage.widget.env=1
      # - homepage.widget.key=DUMMY # https://docs.portainer.io/api/access