services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - transmission
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - $MEDIADIR/Downloads:/data/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.prowlarr-rtr.entrypoints: "websecure"
      traefik.http.routers.prowlarr-rtr.rule: "Host(`prowlarr.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.prowlarr-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.prowlarr-rtr.service: "prowlarr-svc"
      traefik.http.services.prowlarr-svc.loadbalancer.server.port: "9696"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Prowlarr"
      homepage.icon: "prowlarr.svg"
      homepage.href: "https://prowlarr.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Indexer Manager"
    profiles:
      - media
      - arr
