services:
  # Default user-pass: admin / adminadmin
  qbittorrent-lscr:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-lscr
    restart: $MEDIA_RESTART_POLICY
    # network_mode: "service:gluetun"
    # depends_on:
    #   - gluetun
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $MEDIADIR/Downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      WEBUI_PORT: 8080
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.qbittorrent-lscr-rtr.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent-lscr-rtr.rule=Host(`qtorrent.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-lscr-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-lscr-rtr.service=qbittorrent-lscr-svc"
      - "traefik.http.services.qbittorrent-lscr-svc.loadbalancer.server.port=8080"
      # - traefik.http.services.qbittorrent-lscr-svc.loadbalancer.passhostheader=false # Not needed
    profiles:
      - media
