# NOTE: To rebuild: NOT WORKING
# https://digitalgarden.$DOMAINNAME/rebuild/{REBUILD_WEBHOOK_SECRET}
# Add to crontab: 0 1 * * * docker exec quartz /usr/src/app/scripts/build-quartz.sh
services:
  quartz:
    container_name: quartz
    # image: shommey/dockerized-quartz
    image: ilkersigirci/dockerized-quartz:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/vault:ro
      - $CONFIGDIR/quartz/repo:/usr/src/app/quartz # Optional: Mount existing Quartz repo
      - $CONFIGDIR/quartz/quartz.config.ts:/usr/src/app/quartz/quartz.config.ts:ro
      - $CONFIGDIR/quartz/quartz.layout.ts:/usr/src/app/quartz/quartz.layout.ts:ro
    environment:
      AUTO_REBUILD: false
      REBUILD_WEBHOOK_SECRET: $QUARTZ_REBUILD_WEBHOOK_SECRET
      # BUILD_UPDATE_DELAY: 300
      # NOTIFY_TARGET: $TELEGRAM_APPRISE_FORMAT
      # GIT_REPO: "https://github.com/yourusername/your-quartz-site.git" # Use your custom Quartz repo or leave blank for the default Quartz repo
      # GIT_BRANCH: "v4" # Optional: specify a branch to checkout
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.quartz-rtr.entrypoints=websecure"
      - "traefik.http.routers.quartz-rtr.rule=Host(`digitalgarden.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.quartz-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.quartz-rtr.service=quartz-svc"
      - "traefik.http.services.quartz-svc.loadbalancer.server.port=80"
      ####### HOMEPAGE #######
      - homepage.group=Reading
      - homepage.name=Quartz
      - homepage.icon=obsidian.svg
      - homepage.href=https://digitalgarden.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Static-site generator that transforms Markdown content into fully functional websites 
    profiles:
      - reading
