services:
  # Set url_base in the settings if using PathPrefix
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/readarr:/config
      # - /path/to/books:/books #optional
      - $MEDIADIR/Downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # UMASK: 002
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.readarr-rtr.entrypoints: "websecure"
      traefik.http.routers.readarr-rtr.rule: "Host(`readarr.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.readarr-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.readarr-rtr.service: "readarr-svc"
      traefik.http.services.readarr-svc.loadbalancer.server.port: "8787"
    profiles:
      - media
      - arr
