services:
  # adb connect localhost:5555
  # scrcpy -s localhost:5555
  redroid:
    container_name: redroid
    image: redroid/redroid:13.0.0-latest
    restart: unless-stopped
    profiles:
      - android
    privileged: true
    networks:
      - t3_proxy
    ports:
      - 5555:5555
    # security_opt:
    #   - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/redroid/data:/data
    # environment:
    #   - PUID=$PUID
    #   - PGID=$PGID
    #   - TZ=$TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.redroid-rtr.entrypoints: "websecure"
      traefik.http.routers.redroid-rtr.rule: "Host(`redroid.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.redroid-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.redroid-rtr.service: "redroid-svc"
      traefik.http.services.redroid-svc.loadbalancer.server.port: "5555"
      ####### TINYAUTH #######
      tinyauth.apps.redroid.config.domain: "redroid.$DOMAINNAME"
      tinyauth.apps.redroid.ip.bypass: "$LOCAL_IPS"
