# Use with: drun rustic <COMMAND>
# Commands:
#  - init: Initialize a new remote repository
#      init -r /repos/TestRepo
#  - backup: Backup the local repository to the remote repository
#  - restore: Restore the remote repository to a local directory
#       restore -r /repos/TestRepo restore latest /restores/RestoreTest
#  - snapshots: List all snapshots in the remote repository
services:
  rustic:
    container_name: rustic
    hostname: ${MY_HOSTNAME}
    image: ghcr.io/rustic-rs/rustic:latest
    # user: $PUID:$PGID
    # build:
    #   context: $DOCKERDIR/Dockerfiles/Rustic
    #   args:
    #     RUSTIC_VERSION: v0.9.5
    # restart: $MAINTENANCE_RESTART_POLICY
    restart: "no"
    # command: init
    profiles:
      - maintenance
      - backup
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/rustic/rustic.toml:/etc/rustic/rustic.toml:ro
      - $DOCKERDIR/logs/rustic:/logs:rw
      # - $CONFIGDIR/rclone:/root/.config/rclone:rw
      - $BACKUPDIR/RUSTIC/Repos/TestRepo:/repos/TestRepo:rw
      - $BACKUPDIR/RUSTIC/BackupTest:/backups/BackupTest:ro
      - $BACKUPDIR/RUSTIC/Restores:/restores:rw
      # - $CONFIGDIR:/backups/docker_configs:ro
      # - $NOTESDIR/Markdown:/backups/Markdown:ro
      # - $DATADIR/vaultwarden:/vaultwarden_backup:ro
    environment:
      - TZ=$TZ
      - RUSTIC_PASSWORD=/run/secrets/rustic_password
      # - RCLONE_CONFIG=/root/.config/rclone/rclone.conf
    secrets:
      - rustic_password