x-deploy: &gpu-deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, utility]
            # capabilities: [compute, utility]

services:
  sd-next:
    container_name: sd-next
    image: vladmandic/sdnext-cuda:latest
    restart: $ML_RESTART_POLICY
    <<: *gpu-deploy
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/sd-next:/mnt/data:rw
      - $MLMODELSDIR/sdnext:/mnt/models:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sdnext-rtr.entrypoints=websecure"
      - "traefik.http.routers.sdnext-rtr.rule=Host(`sdnext.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.sdnext-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.sdnext-rtr.service=sdnext-svc"
      - "traefik.http.services.sdnext-svc.loadbalancer.server.port=7860"
    profiles:
      - ml
