services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: $ML_RESTART_POLICY
    depends_on:
      - searxng-redis
    profiles:
      - ml
      - searxng
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIGDIR/searxng:/etc/searxng:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      SEARXNG_BASE_URL: https://searxng.$DOMAINNAME
      UWSGI_WORKERS: 4
      UWSGI_THREADS: 4
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.searxng-rtr.entrypoints: "websecure"
      traefik.http.routers.searxng-rtr.rule: "Host(`searxng.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.searxng-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.searxng-rtr.service: "searxng-svc"
      traefik.http.services.searxng-svc.loadbalancer.server.port: "8080"
      ####### HOMEPAGE #######
      homepage.group: "ML"
      homepage.name: "searxng"
      homepage.icon: "searxng.png"
      homepage.href: "https://searxng.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Free internet metasearch engine"
      ####### GLANCE #######
      glance.name: "searxng"
      glance.icon: "sh:searxng"
      glance.url: "https://searxng.$DOMAINNAME"
      glance.description: "Free internet metasearch engine"

  searxng-redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-redis
    command: valkey-server --save 30 1 --loglevel warning
    restart: $ML_RESTART_POLICY
    profiles:
      - ml
      - searxng
    networks:
      - t3_proxy
    expose:
      - "6379"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/searxng-redis:/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"