# NOTE: env variables: https://silverbullet.md/Install/Configuration
services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet
    restart: $OTHERS_RESTART_POLICY
    profiles:
      - reading
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/space
    environment:
      PUID: $PUID
      PGID: $PGID
      SB_HOSTNAME: 0.0.0.0
      SB_PORT: 3000
      SB_FOLDER: /space
      SB_INDEX_PAGE: index
      # SB_READ_ONLY: true
      # SB_USER: admin:admin
      # SB_LOG_PUSH: 1
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.silverbullet-rtr.entrypoints: "websecure"
      traefik.http.routers.silverbullet-rtr.rule: "Host(`notes.$DOMAINNAME`)"
      ## Middlewares
      # traefik.http.routers.silverbullet-rtr.middlewares: chain-silverbullet-no-auth@file
      traefik.http.routers.silverbullet-rtr.middlewares: "chain-silverbullet-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.silverbullet-rtr.service: "silverbullet-svc"
      traefik.http.services.silverbullet-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.silverbullet.config.domain: "notes.$DOMAINNAME"
      tinyauth.apps.silverbullet.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "silverbullet"
      homepage.icon: "silverbullet.png"
      homepage.href: "https://notes.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
      ####### GLANCE #######
      glance.name: "silverbullet"
      glance.icon: "sh:silverbullet"
      glance.url: "https://notes.$DOMAINNAME"
      glance.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
