# NOTE: env variables: https://silverbullet.md/Install/Configuration
services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet
    restart: $OTHERS_RESTART_POLICY
    profiles:
      - reading
    networks:
      - t3_proxy
    ports:
      - "1001:3000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/space
    environment:
      PUID: $PUID
      PGID: $PGID
      SB_HOSTNAME: 0.0.0.0
      SB_PORT: 3000
      SB_FOLDER: /space
      SB_INDEX_PAGE: index
      # SB_READ_ONLY: true
      # SB_USER: admin:admin
      # SB_LOG_PUSH: 1
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.silverbullet-rtr.entrypoints: websecure
      traefik.http.routers.silverbullet-rtr.rule: Host(`silverbullet.$DOMAINNAME`)
      ## Middlewares
      # traefik.http.routers.silverbullet-rtr.middlewares: chain-silverbullet@file
      traefik.http.routers.silverbullet-rtr.middlewares: chain-silverbullet-tinyauth@file
      ## HTTP Services
      traefik.http.routers.silverbullet-rtr.service: silverbullet-svc
      traefik.http.services.silverbullet-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.silverbullet.config.domain: silverbullet.$DOMAINNAME
      tinyauth.apps.silverbullet.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: Reading
      homepage.name: silverbullet
      homepage.icon: silverbullet.png
      homepage.href: https://silverbullet.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Offline first web based Markdown editor, turbo charged with the scripting power of Lua 
      ####### GLANCE #######
      glance.name: silverbullet
      glance.icon: sh:silverbullet
      glance.url: https://silverbullet.$DOMAINNAME
      glance.description: Offline first web based Markdown editor, turbo charged with the scripting power of Lua

  silverbullet-test:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet-test
    restart: $OTHERS_RESTART_POLICY
    profiles:
      - reading
    networks:
      - t3_proxy
    ports:
      - "3333:3000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/silverbullet-test:/space
    environment:
      PUID: $PUID
      PGID: $PGID
      SB_HOSTNAME: 0.0.0.0
      SB_PORT: 3000
      SB_FOLDER: /space
      SB_INDEX_PAGE: index
      # SB_READ_ONLY: true
      # SB_USER: admin:admin
      # SB_LOG_PUSH: 1
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.silverbullet-test-rtr.entrypoints: websecure
      traefik.http.routers.silverbullet-test-rtr.rule: Host(`silverbullet-test.$DOMAINNAME`)
      ## Middlewares
      # traefik.http.routers.silverbullet-test-rtr.middlewares: chain-silverbullet@file
      traefik.http.routers.silverbullet-test-rtr.middlewares: chain-silverbullet-tinyauth@file
      ## HTTP Services
      traefik.http.routers.silverbullet-test-rtr.service: silverbullet-test-svc
      traefik.http.services.silverbullet-test-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.silverbullet-test.config.domain: silverbullet-test.$DOMAINNAME
      tinyauth.apps.silverbullet-test.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: Reading
      homepage.name: silverbullet-test
      homepage.icon: silverbullet.png
      homepage.href: https://silverbullet-test.$DOMAINNAME
      homepage.target: _blank
      homepage.description: Offline first web based Markdown editor, turbo charged with the scripting power of Lua 
      ####### GLANCE #######
      glance.name: silverbullet-test
      glance.icon: sh:silverbullet
      glance.url: https://silverbullet-test.$DOMAINNAME
      glance.description: Offline first web based Markdown editor, turbo charged with the scripting power of Lua