# NOTE: Disable Local, Global Announce, Relays and NATS in the Syncthing GUI
# NOTE: 22000:22000/tcp port is probably needed for other devices to see this device.
#  `remoteserver` needs this but somehow, homeserver does not. TEST IT
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    ports:
    #   - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/syncthing:/config
      - $NOTESDIR/Markdown:/notes
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.syncthing-rtr.entrypoints: "websecure"
      traefik.http.routers.syncthing-rtr.rule: "Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.syncthing-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.syncthing-rtr.service: "syncthing-svc"
      traefik.http.services.syncthing-svc.loadbalancer.server.port: "8384"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Syncthing"
      homepage.icon: "syncthing.svg"
      homepage.href: "https://syncthing.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Synchronization"
    profiles:
      - maintenance
