# NOTE: 22000:22000/tcp port is probably needed for other devices to see this device.
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    ports:
    #   - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/syncthing:/config
      - $NOTESDIR/Markdown:/notes
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.syncthing-rtr.entrypoints: "websecure"
      traefik.http.routers.syncthing-rtr.rule: "Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.syncthing-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.syncthing-rtr.service: "syncthing-svc"
      traefik.http.services.syncthing-svc.loadbalancer.server.port: "8384"
      ####### TINYAUTH #######
      tinyauth.apps.syncthing.config.domain: syncthing.$DOMAINNAME
      tinyauth.apps.syncthing.ip.bypass: $LOCAL_IPS
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Syncthing"
      homepage.icon: "syncthing.svg"
      homepage.href: "https://syncthing.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Synchronization"
      homepage.widget.type: "customapi"
      homepage.widget.url: "http://syncthing:8384/rest/svc/report"
      homepage.widget.headers.X-API-Key: $SYNCTHING_API_KEY
      homepage.widget.mappings.0.field: "numDevices"
      homepage.widget.mappings.0.label: "Devices"
      homepage.widget.mappings.0.format: "number"
      homepage.widget.mappings.1.field: "numFolders"
      homepage.widget.mappings.1.label: "Folders"
      homepage.widget.mappings.1.format: "number"
      homepage.widget.mappings.2.field: "totFiles"
      homepage.widget.mappings.2.label: "Files"
      homepage.widget.mappings.2.format: "number"
      homepage.widget.mappings.3.field: "totMiB"
      homepage.widget.mappings.3.label: "MB"
      homepage.widget.mappings.3.format: "number"
      ####### GLANCE #######
      glance.name: "syncthing"
      glance.icon: "sh:syncthing"
      glance.url: "https://syncthing.$DOMAINNAME"
      glance.description: "File Synchronization"
    profiles:
      - maintenance
