# Create user: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 user create --interactive
# Create SECRET: openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
# Create TOTP: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 totp generate --interactive
services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: $BASE_RESTART_POLICY
    profiles:
      - core
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      APP_TITLE: Single Sign-On
      APP_URL: https://tinyauth.$DOMAINNAME
      SECRET: $TINYAUTH_SECRET
      COOKIE_SECURE: "true"
      DISABLE_CONTINUE: "true"
      # LOG_LEVEL: "5"
      # USERS: $TINYAUTH_USERS
      USERS_FILE: users_file
      LOGIN_MAX_RETRIES: 5
      ## OIDC CLIENT CONFIGURATION
      GENERIC_NAME: PocketID
      GENERIC_CLIENT_ID: $TINYAUTH_GENERIC_CLIENT_ID
      GENERIC_CLIENT_SECRET: $TINYAUTH_GENERIC_CLIENT_SECRET
      GENERIC_AUTH_URL: https://pocketid.$BASE_DOMAINNAME/authorize
      GENERIC_TOKEN_URL: https://pocketid.$BASE_DOMAINNAME/api/oidc/token
      GENERIC_USER_URL: https://pocketid.$BASE_DOMAINNAME/api/oidc/userinfo
      GENERIC_SCOPES: openid email profile groups
      GENERIC_SKIP_SSL: "true"
      # OAUTH_AUTO_REDIRECT: generic # To automatically redirected to Pocket ID
      # OAUTH_WHITELIST: $POCKETID_WHITELIST_USERS
    volumes:
      - $SECRETSDIR/tinyauth_users:/tinyauth/users_file
    labels:
      komodo.skip: # Prevents from stopping with StopAllContainers on Komodo
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.tinyauth-rtr.entrypoints: "websecure"
      traefik.http.routers.tinyauth-rtr.rule: "Host(`tinyauth.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.tinyauth-rtr.middlewares: "chain-no-auth@file"
      ## Forward Auth - Commented out because it is handled inside treafik middleware chain file
      # - "traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "tinyauth"
      homepage.icon: "tinyauth.png"
      homepage.href: "https://tinyauth.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "The simplest way to protect your apps with a login screen"
      ####### GLANCE #######
      glance.name: "tinyauth"
      glance.icon: "sh:tinyauth"
      glance.url: "https://tinyauth.$DOMAINNAME"
      glance.description: "The simplest way to protect your apps with a login screen"