services:
  # NOTE: Revisit this when uptime-kuma v2 is released officially
  autokuma:
    image: ghcr.io/bigboot/autokuma:uptime-kuma-v2-master
    container_name: autokuma
    restart: $MAINTENANCE_RESTART_POLICY
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/autokuma:/data
    environment:
      AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
      AUTOKUMA__DOCKER__HOSTS: tcp://docker-socket-proxy:2375
      AUTOKUMA__DOCKER__LABEL_PREFIX: traefik
      AUTOKUMA__DOCKER__SOURCE: Containers
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.autokuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.autokuma-rtr.rule=Host(`autokuma.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.autokuma-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.autokuma-rtr.service=autokuma-svc"
      - "traefik.http.services.autokuma-svc.loadbalancer.server.port=3001"
    profiles:
      # - monitoring
      - not-used
      
  # Add tcp docker host: tcp://docker-socket-proxy:2375 in the UI
  # After user creation, disable auth: Settings -> Security -> Disable Auth
  uptime-kuma:
    image: louislam/uptime-kuma:beta
    container_name: uptime-kuma
    restart: $MAINTENANCE_RESTART_POLICY
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/uptime-kuma:/app/data
    environment:
      PUID: $PUID
      PGID: $PGID
      UPTIME_KUMA_PORT: 3001
      DATA_DIR: /app/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.uptime-kuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma-rtr.rule=Host(`uptimekuma.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.uptime-kuma-rtr.middlewares=chain-tinyauth@file"
      ## HTTP Services
      - "traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc"
      - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001"
      ####### HOMEPAGE #######
      - homepage.group=Monitoring
      - homepage.name=Uptimekuma
      - homepage.icon=uptime-kuma.svg
      - homepage.href=https://uptimekuma.$DOMAINNAME
      - homepage.target=_blank
      - homepage.description=Healthcheck for Http Apps
      # - homepage.widget.type=uptimekuma
      # - homepage.widget.url=http://uptime-kuma:3001
      # - homepage.widget.slug=statuspageslug
    profiles:
      - monitoring
