services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest # TODO: ghcr.io/
    profiles:
      - core
    depends_on:
      - traefik
    restart: $BASE_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATADIR/vaultwarden:/data/
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vaultwarden.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=80"
