# NOTE: argod2id token generation (don't forget to add extra $ in the password)
# docker exec -it vaultwarden /vaultwarden hash
services:
  vaultwarden:
    container_name: vaultwarden
    image: ghcr.io/dani-garcia/vaultwarden:latest
    profiles:
      - core
    depends_on:
      - traefik
    restart: $BASE_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATADIR/vaultwarden:/data/
    environment:
      ADMIN_TOKEN: $VAULTWARDEN_ADMIN_TOKEN
      DATA_FOLDER: data
      DOMAIN: https://vaultwarden.$DOMAINNAME
      TRASH_AUTO_DELETE_DAYS: 30
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: false
      SIGNUPS_DOMAINS_WHITELIST: $BASE_DOMAINNAME
      EMAIL_CHANGE_ALLOWED: false
      REQUIRE_DEVICE_EMAIL: false
      LOG_LEVEL: info
      SMTP_DEBUG: false
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.vaultwarden-rtr.entrypoints: "websecure"
      traefik.http.routers.vaultwarden-rtr.rule: "Host(`vaultwarden.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.vaultwarden-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.vaultwarden-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.vaultwarden-rtr.service: "vaultwarden-svc"
      traefik.http.services.vaultwarden-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.vaultwarden.config.domain: "vaultwarden.$DOMAINNAME"
      tinyauth.apps.vaultwarden.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "Vaultwarden"
      homepage.icon: "vaultwarden.svg"
      homepage.href: "https://vaultwarden.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Password Manager"
