services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest # TODO: ghcr.io/
    profiles:
      - core
    depends_on:
      - traefik
    restart: $BASE_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATADIR/vaultwarden:/data/
    labels:
      tinyauth.ip.bypass: $LOCAL_IPS
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.vaultwarden-rtr.entrypoints: "websecure"
      traefik.http.routers.vaultwarden-rtr.rule: "Host(`vaultwarden.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.jellyseerr-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.vaultwarden-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.vaultwarden-rtr.service: "vaultwarden-svc"
      traefik.http.services.vaultwarden-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "Vaultwarden"
      homepage.icon: "vaultwarden.svg"
      homepage.href: "https://vaultwarden.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Password Manager"