services:
  volglass:
    image: volglass:latest
    container_name: volglass
    build:
      # context: $GITHUBREPOSDIR/volglass
      # dockerfile: $GITHUBREPOSDIR/volglass/Dockerfile
      context: $DOCKERDIR/compose/notes
      dockerfile: $DOCKERDIR/compose/notes/Dockerfile_volglass
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $NOTESDIR/Markdown:/app/posts:ro
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # - DOCKER_MODS=linuxserver/mods:universal-git
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.volglass-rtr.entrypoints: "websecure"
      traefik.http.routers.volglass-rtr.rule: "Host(`volglass.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.volglass-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.volglass-rtr.service: "volglass-svc"
      traefik.http.services.volglass-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.volglass.config.domain: "volglass.$DOMAINNAME"
      tinyauth.apps.volglass.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "Volglass"
      homepage.icon: "volglass.svg"
      homepage.href: "https://volglass.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Publishing Your Digital Garden"
    profiles:
      - reading
