FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbookworm@sha256:c6129530811450448ab760064b27e111fb3351fc3222af652f605a48eb518ed7

RUN \
    echo "**** install packages ****" && \
        # Update and install extra packages.
        apt-get update && \
        apt-get install -y --no-install-recommends \
            # Packages needed to download and extract obsidian.
            curl \
            libgtk-3-0 \
            libnotify4 \
            libatspi2.0-0 \
            libsecret-1-0 \
            libnss3 && \
    echo "**** cleanup ****" && \
        apt-get autoclean && \
        rm -rf \
        /var/lib/apt/lists/* \
        /var/tmp/* \
        /tmp/*


ARG OBSIDIAN_VERSION=1.1.16

RUN \
    echo "**** Download Obsidian ****" && \
    curl -L \
    https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/Obsidian-${OBSIDIAN_VERSION}.AppImage \
    -o obsidian.AppImage

RUN \
    echo "**** Extract Obsidian ****" && \
    chmod +x /obsidian.AppImage && \
    # sed '0,/AI\x02/{s|AI\x02|\x00\x00\x00|}' -i /obsidian.AppImage && \
    # dd if=/dev/zero bs=1 count=3 seek=8 conv=notrunc of=/obsidian.AppImage && \
    /obsidian.AppImage --appimage-extract
    # /obsidian.AppImage --appimage-extract-and-run
    # chown -R root:root /squashfs-root


# RUN dl_url=$( curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest  \
#     | grep "browser_download_url.*AppImage" | tail -n 1 | cut -d '"' -f 4 ) && \
#     curl --location --output obsidian.AppImage "$dl_url" && \
#     chmod +x /obsidian.AppImage && \
#     /obsidian.AppImage --appimage-extract

ENV \
    CUSTOM_PORT="3000" \
    CUSTOM_HTTPS_PORT="3001" \
    TITLE="Obsidian v$OBSIDIAN_VERSION" \
    FM_HOME="/vaults"
    # FM_HOME="/config"

# add local files
COPY /root /

EXPOSE 3000
VOLUME ["/config","/vaults"]
