tls:
  enabled: false

auth:
  enabled: false

proxy:
  default_role: admin

## NOTE: For tinyauth proxy auth
# proxy:
#   default_role: viewer
#   header_map:
#     user: Remote-User
#     role: Remote-Groups
#     role_map:
#       admin:
#         - family

logger:
  default: info
  logs:
    frigate.event: info

mqtt:
  enabled: true
  host: "{FRIGATE_MOSQUITTO_HOST}"

# Hardware acceleration for Intel Xe Graphics
ffmpeg:
  # hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: true

# OpenVINO detector for Intel GPU
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: false

go2rtc:
  streams:
    raylikapi_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.124:{FRIGATE_RTSP_PORT}/1/1
    raylikapi_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.124:{FRIGATE_RTSP_PORT}/1/2
    giris_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.120:{FRIGATE_RTSP_PORT}/1/1
    giris_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.120:{FRIGATE_RTSP_PORT}/1/2
    garajustu_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.121:{FRIGATE_RTSP_PORT}/1/1
    garajustu_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.121:{FRIGATE_RTSP_PORT}/1/2
    altbahce_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.122:{FRIGATE_RTSP_PORT}/1/1
    altbahce_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.122:{FRIGATE_RTSP_PORT}/1/2
    kamelya_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.123:{FRIGATE_RTSP_PORT}/1/1
    kamelya_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.123:{FRIGATE_RTSP_PORT}/1/2

cameras:
  raylikapi:
    ffmpeg: &id001
      inputs:
        - path: rtsp://127.0.0.1:8554/raylikapi_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/raylikapi_sub
          roles:
            - detect

    detect: &id002
      enabled: true
      # IMPORTANT: Update width and height to match your camera's sub-stream resolution exactly
      width: 704
      height: 576
      fps: 5

    record: &id003
      enabled: true
      motion:
        days: 2
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots: &id004
      enabled: true

    objects: &id005
      track:
        # - face # NOTE: Don't enable with `person` at the same time
        - person
        - car
        - motorcycle
        - horse
        # - suitcase
        # - knife
        # - cat

    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
  giris:
    <<: &camera_defaults
      ffmpeg: *id001
      detect: *id002
      record: *id003
      snapshots: *id004
      objects: *id005
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/giris_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/giris_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
  garajustu:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garajustu_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garajustu_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
  altbahce:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/altbahce_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/altbahce_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
  kamelya:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamelya_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kamelya_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
version: 0.17-0
