tls:
  enabled: false

auth:
  enabled: false

logger:
  default: info
  logs:
    frigate.event: debug

mqtt:
  enabled: true
  host: '{FRIGATE_MOSQUITTO_HOST}'

# Hardware acceleration for Intel Xe Graphics
ffmpeg:
  # hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: true

# OpenVINO detector for Intel GPU
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    raylikapi_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.124:{FRIGATE_RTSP_PORT}/1/1
    raylikapi_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.124:{FRIGATE_RTSP_PORT}/1/2
    giris_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.120:{FRIGATE_RTSP_PORT}/1/1
    giris_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.120:{FRIGATE_RTSP_PORT}/1/2
    garajustu_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.121:{FRIGATE_RTSP_PORT}/1/1
    garajustu_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.121:{FRIGATE_RTSP_PORT}/1/2
    altbahce_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.122:{FRIGATE_RTSP_PORT}/1/1
    altbahce_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.122:{FRIGATE_RTSP_PORT}/1/2
    kamelya_main:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.123:{FRIGATE_RTSP_PORT}/1/1
    kamelya_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.123:{FRIGATE_RTSP_PORT}/1/2

cameras:
  raylikapi:
    ffmpeg: &id001
      inputs:
        - path: rtsp://127.0.0.1:8554/raylikapi_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/raylikapi_sub
          roles:
            - detect

    detect: &id002
      enabled: true
      # IMPORTANT: Update width and height to match your camera's sub-stream resolution exactly
      width: 704
      height: 576
      fps: 5

    record: &id003
      enabled: true
      motion:
        days: 2
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots: &id004
      enabled: true

    objects: &id005
      track:
        - person
        - car
        - motorcycle
        - horse
        - suitcase
        - knife
        # - face
        # - cat

  giris:
    <<: &camera_defaults
      ffmpeg: *id001
      detect: *id002
      record: *id003
      snapshots: *id004
      objects: *id005
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/giris_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/giris_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
  garajustu:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garajustu_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garajustu_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
  altbahce:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/altbahce_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/altbahce_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
  kamelya:
    <<: *camera_defaults
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamelya_main
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kamelya_sub
          roles:
            - detect

    detect: *id002
    record: *id003
    snapshots: *id004
    objects: *id005
version: 0.17-0
