version: "3.9"
name: photo-dev

networks:
  t2_proxy:
    external: true

services:
  immich-redis-dev:
    container_name: immich-redis-dev
    image: redis:6.2
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy

  immich-postgres-dev:
    container_name: immich-postgres-dev
    image: postgres:14
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-db-dev:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data

  # NOTE: Change `TYPESENSE_HOST` env variable accordingly
  immich-typesense-dev:
    container_name: immich-typesense-dev
    image: typesense/typesense:0.24.0
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-typesense-dev:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none

  immich-server-dev:
    container_name: immich-server-dev
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-redis-dev
      - immich-postgres-dev
      - immich-typesense-dev
    networks:
      - t2_proxy
    volumes:
      - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      - ${MEDIADIR}/Photos/Pictures:/mnt/media/Photos/Pictures:ro
      - ${MEDIADIR}/Photos/Videos:/mnt/media/Photos/Videos:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-server-dev-rtr.entrypoints=https"
      - "traefik.http.routers.immich-server-dev-rtr.rule=Host(`photosdev.$DOMAINNAME`) && Pathprefix(`/api`)"
      ## Middlewares
      - "traefik.http.routers.immich-server-dev-rtr.middlewares=add-api" # chain-authelia@file
      - "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
      ## HTTP Services
      - "traefik.http.routers.immich-server-dev-rtr.service=immich-server-dev-svc"
      - "traefik.http.services.immich-server-dev-svc.loadbalancer.server.port=3001"

  immich-microservices-dev:
    container_name: immich-microservices-dev
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    # restart: $MEDIA_RESTART_POLICY
    restart: on-failure
    depends_on:
      - immich-redis-dev
      - immich-postgres-dev
      - immich-typesense-dev
    networks:
      - t2_proxy
    volumes:
      - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      - ${MEDIADIR}/Photos/Pictures:/mnt/media/Photos/Pictures:ro
      - ${MEDIADIR}/Photos/Videos:/mnt/media/Photos/Videos:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production

  immich-web-dev:
    container_name: immich-web-dev
    image: ghcr.io/immich-app/immich-web:release
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-server-dev
    networks:
      - t2_proxy
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-dev-rtr.entrypoints=https"
      - "traefik.http.routers.immich-dev-rtr.rule=Host(`photosdev.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.immich-dev-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.immich-dev-rtr.service=immich-dev-svc"
      - "traefik.http.services.immich-dev-svc.loadbalancer.server.port=3000"

  immich-machine-learning-dev:
    container_name: immich-machine-learning-dev
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-ml-dev/model-cache:/cache
    env_file:
      - .env
    environment:
      NODE_ENV: production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
