version: "3.9"
name: maintanence

networks:
  t2_proxy:
    external: true
  socket_proxy:
    external: true

services:
  # Linuxserver
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    restart: $MAINTANENCE_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/code-server:/config
      # - $DOCKERDIR:/config/workspace/docker
      - $NOTESDIR:/config/workspace/notes
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEFAULT_WORKSPACE: /config/workspace
      # DOCKER_HOST: tcp://docker-socket-proxy:2375
      # PASSWORD: password
      # HASHED_PASSWORD: 
      SUDO_PASSWORD: ilker
      # SUDO_PASSWORD_HASH: 
      # PROXY_DOMAIN: code-server-ls.my.domain
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.code-server-rtr.entrypoints=https"
      - "traefik.http.routers.code-server-rtr.rule=Host(`code.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.code-server-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.code-server-rtr.service=code-server-svc"
      - "traefik.http.services.code-server-svc.loadbalancer.server.port=8443"

  # OpenVscode - Gitpod
  # openvscode:
  #   image: gitpod/openvscode-server
  #   container_name: openvscode
  #   restart: $MAINTANENCE_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   volumes:
  #     - $DOCKERDIR/appdata/openvscode:/home/workspace:cached
  # #      - $DOCKERDIR:/home/workspace/docker:cached
  # #      - $NOTESDIR:/home/workspace/notes:cached
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.openvscode-rtr.entrypoints=https"
  #     - "traefik.http.routers.openvscode-rtr.rule=Host(`code.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.openvscode-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.openvscode-rtr.service=openvscode-svc"
  #     - "traefik.http.services.openvscode-svc.loadbalancer.server.port=3000"
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    # NOTE: Enable them. Probably needed for connecting to phone (RESEARCH)
    # ports:
    #   - 22000:22000/tcp
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/syncthing:/config
      # - $APKDIR:/apk
      # - $NOTESDIR:/notes
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.syncthing-rtr.entrypoints=https"
      - "traefik.http.routers.syncthing-rtr.rule=Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.syncthing-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.syncthing-rtr.service=syncthing-svc"
      - "traefik.http.services.syncthing-svc.loadbalancer.server.port=8384"

  # duplicati:
  #   image: lscr.io/linuxserver/duplicati
  #   container_name: duplicati
  #   restart: $MAINTANENCE_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   volumes:
  #     - $DOCKERDIR/appdata/duplicati:/config
  #     - $BACKUPDIR:/backups
  #     - $DOCKERDIR:/source
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     # CLI_ARGS:
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.duplicati-rtr.entrypoints=https"
  #     - "traefik.http.routers.duplicati-rtr.rule=Host(`duplicati.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.duplicati-rtr.middlewares=chain-no-auth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.duplicati-rtr.service=duplicati-svc"
  #     - "traefik.http.services.duplicati-svc.loadbalancer.server.port=8200"

  # # Traefik Certs Dumper - Extract LetsEncrypt Certificates - Traefik2 Compatible
  # certdumper:
  #   container_name: traefik_certdumper
  #   image: humenius/traefik-certs-dumper:latest
  #   network_mode: none
  #   # profiles:
  #   # - core
  #   security_opt:
  #     - no-new-privileges:true
  #   # command: --restart-containers container1,container2,container3
  #   volumes:
  #     - $DOCKERDIR/appdata/traefik2/acme:/traefik:ro
  #     - $DOCKERDIR/shared/certs:/output:rw
  #     # - /var/run/docker.sock:/var/run/docker.sock:ro # Only needed if restarting containers (use Docker Socket Proxy instead)
  #   environment:
  #     DOMAIN: $DOMAINNAME

  # # Cloudflare-Companion - Automatic CNAME DNS Creation
  # cf-companion:
  #   container_name: cf-companion
  #   image: tiredofit/traefik-cloudflare-companion:latest
  #   security_opt:
  #     - no-new-privileges:true
  #   restart: $MAINTANENCE_RESTART_POLICY
  #   # profiles:
  #   # - core
  #   networks:
  #     - socket_proxy
  #   #depends_on:
  #   #  - socket-proxy
  #   environment:
  #     - TIMEZONE=$TZ
  #     - TRAEFIK_VERSION=2
  #     #- CF_EMAIL=$CLOUDFLARE_EMAIL
  #     # - CF_TOKEN=$CLOUDFLARE_API_TOKEN
  #     - TARGET_DOMAIN=$DOMAINNAME
  #     - DOMAIN1=$DOMAINNAME
  #     - DOMAIN1_ZONE_ID=$CLOUDFLARE_ZONEID # Copy from Cloudflare Overview page
  #     - DOMAIN1_PROXIED=TRUE
  #     - DOCKER_HOST=tcp://socket-proxy:2375
  #   # secrets: # not working
  #   #   - cloudflare_api_token
  #   labels:
  #     # Add hosts specified in rules here to force cf-companion to create the CNAMEs
  #     # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
  #     - "traefik.http.routers.cf-companion-rtr.rule=Host(`mox.$DOMAINNAME`) || Host(`pwt.$DOMAINNAME`) || Host(`webmin.$DOMAINNAME`) || Host(`shell.$DOMAINNAME`)"


  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   networks:
  #     - t2_proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     TZ: $TZ
  #     WATCHTOWER_SCHEDULE: 0 30 18 * * *
  #     WATCHTOWER_MONITOR_ONLY: "true"
  #     WATCHTOWER_CLEANUP: "true"
  #     WATCHTOWER_NO_STARTUP_MESSAGE: "true"
  #     WATCHTOWER_NOTIFICATIONS: "shoutrrr"
  #     WATCHTOWER_NOTIFICATION_URL: "telegram://$BOT_TOKEN@telegram/?channels=$CHAT_ID"
  #   labels:
  #     - "traefik.enable=true"

  # Contaits guacamole web client, the guacd server and a postgres database
  # Default user/pass: guacadmin/guacadmin
  # guacamole:
  #   image: oznu/guacamole
  #   container_name: guacamole
  #   restart: $MAINTANENCE_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/guacamole:/config
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.guacamole-rtr.entrypoints=https"
  #     - "traefik.http.routers.guacamole-rtr.rule=Host(`guacamole.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.guacamole-rtr.middlewares=chain-no-auth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.guacamole-rtr.service=guacamole-svc"
  #     - "traefik.http.services.guacamole-svc.loadbalancer.server.port=8080"

  # remmina:
  #   image: lscr.io/linuxserver/remmina
  #   container_name: remmina
  #   restart: $MAINTANENCE_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/remmina:/config
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.remmina-rtr.entrypoints=https"
  #     - "traefik.http.routers.remmina-rtr.rule=Host(`remmina.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.remmina-rtr.middlewares=chain-no-auth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.remmina-rtr.service=remmina-svc"
  #     - "traefik.http.services.remmina-svc.loadbalancer.server.port=3000"

  # CrowdSec - Open-source & collaborative security IPS
  # crowdsec:
  #   <<: *common-keys-core # See EXTENSION FIELDS at the top
  #   image: crowdsecurity/crowdsec
  #   container_name: crowdsec
  #   ports:
  #     - "$CROWDSEC_API_PORT:8080"
  #   environment:
  #     COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/nginx crowdsecurity/sshd"
  #     GID: "${GID-1000}"
  #     CUSTOM_HOSTNAME: "cDoc"
  #     DISABLE_LOCAL_API: "true" # Only after successfully registering and validating remote agent below.
  #     # For the following, check local_api_credentials.yaml after cscli lapi register (secondary machine) and cscli machine validate (on primary machine)
  #     AGENT_USERNAME: $CROWDSEC_AGENT_USERNAME 
  #     AGENT_PASSWORD: $CROWDSEC_AGENT_PASSWORD 
  #     LOCAL_API_URL: $CROWDSEC_LOCAL_API_URL 
  #   volumes:
  #     - $DOCKERDIR/logs/cloudserver:/logs:ro
  #     - /var/log:/var/log:ro
  #     - /media/cbox/log:/cbox/log:ro
  #     - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
  #     - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec

  # # CrowdSec Bouncer - Traefik
  # traefik-bouncer:
  #   <<: *common-keys-core # See EXTENSION FIELDS at the top
  #   image: fbonalair/traefik-crowdsec-bouncer
  #   container_name: traefik-bouncer
  #   environment:
  #     GIN_MODE: release # default is debug (more logs)
  #     CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_BOUNCER_TRAEFIK_API_KEY
  #     CROWDSEC_AGENT_HOST: $CROWDSEC_LAPI_HOST:$CROWDSEC_LAPI_PORT # CrowdSec host and port
