name: dekstop_apps

networks:
  t3_proxy:
    external: true
  internal:
    name: internal
    driver: bridge

services:
  ################################################# KASM #################################################
  kasm:
    container_name: kasm
    image: lscr.io/linuxserver/kasm:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    privileged: true
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/kasm/opt:/opt
    #   - /path/to/profiles:/profiles #optional
    #   - /dev/input:/dev/input #optional
    #   - /run/udev/data:/run/udev/data #optional
    ports:
      - 3030:3000
      # - 4443:4443
    # expose:
    #   - 4443
    environment:
      - KASM_PORT=4433
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kasm-rtr.entrypoints=websecure"
      - "traefik.http.routers.kasm-rtr.rule=Host(`kasm.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.kasm-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.kasm-rtr.service=kasm-svc"
      - "traefik.http.services.kasm-svc.loadbalancer.server.port=4443"
      # NOTE: https://docs.linuxserver.io/faq#strict-proxy
      - traefik.http.services.kasm-svc.loadbalancer.serverstransport=ignorecert@file
      - traefik.http.services.kasm-svc.loadbalancer.server.scheme=https

  ## TODO: Not Complete
  ## TODO: Is it possible only run kasmvnc as a server without kasmweb ui?
  ## echo -n "kasm_user:yourmostawesomepasswordhere" | base64
  ## a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ==
  # kasmvnc:
  #   container_name: kasmvnc
  #   image: kasmweb/desktop:latest
  #   restart: $DESKTOP_IMAGES_RESTART_POLICY
  #   shm_size: 512m
  #   networks:
  #     - t3_proxy
  #   # volumes:
  #     # - $DOCKERDIR/appdata/kasmvnc:/TODO
  #   environment:
  #     - VNC_PW=yourmostawesomepasswordhere
  #     - TZ=$TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.kasmvnc-rtr.entrypoints=websecure"
  #     - "traefik.http.routers.kasmvnc-rtr.rule=Host(`kasmvnc.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.kasmvnc-rtr.middlewares=chain-no-auth@file"
  #     - "traefik.http.middlewares.kasmauth.headers.customrequestheaders.Authorization=Basic a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ=="
  #     ## HTTP Services
  #     - "traefik.http.routers.kasmvnc-rtr.service=kasmvnc-svc"
  #     - "traefik.http.services.kasmvnc-svc.loadbalancer.server.port=6901"
  #     # NOTE: https://docs.linuxserver.io/faq#strict-proxy
  #     # - traefik.http.services.kasmvnc-svc.loadbalancer.serverstransport=ignorecert@file
  #     # - traefik.http.services.kasmvnc-svc.loadbalancer.server.scheme=https
  ################################################# KASM #################################################

  webtop:
    container_name: webtop
    image: lscr.io/linuxserver/webtop:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    shm_size: "1gb" #optional
    devices:  #optional
      - /dev/dri:/dev/dri
    # privileged: true
    # security_opt:
    #   - seccomp:unconfined #optional
    networks:
      - t3_proxy
    volumes:
      - $DOCKERDIR/appdata/webtop:/config
      # - /var/run/docker.sock:/var/run/docker.sock #optional
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TITLE=Debian on the Browser
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.webtop-rtr.entrypoints=websecure"
      - "traefik.http.routers.webtop-rtr.rule=Host(`webtop.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.webtop-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.webtop-rtr.service=webtop-svc"
      - "traefik.http.services.webtop-svc.loadbalancer.server.port=3000"

  darktable:
    container_name: darktable
    image: lscr.io/linuxserver/darktable:latest
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $MEDIADIR/Photos:/photos
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.darktable-rtr.entrypoints=websecure"
      - "traefik.http.routers.darktable-rtr.rule=Host(`darktable.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.darktable-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.darktable-rtr.service=darktable-svc"
      - "traefik.http.services.darktable-svc.loadbalancer.server.port=3000"

  firefox:
    container_name: firefox
    image: firefox:latest
    build:
      context: $DESKTOPAPPDOCKERFILES/Firefox
      dockerfile: $DESKTOPAPPDOCKERFILES/Firefox/Dockerfile
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    shm_size: "1gb"  #optional
    devices:  #optional
      - /dev/dri:/dev/dri
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/firefox:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # For watchtower
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.firefox-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.firefox-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=3000"

  # NOTE: Recent file location: /config/.local/share/okular/docdata/
  okular:
    container_name: okular
    image: okular:latest
    build:
      context: $DESKTOPAPPDOCKERFILES/Okular
      dockerfile: $DESKTOPAPPDOCKERFILES/Okular/Dockerfile
    restart: $DESKTOP_IMAGES_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/okular:/config
      - $MEDIADIR/Books:/books
      - $HARDDISKROOTDIR/School/Thesis/Papers:/thesis
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # For watchtower
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.okular-rtr.entrypoints=websecure"
      - "traefik.http.routers.okular-rtr.rule=Host(`okular.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.okular-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.okular-rtr.service=okular-svc"
      - "traefik.http.services.okular-svc.loadbalancer.server.port=3000"