# You have to configure at least one container.
containers:
  container-name: # Exact container name
    keywords:
      - error
      - regex: (username|password).*incorrect # Use regex when you need them

  vaultwarden:
    ntfy_tags: closed_lock_with_key
    ntfy_priority: 5
    ntfy_topic: security
    ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/vaultwarden.png
    notification_cooldown: 0
    keywords:
      - regex: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}).*Username or password is incorrect. Try again. IP: (?P<ip_address>\d{1,3}(?:\.\d{1,3}){3}). Username: (?P<email>[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})'
        message_template: |
          🚨 Failed login!
          📧 Email: '{email}'
          🔎 IP Address: {ip_address}
          🕐 {timestamp}
        title_template: "Failed Vaultwarden login"
        ntfy_tags: rotating_light

  home-assistant:
    ntfy_priority: 5
    ntfy_topic: security
    notification_cooldown: 0
    ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/home-assistant.png
    keywords:
      - regex: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*Login attempt or request with invalid authentication from (?P<ip>.*)\. Requested URL.*'
        message_template: |
          🚨 Failed login!
          🔎 IP Address: {ip}
          🕐 {timestamp}
        title_template: "Failed Home Assistant login"
        ntfy_tags: closed_lock_with_key,rotating_light

  immich-server:
    ntfy_tags: camera_flash
    ntfy_priority: 5
    ntfy_topic: security
    ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/immich.png
    notification_cooldown: 0
    keywords:
      - regex: '.*(?P<timestamp>\d{2}\/\d{2}\/\d{4}, \d+:\d{2}:\d{2} (?:AM|PM)).*Failed login attempt for user (?P<username>.*) from ip address (?P<ip>.*)'
        message_template: |
          🚨 Failed login!
          📧 Username: '{username}'
          🔎 IP Address: {ip}
          🕐 {timestamp}
        title_template: "Failed Immich login"
        ntfy_tags: camera_flash,rotating_light

  immich-machine-learning:
    ntfy_tags: camera_flash,robot
    ntfy_topic: server
    ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/immich.png
    ntfy_markdown: true
    container_events:
      - event: oom
        attach_logfile: true
        ntfy_tags: robot,rotating_light
      - event: crash
        ntfy_tags: robot,rotating_light
        action: restart
        action_cooldown: 10
        title_template: "Immich Machine Learning Container crashed (exit code: {exit_code})"
        # link inside message_template is formatted as markdown for the ntfy notification because of ntfy_markdown: true
        message_template: |
          🔁 {action_result_message}
          🔎 [Link to Dozzle](http://192.168.178.222:8080/container/{container_id})

  adguardhome:
    attach_logfile: true # Attach a log file to the notification
    attachment_lines: 100
    ntfy_topic: adguard
    ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/adguard-home-light.png
    keywords:
      - failed
      - error

# Optional. These keywords are being monitored for all configured containers.
# global_keywords:
#   keywords:
#     - failed
#     - critical
#     - error
#     - keyword: panic
#       attach_logfile: true  # Attach a log file to the notification
#     - keyword: fatal
#       ntfy_topic: fatal-errors

notifications:
  # At least one of these (ntfy/Apprise/Webhook) is required.
  ntfy:
    url: http://your-ntfy-server # Required. The URL of your ntfy instance
    topic: loggifly # Required. the topic for ntfy
    token: ntfy-token # ntfy token in case you need authentication
    username: john # ntfy Username + Password in case you need authentication
    password: password # ntfy Username + Password in case you need authentication
    priority: 3 # ntfy priority (1-5)
    tags: kite,mag # ntfy tags/emojis
  apprise:
    url: "discord://webhook-url" # Any Apprise-compatible URL (https://github.com/caronc/apprise/wiki)
  webhook:
    url: https://custom.endpoint.com/post
    headers: # add headers if needed
      Authorization: "Bearer token"
      X-Custom-Header": "Test123"

# Since all settings have default values, we can only set the ones we want to change.
# This is just an example of settings you might want to change. See the docs for all available settings.
settings:
  disable_config_reload_message: True # Suppress config reload notification
  disable_monitor_event_message: True # Suppress notifications when container monitoring starts/stops
  notification_cooldown: 0 # Seconds between alerts for same keyword (per container)
  action_cooldown: 60 # Cooldown (seconds) before next container action (min 60s)
  hide_regex_in_title: True # Hide full regex pattern in found keywords in notification title for cleaner look
