global:
  defaults:
    trigger_cooldown: 0
    container_action_cooldown: 60
    hide_full_regex: true

containers:
  rules:
    - id: vaultwarden
      container_name: vaultwarden
      ntfy_tags: closed_lock_with_key
      ntfy_topic: security
      ntfy_priority: 5
      ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/vaultwarden.png
      keywords:
        - regex: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}).*Username or password is incorrect. Try again. IP: (?P<ip_address>\d{1,3}(?:\.\d{1,3}){3}). Username: (?P<email>[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})'
          ntfy_tags: rotating_light
          title_template: Failed Vaultwarden login
          message_template: |
            🚨 Failed login!
            📧 Email: '{{ email }}'
            🔎 IP Address: {{ ip_address }}
            🕐 {{ timestamp }}

    - id: home-assistant
      container_name: home-assistant
      ntfy_topic: security
      ntfy_priority: 5
      ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/home-assistant.png
      keywords:
        - regex: (?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*Login attempt or request with invalid authentication from (?P<ip>.*)\. Requested URL.*
          ntfy_tags: closed_lock_with_key,rotating_light
          title_template: Failed Home Assistant login
          message_template: |
            🚨 Failed login!
            🔎 IP Address: {{ ip }}
            🕐 {{ timestamp }}

    - id: immich-server
      container_name: immich-server
      ntfy_tags: camera_flash
      ntfy_topic: security
      ntfy_priority: 5
      ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/immich.png
      keywords:
        - regex: .*(?P<timestamp>\d{2}\/\d{2}\/\d{4}, \d+:\d{2}:\d{2} (?:AM|PM)).*Failed login attempt for user (?P<username>.*) from ip address (?P<ip>.*)
          ntfy_tags: camera_flash,rotating_light
          title_template: Failed Immich login
          message_template: |
            🚨 Failed login!
            📧 Username: '{{ username }}'
            🔎 IP Address: {{ ip }}
            🕐 {{ timestamp }}

    - id: immich-machine-learning
      container_name: immich-machine-learning
      ntfy_tags: camera_flash,robot
      ntfy_topic: server
      ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/immich.png
      ntfy_markdown: true
      container_events:
        - ntfy_tags: robot,rotating_light
          attach_logfile: true
          event: oom
        - container_action: restart
          ntfy_tags: robot,rotating_light
          title_template: "Immich Machine Learning Container crashed (exit code: {{ exit_code }})"
          message_template: |
            🔁 {{ container_action_result_message }}
            🔎 [Link to Dozzle](http://192.168.178.222:8080/container/{{ container_id }})
          event: crash
          container_action_cooldown: 10

    - id: adguardhome
      container_name: adguardhome
      ntfy_topic: adguard
      ntfy_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/adguard-home-light.png
      attachment_lines: 100
      attach_logfile: true
      keywords:
        - failed
        - error

# notifications:
#   ntfy:
#     url: http://your-ntfy-server
#     topic: loggifly
#     token: ntfy-token
#     username: john
#     password: password
#     priority: 3
#     tags: kite,mag
#   apprise:
#     url: discord://webhook-url
#   webhook:
#     url: https://custom.endpoint.com/post
#     headers:
#       Authorization: Bearer token
#       X-Custom-Header": Test123

settings:
  system_notifications:
    config_reload: false
    monitor_event: false
