version: "3.9"
name: photo

networks:
  t2_proxy:
    external: true

services:
  immich-redis:
    container_name: immich-redis
    image: redis:6.2
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy

  immich-postgres:
    container_name: immich-postgres
    image: postgres:14
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data

  # NOTE: When renaming to immich-typesense, it is not working
  typesense:
    container_name: typesense
    image: typesense/typesense:0.24.0
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/typesense:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-redis
      - immich-postgres
      - typesense
    networks:
      - t2_proxy
    ports:
      - "3001:3001"
    # expose:
    #   - "3001"
    volumes:
      - ${ORIGINAL_UPLOAD_LOCATION}:/usr/src/app/upload
      # - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      # - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      # - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      ## - ${GENERATED_UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
    env_file:
      - .env
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-server-rtr.entrypoints=https"
      - "traefik.http.routers.immich-server-rtr.rule=Host(`photos.$DOMAINNAME`) && Pathprefix(`/api`)"
      ## Middlewares
      - "traefik.http.routers.immich-server-rtr.middlewares=add-api" # chain-authelia@file
      - "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
      ## HTTP Services
      - "traefik.http.routers.immich-server-rtr.service=immich-server-svc"
      - "traefik.http.services.immich-server-svc.loadbalancer.server.port=3001"

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    # restart: $MEDIA_RESTART_POLICY
    restart: on-failure
    depends_on:
      - immich-redis
      - immich-postgres
      - typesense
    networks:
      - t2_proxy
    volumes:
      - ${ORIGINAL_UPLOAD_LOCATION}:/usr/src/app/upload
      # - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      # - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      # - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      ## - ${GENERATED_UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
    env_file:
      - .env
    environment:
      NODE_ENV: production
    # labels:
    #   - "traefik.enable=true"
    #   ## HTTP Routers
    #   - "traefik.http.routers.immich-microservices.entrypoints=https"
    #   - "traefik.http.routers.immich-microservices.rule=Host(`immich-mc.$DOMAINNAME`)"
    #   ## Middlewares
    #   # - "traefik.http.routers.immich-microservices.middlewares=chain-authelia@file"
    #   ## HTTP Services
    #   # - "traefik.http.routers.immich-microservices.service=immich-microservices-svc"
    #   - "traefik.http.services.immich-microservices-svc.loadbalancer.server.port=3001"

  immich-web:
    container_name: immich-web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-server
    networks:
      - t2_proxy
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-rtr.entrypoints=https"
      - "traefik.http.routers.immich-rtr.rule=Host(`photos.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.immich-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=3000"

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-ml/model-cache:/cache
      - ${ORIGINAL_UPLOAD_LOCATION}:/usr/src/app/upload
      # - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      # - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      # - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      ## - ${GENERATED_UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
    env_file:
      - .env
    environment:
      NODE_ENV: production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]