name: photo

networks:
  t2_proxy:
    external: true

services:
  immich-redis:
    container_name: immich-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy

  immich-database:
    container_name: immich-database
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-redis
      - immich-database
    networks:
      - t2_proxy
    volumes:
      - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      - ${MEDIADIR}/Photos/Pictures:/mnt/media/Photos/Pictures:ro
      - ${MEDIADIR}/Photos/Videos:/mnt/media/Photos/Videos:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-server-rtr.entrypoints=https"
      - "traefik.http.routers.immich-server-rtr.rule=Host(`photos.$DOMAINNAME`)"
      # - "traefik.http.routers.immich-server-rtr.rule=Host(`photos.$DOMAINNAME`) && Pathprefix(`/api`)"
      ## Middlewares
      - "traefik.http.routers.immich-server-rtr.middlewares=chain-authelia@file"
      # - "traefik.http.routers.immich-server-rtr.middlewares=add-api"
      # - "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
      ## HTTP Services
      - "traefik.http.routers.immich-server-rtr.service=immich-server-svc"
      - "traefik.http.services.immich-server-svc.loadbalancer.server.port=3001"

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    # restart: $MEDIA_RESTART_POLICY
    restart: on-failure
    depends_on:
      - immich-redis
      - immich-database
    networks:
      - t2_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ORIGINAL_UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${GENERATED_UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${GENERATED_UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${GENERATED_UPLOAD_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-videos
      - ${MEDIADIR}/Photos/Pictures:/mnt/media/Photos/Pictures:ro
      - ${MEDIADIR}/Photos/Videos:/mnt/media/Photos/Videos:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/immich-ml/model-cache:/cache
    env_file:
      - .env
    environment:
      NODE_ENV: production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ##############################################
  # https://github.com/Salvoxia/immich-folder-album-creator
  immich-folder-album-creator:
    container_name: immich-folder-album-creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: "no"
    # command: ["/script/immich_auto_album.sh"] # NOTE: Manually run
    networks:
      - t2_proxy
    environment:
      API_URL: http://immich-server:3001/api
      API_KEY: $IMMICH_API_KEY
      ROOT_PATH: /mnt/media/Photos/Pictures
      CRON_EXPRESSION: "0 2 * * *"
      TZ: Europe/Istanbul
      ALBUM_LEVELS: 1
      LOG_LEVEL: INFO