version: "3.7"

networks:
  t2_proxy:
    external: true

########################### SECRETS
secrets:
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password
  mysql_password:
    file: $DOCKERDIR/secrets/mysql_password

# volumes:
#   pgdata:

services:
  ############################## IMMICH ##############################
  immich-redis:
    container_name: immich-redis
    image: redis:6.2
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t2_proxy  

  immich-postgres:
    container_name: immich-postgres
    image: postgres:14
    networks:
      - t2_proxy
    # ports:
    #   - 5432:5432
    volumes:
      - $DOCKERDIR/appdata/immich-db:/var/lib/postgresql/data
      # - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    

  # https://hub.docker.com/r/altran1502/immich-server/
  # Register user:
  # curl --location --request POST 'https://immichserver.ilkerflix.com/api/auth/signUp' --header 'Content-Type: application/json' --data-raw '{"email": "ilker4fun@gmail.com","password": "ilker"}'
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./start-server.sh"]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-redis
      - immich-postgres
    networks:
      - t2_proxy
    volumes:
      # - /usr/src/app/node_modules
      - $IMMICH_UPLOAD_DIR:/usr/src/app/upload
      # - $DOCKERDIR/appdata/immich:/usr/src/app
      # - $DOCKERDIR/appdata/immich/node_modules:/usr/src/app/node_modules
    environment:
      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: immich
      DB_PASSWORD: immich
      DB_DATABASE_NAME: immich
      UPLOAD_LOCATION: $IMMICH_UPLOAD_DIR
      JWT_SECRET: "False"
      NODE_ENV: production
      ENABLE_MAPBOX: "False"
      # MAPBOX_KEY: ""
      # VITE_SERVER_ENDPOINT: https://immichserver.ilkerflix.com:443/api
      VITE_SERVER_ENDPOINT: https://immichserver.ilkerflix.com:443
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-server-rtr.entrypoints=https"
      - "traefik.http.routers.immich-server-rtr.rule=Host(`immichserver.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.immich-server-rtr.middlewares=add-api" # chain-authelia@file
      - "traefik.http.middlewares.add-api.addPrefix.prefix=/api"
      ## HTTP Services
      - "traefik.http.routers.immich-server-rtr.service=immich-server-svc"
      - "traefik.http.services.immich-server-svc.loadbalancer.server.port=3000"

  immich-web:
    container_name: immich-web
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    # ports:
    #   - 2285:3000
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-server
    networks:
      - t2_proxy
    environment:
      # VITE_SERVER_ENDPOINT: https://immichserver.ilkerflix.com:443/api
      VITE_SERVER_ENDPOINT: https://immichserver.ilkerflix.com:443
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-rtr.entrypoints=https"
      - "traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.immich-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=3000"

  immich-microservices:
    container_name: immich-microservices
    image: altran1502/immich-microservices:latest
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - immich-redis
      - immich-postgres
    networks:
      - t2_proxy
    # expose:
    #   - "3001"
    volumes:
      - $IMMICH_UPLOAD_DIR:/usr/src/app/upload
    environment:
      DB_USERNAME: immich
      DB_PASSWORD: immich
      DB_DATABASE_NAME: immich
      UPLOAD_LOCATION: $IMMICH_UPLOAD_DIR
      JWT_SECRET: "False"
      NODE_ENV: production
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-microservices.entrypoints=https"
      - "traefik.http.routers.immich-microservices.rule=Host(`immich-mc.$DOMAINNAME`)"
      ## Middlewares
      # - "traefik.http.routers.immich-microservices.middlewares=chain-authelia@file"
      ## HTTP Services
      # - "traefik.http.routers.immich-microservices.service=immich-microservices-svc"
      - "traefik.http.services.immich-microservices-svc.loadbalancer.server.port=3001"