# NOTE: In initial configuration screen, choose dashboard port 81 to avoid conflict with traefik
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.71
    container_name: adguardhome
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    network_mode: host
    expose:
      - "81"
      - "53"
      - "853"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/adguardhome:/opt/adguardhome/conf:rw
      - $REPO_PATH/appdata/adguardhome/work:/opt/adguardhome/work
    environment:
      TZ: $TZ
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "adguardhome"
      homepage.icon: "adguard-home.svg"
      homepage.href: "https://adguardhome.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Network-wide ads & trackers blocking DNS server"
      homepage.widget.type: "adguard"
      homepage.widget.url: "https://adguardhome.$DOMAINNAME"
      homepage.widget.username: "$ADGUARD_USERNAME"
      homepage.widget.password: "$ADGUARD_PASSWORD"
      ####### GLANCE #######
      glance.name: "adguardhome"
      glance.icon: "sh:adguard-home"
      glance.url: "https://adguardhome.$DOMAINNAME"
      glance.description: "Network-wide ads & trackers blocking DNS server"
