services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: $MEDIA_RESTART_POLICY
    depends_on:
      - nzbdav
    profiles:
      - media
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/aiostreams:/app/data
    environment:
      ADDON_NAME: AIOStreams
      ADDON_ID: aiostreams.$DOMAINNAME
      BASE_URL: https://aiostreams.$DOMAINNAME
      AIOSTREAMS_AUTH: $AIOSTREAMS_AUTH
      SECRET_KEY: $AIOSTREAMS_SECRET_KEY
      TMDB_ACCESS_TOKEN: $TMDB_READ_ACCESS_TOKEN
    # env_file:
    #   - $DOCKERDIR/.env.aiostreams
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.aiostreams-rtr.entrypoints: "websecure"
      traefik.http.routers.aiostreams-rtr.rule: "Host(`aiostreams.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.aiostreams-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.aiostreams-rtr.service: "aiostreams-svc"
      traefik.http.services.aiostreams-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.aiostreams.config.domain: "aiostreams.$DOMAINNAME"
      tinyauth.apps.aiostreams.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "aiostreams"
      homepage.icon: "aiostreams.png"
      homepage.href: "https://aiostreams.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "description"
      ####### GLANCE #######
      glance.name: "aiostreams"
      glance.icon: "sh:aiostreams"
      glance.url: "https://aiostreams.$DOMAINNAME"
      glance.description: "description"