services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:v2.32.1@sha256:071fce6e6a42ccca3b32d7a0b94edfb1d5d131616beed30899d0ba21f90cc1f8
    container_name: aiostreams
    restart: $RESTART_POLICY_MEDIA
    # NOTE: Not needed after v2.30.0
    # depends_on:
    #   - nzbdav
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "2.0"
    mem_limit: "4G"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - $REPO_PATH/data/aiostreams:/app/data
    # NOTE: https://docs.aiostreams.viren070.me/configuration/environment-variables
    environment:
      ADDON_NAME: AIOStreams
      ADDON_ID: aiostreams.$BASE_DOMAINNAME
      BASE_URL: https://aiostreams.$BASE_DOMAINNAME
      AIOSTREAMS_AUTH_REQUIRED: true
      AIOSTREAMS_AUTH: $AIOSTREAMS_AUTH
      # AIOSTREAMS_AUTH_PERMISSIONS: $AIOSTREAMS_USER_NAME=admin
      SECRET_KEY: $AIOSTREAMS_SECRET_KEY
      TMDB_ACCESS_TOKEN: $TMDB_API_READ_ACCESS_TOKEN
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "/app/scripts/healthcheck.js"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 1m
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.aiostreams-rtr.entrypoints: "websecure"
      traefik.http.routers.aiostreams-rtr.rule: "Host(`aiostreams.$BASE_DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.aiostreams-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.aiostreams-rtr.service: "aiostreams-svc"
      traefik.http.services.aiostreams-svc.loadbalancer.server.port: "3000"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "aiostreams"
      homepage.icon: "aiostreams.png"
      homepage.href: "https://aiostreams.$BASE_DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Consolidates multiple Stremio addons and debrid services into a single addon"
      ####### GLANCE #######
      glance.name: "aiostreams"
      glance.icon: "sh:aiostreams"
      glance.url: "https://aiostreams.$BASE_DOMAINNAME"
      glance.description: "Consolidates multiple Stremio addons and debrid services into a single addon"
