services:
  alertmanager:
    image: prom/alertmanager:latest@sha256:58e117eabccebbff04e6643a3432d6315a2cc3a8c24ab5849bc628886bf08857
    container_name: alertmanager
    restart: $RESTART_POLICY_MAINTENANCE
    networks:
      - t3_proxy
    expose:
      - 9093
    volumes:
      - $REPO_PATH/configs/alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role==manager
    # labels:
    #   - "traefik.enable=true"
    #   ## HTTP Routers
    #   - "traefik.http.routers.alertmanager-rtr.entrypoints=websecure"
    #   - "traefik.http.routers.alertmanager-rtr.rule=Host(`alertmanager.$DOMAINNAME`)"
    #   ## Middlewares
    #   - "traefik.http.routers.alertmanager-rtr.middlewares=chain-no-auth@file"
    #   ## HTTP Services
    #   - "traefik.http.routers.alertmanager-rtr.service=alertmanager-svc"
    #   - "traefik.http.services.alertmanager-svc.loadbalancer.server.port=9093"

    profiles:
      - monitoring
