services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:v1.18.0@sha256:c0a5d2dc6fbbd8e00400bdb8a03cb949d2c53b6143fd708858478812d2eee820
    container_name: arcane-agent
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "3553:3553"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/arcane-agent:/app/data
    environment:
      AGENT_MODE: true
      AGENT_TOKEN: $ARCANE_AGENT_TOKEN
      ANALYTICS_DISABLED: true
      DOCKER_HOST: tcp://docker-socket-proxy-exec:2375
      EDGE_TRANSPORT: auto
      ENVIRONMENT: production
      GPU_MONITORING_ENABLED: true
      GPU_TYPE: nvidia
      MANAGER_API_URL: https://arcane.gpu.$BASE_DOMAINNAME
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "arcane-agent"
      homepage.icon: "arcane.png"
      homepage.description: "Modern Docker Management Remote Agent"
      ####### GLANCE #######
      glance.name: "arcane-agent"
      glance.icon: "sh:arcane"
      glance.description: "Modern Docker Management Remote Agent"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
