services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    restart: $RESTART_POLICY_CORE
    profiles:
      - root
      - core
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "3553:3553"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/arcane-agent:/app/data
    environment:
      AGENT_MODE: true
      AGENT_BOOTSTRAP_TOKEN: $ARCANE_AGENT_BOOTSTRAP_TOKEN
      ANALYTICS_DISABLED: true
      DOCKER_HOST: tcp://docker-socket-proxy-exec:2375
      GPU_MONITORING_ENABLED: ${GPU_MONITORING_ENABLED:-false}
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "arcane-agent"
      homepage.icon: "arcane.png"
      homepage.description: "Modern Docker Management Remote Agent"
      ####### GLANCE #######
      glance.name: "arcane-agent"
      glance.icon: "sh:arcane"
      glance.description: "Modern Docker Management Remote Agent"
