# NOTE: To see the config: docker compose run authelia authelia config template
# Env var issue: https://github.com/authelia/authelia/issues/920#issuecomment-2029652076
services:
  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.38.18
    depends_on:
      - traefik
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/authelia:/config
      - $REPO_PATH/configs/authelia/config/configuration.yml:/config/configuration.yml
      - $REPO_PATH/configs/authelia/config/users.yml:/config/users.yml
      - $REPO_PATH/configs/authelia/secrets:/secrets
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      # - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
      #  Custom Environment Variables
      # - X_AUTHELIA_CONFIG_FILTERS=template # Needed for environment variables to work but breaks existing config
      DOMAINNAME: $DOMAINNAME
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
    #  - authelia_duo_api_secret_key
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.authelia-rtr.entrypoints: "websecure"
      traefik.http.routers.authelia-rtr.rule: "Host(`authelia.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.authelia-rtr.middlewares: "chain-no-auth@file" # IMPORTANT
      ## HTTP Services
      traefik.http.routers.authelia-rtr.service: "authelia-svc"
      traefik.http.services.authelia-svc.loadbalancer.server.port: "9091"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "Authelia"
      homepage.icon: "authelia.svg"
      homepage.href: "https://authelia.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Secure Single Sign On"
