# TODO: Harden
# NOTE: Consumes +2GB RAM
services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:02.07.00@sha256:3972e222f1e6b3087ededc30a20c726ce1e7b08f760e82d9395b724dae07c6e7
    container_name: bambustudio
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    hostname: bambustudio
    profiles:
      - desktop_apps
    networks:
      - t3_proxy
    expose:
      - 3000 # HTTP
      - 3001 # HTTPS
    security_opt:
      - no-new-privileges:true
    shm_size: "1gb"
    # pids_limit: 256
    # cpus: '1.0'
    mem_limit: 5g
    # ulimits:
    #   nofile:
    #     soft: 4096
    #     hard: 8192
    volumes:
      - $REPO_PATH/data/bambustudio:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Bambu-Studio
      # DARK_MODE: true
      PIXELFLUX_WAYLAND: true
      # DRI_NODE: /dev/dri/renderD128 # NOTE: Don't set this. It breaks HW.
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:3000/ >/dev/null || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 2m
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bambustudio-rtr.entrypoints: "websecure"
      traefik.http.routers.bambustudio-rtr.rule: "Host(`bambustudio.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bambustudio-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.bambustudio-rtr.service: "bambustudio-svc"
      traefik.http.services.bambustudio-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.bambustudio.config.domain: "bambustudio.$DOMAINNAME"
      tinyauth.apps.bambustudio.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "bambustudio"
      homepage.icon: "bambustudio.png"
      homepage.href: "https://bambustudio.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "PC Software for BambuLab and other 3D printers"
      ####### GLANCE #######
      glance.name: "bambustudio"
      glance.icon: "sh:bambustudio"
      glance.url: "https://bambustudio.$DOMAINNAME"
      glance.description: "PC Software for BambuLab and other 3D printers"
    # For Nvidia Zero Copy Rendering
    group_add:
      # - "44" # video
      - "992" # render
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, graphics, utility]
