# NOTE: Consumes +2GB RAM
services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    hostname: bambustudio
    shm_size: "1gb"
    mem_limit: 5g
    profiles:
      - desktop_apps
    networks:
      - t3_proxy
    expose:
      - 3000 # HTTP
      - 3001 # HTTPS
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/data/bambustudio:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Bambu-Studio
      # DARK_MODE: true
      PIXELFLUX_WAYLAND: true
      # DRI_NODE: /dev/dri/renderD128 # NOTE: Don't set this. It breaks HW.
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bambustudio-rtr.entrypoints: "websecure"
      traefik.http.routers.bambustudio-rtr.rule: "Host(`bambustudio.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bambustudio-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.bambustudio-rtr.service: "bambustudio-svc"
      traefik.http.services.bambustudio-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.bambustudio.config.domain: "bambustudio.$DOMAINNAME"
      tinyauth.apps.bambustudio.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "bambustudio"
      homepage.icon: "bambustudio.png"
      homepage.href: "https://bambustudio.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "PC Software for BambuLab and other 3D printers"
      ####### GLANCE #######
      glance.name: "bambustudio"
      glance.icon: "sh:bambustudio"
      glance.url: "https://bambustudio.$DOMAINNAME"
      glance.description: "PC Software for BambuLab and other 3D printers"
    # For Nvidia Zero Copy Rendering
    group_add:
      # - "44" # video
      - "992" # render
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, graphics, utility]
