services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest@sha256:f54b9ed9c56b767e0098b525468206689b666323c2b500b9686c3cf41cdfa348
    container_name: bentopdf
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - custom-user
      - maintenance
    networks:
      - t3_proxy
    user: 6969:6969
    read_only: true
    tmpfs:
      - /tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /var/cache/nginx:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /etc/nginx/tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /var/lib/nginx/tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    # environment:
    #   DISABLE_IPV6: true
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8080']
      start_period: 5s
      interval: 1m
      timeout: 3s
      retries: 5
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bentopdf-rtr.entrypoints: "websecure"
      traefik.http.routers.bentopdf-rtr.rule: "Host(`pdftool.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bentopdf-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.bentopdf-rtr.service: "bentopdf-svc"
      traefik.http.services.bentopdf-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.bentopdf.config.domain: "pdftool.$DOMAINNAME"
      tinyauth.apps.bentopdf.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "bentopdf"
      homepage.icon: "bentopdf.png"
      homepage.href: "https://pdftool.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A Privacy First PDF Toolkit"
      ####### GLANCE #######
      glance.name: "bentopdf"
      glance.icon: "sh:bentopdf"
      glance.url: "https://pdftool.$DOMAINNAME"
      glance.description: "A Privacy First PDF Toolkit"
