services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:2.8.7@sha256:ba67d44f07ec0d2d636c945eef1c186f71bceda3d11b1e9809d7dbfbbaaacfa4
    container_name: bentopdf
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    user: 6969:6969
    read_only: true
    tmpfs:
      - /tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /var/cache/nginx:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /etc/nginx/tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
      - /var/lib/nginx/tmp:uid=6969,gid=6969,rw,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      # PUID: $PUID
      # PGID: $PGID
      PORT: 8080
      # DISABLE_IPV6: true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bentopdf-rtr.entrypoints: "websecure"
      traefik.http.routers.bentopdf-rtr.rule: "Host(`pdftool.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bentopdf-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.bentopdf-rtr.service: "bentopdf-svc"
      traefik.http.services.bentopdf-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.bentopdf.config.domain: "pdftool.$DOMAINNAME"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "bentopdf"
      homepage.icon: "bentopdf.png"
      homepage.href: "https://pdftool.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A Privacy First PDF Toolkit"
      ####### GLANCE #######
      glance.name: "bentopdf"
      glance.icon: "sh:bentopdf"
      glance.url: "https://pdftool.$DOMAINNAME"
      glance.description: "A Privacy First PDF Toolkit"
