# NOTE: When config_store is disabled, all config related UI places are also disabled
# NOTE: Bifrost appends `/v1` into providers urls.
# TODO: Enable username/password to add API_KEY support
# TODO: Enable OpenTelemetry so that we ditch the bifrost UI completely
# TODO: Research Vector Store integration for Semantic Caching
services:
  bifrost:
    image: maximhq/bifrost:v1.4.23@sha256:4ce7dc06559eb0beebfcda9b94af13e91cb4d6d75c4fa92c3bb0f608a12b0f2f
    container_name: bifrost
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - custom-user
      - programming
    networks:
      - t3_proxy
    user: appuser
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    entrypoint: # NOTE: For custom base_url env logic
      - /bin/sh
      - /app/render-config.sh
    volumes:
      # - $REPO_PATH/configs/bifrost/config.json:/app/data/config.json
      # NOTE: Enables persistence for logs, NOT CONFIGS
      - $REPO_PATH/data/bifrost:/app/data
      - $REPO_PATH/configs/bifrost/config.json:/app/data/config.template.json:ro # NOTE: For custom base_url env logic
      - $REPO_PATH/configs/bifrost/render-config.sh:/app/render-config.sh:ro # NOTE: For custom base_url env logic
    environment:
      APP_DIR: /tmp/bifrost # NOTE: For custom base_url env logic
      LOG_LEVEL: info
      LOG_STYLE: json
      ## Providers
      OPENROUTER_API_BASE_URL: $OPENROUTER_API_BASE_URL
      OPENROUTER_API_KEY: $OPENROUTER_API_KEY
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_PERSONAL_API_KEY: $OPENAI_PERSONAL_API_KEY
      OPENAI_GEMMA4_31B_IT_BASE_URL: $OPENAI_GEMMA4_31B_IT_BASE_URL
      OPENAI_QWEN_3_6_35B_A3B_BASE_URL: $OPENAI_QWEN_3_6_35B_A3B_BASE_URL
      OPENAI_QWEN_IMAGE_2512_BASE_URL: $OPENAI_QWEN_IMAGE_2512_BASE_URL
      OPENAI_HOMESERVER_API_BASE_URL: $OPENAI_HOMESERVER_API_BASE_URL
      OPENAI_HOMESERVER_API_KEY: $OPENAI_HOMESERVER_API_KEY
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bifrost-rtr.entrypoints: "websecure"
      traefik.http.routers.bifrost-rtr.rule: "Host(`aigateway.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bifrost-rtr.middlewares: "chain-tinyauth-relaxed@file" # NOTE: For `List Models Output monaco editor`
      ## HTTP Services
      traefik.http.routers.bifrost-rtr.service: "bifrost-svc"
      traefik.http.services.bifrost-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.bifrost.config.domain: "aigateway.$DOMAINNAME"
      tinyauth.apps.bifrost.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "bifrost"
      homepage.icon: "bifrost.png"
      homepage.href: "https://aigateway.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "AI gateway"
      ####### GLANCE #######
      glance.name: "bifrost"
      glance.icon: "sh:bifrost"
      glance.url: "https://aigateway.$DOMAINNAME"
      glance.description: "AI gateway"
