# NOTE: Nothing is working on Firefox
services:
  bitplay:
    image: ghcr.io/aculix/bitplay:main
    container_name: bitplay
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/bitplay:/app/config
      - $REPO_PATH/appdata/bitplay:/app/torrent-data
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bitplay-rtr.entrypoints: "websecure"
      traefik.http.routers.bitplay-rtr.rule: "Host(`bitplay.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.bitplay-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.bitplay-rtr.service: "bitplay-svc"
      traefik.http.services.bitplay-svc.loadbalancer.server.port: "3347"
      ####### TINYAUTH #######
      tinyauth.apps.bitplay.config.domain: "bitplay.$DOMAINNAME"
      tinyauth.apps.bitplay.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "bitplay"
      homepage.icon: "bitplay.png"
      homepage.href: "https://bitplay.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Stream video torrents in your web browser with ease."
      ####### GLANCE #######
      glance.name: "bitplay"
      glance.icon: "sh:bitplay"
      glance.url: "https://bitplay.$DOMAINNAME"
      glance.description: "Stream video torrents in your web browser with ease."
