services:
  buildarr:
    image: callum027/buildarr:latest@sha256:57e2343fefe5d5701364b5e93b4985dbf08310d7b152f70556bdaba7e9475447
    container_name: buildarr
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - prowlarr
      - radarr
      # - sonarr
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/configs/buildarr:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BUILDARR_LOG_LEVEL: INFO
      BUILDARR_INSTALL_PACKAGES: "buildarr-prowlarr buildarr-radarr"
    profiles:
      - media
      - arr
