services:
  # Traefik Certs Dumper - Extract LetsEncrypt Certificates - traefik3 Compatible
  certdumper:
    container_name: traefik_certdumper
    image: humenius/traefik-certs-dumper:latest
    network_mode: none
    profiles:
      - maintenance
    security_opt:
      - no-new-privileges:true
    # command: --restart-containers container1,container2,container3
    volumes:
      - $REPO_PATH/appdata/traefik3/acme:/traefik:ro
      - $REPO_PATH/shared/certs:/output:rw
    environment:
      DOMAIN: $DOMAINNAME
