services:
  chromium:
    container_name: chromium
    image: lscr.io/linuxserver/ungoogled-chromium:latest@sha256:1a10cf258dfb276fe69ee943462dfca41e5968de55c7d03984abbb1f5f9646c0
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    shm_size: "1gb"
    profiles:
      - desktop_apps
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: chromium
      PIXELFLUX_WAYLAND: true
      # DRI_NODE: /dev/dri/renderD128 # NOTE: Don't set this. It breaks HW.
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.chromium-rtr.entrypoints: "websecure"
      traefik.http.routers.chromium-rtr.rule: "Host(`chromium.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.chromium-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.chromium-rtr.service: "chromium-svc"
      traefik.http.services.chromium-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.chromium.config.domain: "chromium.$DOMAINNAME"
      tinyauth.apps.chromium.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Ungoogled Chromium"
      homepage.icon: "chromium.svg"
      homepage.href: "https://chromium.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Ungoogled Chromium Browser"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 1m
      timeout: 5s
      retries: 3
    # For Nvidia Zero Copy Rendering
    group_add:
      # - "44" # video
      - "992" # render
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, graphics, utility]
