services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.6
    container_name: crowdsec
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
      - crowdsec
    networks:
      - crowdsec_lapi
    user: "$PUID:$PGID"
    group_add:
      - "${CROWDSEC_LOG_GROUP_GID:-4}"
    entrypoint:
      - /bin/bash
      - -ec
      - |
        mkdir -p /var/lib/crowdsec/data/plugins
        cp -f /usr/local/lib/crowdsec/plugins/* /var/lib/crowdsec/data/plugins/
        exec /bin/bash /docker_start.sh
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m
      - /run:rw,nosuid,nodev,size=16m
    expose:
      - 8080 # LAPI endpoint for Traefik bouncer via crowdsec_lapi
      - 6060 # metrics endpoint for prometheus
      - 7422 # appsec waf endpoint
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - /var/log:/var/log:ro # NOTE: Needs adm group privileges on host to read logs
      - $REPO_PATH/logs/traefik:/logs/traefik:ro
      ## Configs
      - $REPO_PATH/appdata/crowdsec:/var/lib/crowdsec/data
      - $REPO_PATH/configs/crowdsec:/etc/crowdsec
      - $REPO_PATH/configs/crowdsec/passwd:/etc/passwd:ro
      - $REPO_PATH/configs/crowdsec/group:/etc/group:ro
      ## Secrets
      - $REPO_PATH/secrets/crowdsec/local_api_credentials.yaml:/etc/crowdsec/local_api_credentials.yaml
      - $REPO_PATH/secrets/crowdsec/online_api_credentials.yaml:/etc/crowdsec/online_api_credentials.yaml
    environment:
      USER: crowdsec:crowdsec
      GID: $PGID
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/sshd"
      CUSTOM_HOSTNAME: $MY_HOSTNAME
      # DISABLE_LOCAL_API: "true" # Only after successfully registering and validating remote agent below.
      # # For the following, check local_api_credentials.yaml after cscli lapi register (secondary machine) and cscli machine validate (on primary machine)
      # AGENT_USERNAME: $CROWDSEC_AGENT_USERNAME
      # AGENT_PASSWORD: $CROWDSEC_AGENT_PASSWORD
      # LOCAL_API_URL: $CROWDSEC_LOCAL_API_URL
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "crowdsec"
      homepage.icon: "crowdsec.png"
      homepage.target: "_blank"
      homepage.description: "Open-source & collaborative security IPS"
      ####### GLANCE #######
      glance.name: "crowdsec"
      glance.icon: "sh:crowdsec"
      glance.description: "Open-source & collaborative security IPS"
