services:
  czkawka:
    container_name: czkawka
    image: jlesage/czkawka:latest
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/czkawka:/config:rw
      - $DIR_PHOTOS/Pictures:/storage:rw
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: 1
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.czkawka-rtr.entrypoints: "websecure"
      traefik.http.routers.czkawka-rtr.rule: "Host(`czkawka.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.czkawka-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.czkawka-rtr.service: "czkawka-svc"
      traefik.http.services.czkawka-svc.loadbalancer.server.port: "5800"
      ####### TINYAUTH #######
      tinyauth.apps.czkawka.config.domain: "czkawka.$DOMAINNAME"
      tinyauth.apps.czkawka.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Czkawka"
      homepage.icon: "czkawka.svg"
      homepage.href: "https://czkawka.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Multi functional app to find duplicates, empty folders, similar images etc."
