services:
  darktable:
    container_name: darktable
    image: lscr.io/linuxserver/darktable:25.4.1-2-ls224@sha256:d2ea6555c5537bf2e917abbada3256921758d758128d0973032bf1340cba5c65
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DIR_PHOTOS:/photos
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.darktable-rtr.entrypoints: "websecure"
      traefik.http.routers.darktable-rtr.rule: "Host(`darktable.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.darktable-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.darktable-rtr.service: "darktable-svc"
      traefik.http.services.darktable-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.darktable.config.domain: "darktable.$DOMAINNAME"
      tinyauth.apps.darktable.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Darktable"
      homepage.icon: "darktable.svg"
      homepage.href: "https://darktable.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Photo Editing App"
    profiles:
      - desktop_apps
