services:
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      TZ: $TZ
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      CRON: 0 0 3 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1