# NOTE: For docker-config auth: echo -n "username:password" | base64
services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.70.0
    container_name: doco-cd
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - forgejo
    networks:
      - t3_proxy
      - socket_proxy
    expose:
      - 80    # API/Webhook endpoint
      - 9120  # Prometheus metrics
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/data/doco-cd:/data
      ## Optional: To pull from your private Forgejo registry
      - $REPO_PATH/configs/doco-cd/docker-config.json:/root/.docker/config.json:ro
    environment:
      TZ: $TZ
      API_SECRET: $DOCO_CD_API_SECRET
      LOG_LEVEL: INFO
      DOCKER_HOST: tcp://docker-socket-proxy-exec:2375
      GIT_ACCESS_TOKEN: $FORGEJO_REPO_READ_TOKEN
      WEBHOOK_SECRET: $DOCO_CD_WEBHOOK_SECRET
      APPRISE_API_URL: https://apprise-api.home.$BASE_DOMAINNAME/notify
      APPRISE_NOTIFY_LEVEL: success
    healthcheck:
      test: [ "CMD", "/doco-cd", "healthcheck" ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.doco-cd-rtr.entrypoints: "websecure"
      traefik.http.routers.doco-cd-rtr.rule: "Host(`doco-cd.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.doco-cd-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.doco-cd-rtr.service: "doco-cd-svc"
      traefik.http.services.doco-cd-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.doco-cd.config.domain: "doco-cd.$DOMAINNAME"
      tinyauth.apps.doco-cd.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "doco-cd"
      homepage.icon: "doco-cd.png"
      homepage.href: "https://doco-cd.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Docker Compose Continuous Deployment"
      ####### GLANCE #######
      glance.name: "doco-cd"
      glance.icon: "sh:doco-cd"
      glance.url: "https://doco-cd.$DOMAINNAME"
      glance.description: "Docker Compose Continuous Deployment"
