# NOTE: For docker-config auth: echo -n "username:password" | base64
services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.105.0@sha256:27e14cc52bc79f8660c321dd4552d780b180fe0d7fe1c9233e4908a5c9f80838
    container_name: doco-cd
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - forgejo
    networks:
      - t3_proxy
      - socket_proxy_exec
    expose:
      - 80 # API/Webhook endpoint
      - 9120 # Prometheus metrics
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,uid=$PUID,gid=$PGID,mode=1777
      - /run:rw,noexec,nosuid,nodev,size=32m,uid=$PUID,gid=$PGID,mode=775
      - $HOME:rw,noexec,nosuid,nodev,size=64m,uid=$PUID,gid=$PGID,mode=0755
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/doco-cd:/data
      ## Optional: To pull from your private Forgejo registry
      - $REPO_PATH/configs/doco-cd/docker-config.json:/data/.docker/config.json:ro
    environment:
      TZ: $TZ
      DATA_MOUNT_PATH: /data # TODO: Make Internal and external paths identical
      API_SECRET: $DOCO_CD_API_SECRET
      LOG_LEVEL: INFO
      DOCKER_CONFIG: /data/.docker
      DOCKER_HOST: tcp://docker-socket-proxy-exec:2375
      GIT_ACCESS_TOKEN: $FORGEJO_REPO_READ_TOKEN
      WEBHOOK_SECRET: $DOCO_CD_WEBHOOK_SECRET
      APPRISE_API_URL: https://apprise-api.home.$BASE_DOMAINNAME/notify
      APPRISE_NOTIFY_LEVEL: success
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.doco-cd-rtr.entrypoints: "websecure"
      traefik.http.routers.doco-cd-rtr.rule: "Host(`doco-cd.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.doco-cd-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.doco-cd-rtr.service: "doco-cd-svc"
      traefik.http.services.doco-cd-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "doco-cd"
      homepage.icon: "doco-cd.png"
      homepage.href: "https://doco-cd.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Docker Compose Continuous Deployment"
      ####### GLANCE #######
      glance.name: "doco-cd"
      glance.icon: "sh:doco-cd"
      glance.url: "https://doco-cd.$DOMAINNAME"
      glance.description: "Docker Compose Continuous Deployment"
