services:
  dufs:
    image: sigoden/dufs:v0.46.0@sha256:8dd3b750015734703e64b55641fb7d2254c112e0ff3967074766177dc15dc982
    container_name: dufs
    restart: $RESTART_POLICY_MEDIA
    command: /data -A
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/dufs:/data
      - $USERDIR:/data/Home
      # - $REPO_PATH/appdata/dufs/Apps/Books:/data/Apps/Books # NOTE: For syncing MoonReader with webdav
      # - $DIR_HARDDISKROOT:/data/Harddisk
    environment:
      DUFS_BIND: 0.0.0.0
      DUFS_PORT: 5000
    # healthcheck:
    #   test: "curl http://127.0.0.1:5000/__dufs__/health" # NOTE: Not working since there is no curl
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.dufs-rtr.entrypoints: "websecure"
      traefik.http.routers.dufs-rtr.rule: "Host(`dufs.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.dufs-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.dufs-rtr.service: "dufs-svc"
      traefik.http.services.dufs-svc.loadbalancer.server.port: "5000"
      ####### TINYAUTH #######
      tinyauth.apps.dufs.config.domain: "dufs.$DOMAINNAME"
      tinyauth.apps.dufs.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Dufs"
      homepage.icon: "files.svg"
      homepage.href: "https://dufs.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A file server that supports static serving, WEBDAV"
      ####### GLANCE #######
      glance.name: Dufs
      glance.icon: sh:dufs
      glance.url: https://dufs.$DOMAINNAME
      glance.description: A file server that supports static serving, WEBDAV
