services:
  dufs:
    container_name: dufs
    image: sigoden/dufs:v0.45.0@sha256:9b45a406b019921c7d2a512784a8652fc23a83c5598bf0ddc81d3c130c623f31
    restart: $RESTART_POLICY_MEDIA
    command: /data -A
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/dufs:/data
      - $USERDIR:/data/Home
      # - $REPO_PATH/appdata/dufs/Apps/Books:/data/Apps/Books # NOTE: For syncing MoonReader with webdav
      # - $DIR_HARDDISKROOT:/data/Harddisk
    # healthcheck:
    #   test: "curl http://127.0.0.1:5000/__dufs__/health" # NOTE: Not working since there is no curl
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    environment:
      DUFS_BIND: 0.0.0.0
      DUFS_PORT: 5000
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.dufs-rtr.entrypoints: "websecure"
      traefik.http.routers.dufs-rtr.rule: "Host(`dufs.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.dufs-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.dufs-rtr.service: "dufs-svc"
      traefik.http.services.dufs-svc.loadbalancer.server.port: "5000"
      ####### TINYAUTH #######
      tinyauth.apps.dufs.config.domain: "dufs.$DOMAINNAME"
      tinyauth.apps.dufs.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Dufs"
      homepage.icon: "files.svg"
      homepage.href: "https://dufs.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A file server that supports static serving, WEBDAV"
