services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/duplicati:/config
      - $DIR_BACKUP:/backups
      - $REPO_PATH:/source
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # CLI_ARGS:
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.duplicati-rtr.entrypoints: "websecure"
      traefik.http.routers.duplicati-rtr.rule: "Host(`duplicati.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.duplicati-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.duplicati-rtr.service: "duplicati-svc"
      traefik.http.services.duplicati-svc.loadbalancer.server.port: "8200"
      ####### TINYAUTH #######
      tinyauth.apps.duplicati.config.domain: "duplicati.$DOMAINNAME"
      tinyauth.apps.duplicati.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Duplicati"
      homepage.icon: "duplicati.svg"
      homepage.href: "https://duplicati.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Store securely encrypted backups in the cloud!"
