services:
  enclosed:
    container_name: enclosed
    image: corentinth/enclosed:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.enclosed.entrypoints: "websecure"
      traefik.http.routers.enclosed.rule: "Host(`enclosed.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.enclosed.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.enclosed.service: "logseq-svc"
      traefik.http.services.logseq-svc.loadbalancer.server.port: "8787"
      ####### TINYAUTH #######
      tinyauth.apps.enclosed.config.domain: "enclosed.$DOMAINNAME"
      tinyauth.apps.enclosed.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "Enclosed"
      homepage.icon: "enclosed.svg"
      homepage.href: "https://enclosed.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Minimalistic web app designed for sending private and secure notes."
    profiles:
      - others
