services:
  filestash-wopi-server:
    image: collabora/code:24.04.10.2.1
    container_name: filestash-wopi-server
    restart: $RESTART_POLICY_MEDIA
    user: root
    command:
      - /bin/bash
      - -c
      - |
        curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
        /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
    profiles:
      - not-used
      # - media
      # - filestash
    networks:
      - t3_proxy
    expose:
      - "9980"
    security_opt:
      - no-new-privileges:true
    environment:
      extra_params: "--o:ssl.enable=false"
      aliasgroup1: "https://.*:443"

  # NOTE: Selfhosted Version: v0.6.20260226
  # NOTE: Enterprise Version: v0.6.20260105
  # NOTE: filestash.bin should be executable (chmod +x)
  filestash:
    image: machines/filestash:latest
    container_name: filestash
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - filestash
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/filestash/filestash.bin:/app/filestash
      - $REPO_PATH/data/filestash:/app/data/state/
    environment:
      APPLICATION_URL: filestash.$DOMAINNAME
      ADMIN_CONSOLE: $FILESTASH_ADMIN_PASSWORD_BCRYPT
      CANARY: false
      # OFFICE_URL: http://filestash-wopi-server:9980
      # OFFICE_FILESTASH_URL: http://app:8334
      # OFFICE_REWRITE_URL: http://127.0.0.1:9980
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.filestash-rtr.entrypoints: "websecure"
      traefik.http.routers.filestash-rtr.rule: "Host(`filestash.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.filestash-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.filestash-rtr.service: "filestash-svc"
      traefik.http.services.filestash-svc.loadbalancer.server.port: "8334"
      ####### TINYAUTH #######
      tinyauth.apps.filestash.config.domain: "filestash.$DOMAINNAME"
      tinyauth.apps.filestash.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "filestash"
      homepage.icon: "filestash.png"
      homepage.href: "https://filestash.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "description"
      ####### GLANCE #######
      glance.name: "filestash"
      glance.icon: "sh:filestash"
      glance.url: "https://filestash.$DOMAINNAME"
      glance.description: "description"
