services:
  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    shm_size: "1gb"
    profiles:
      - desktop_apps
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Firefox
      PIXELFLUX_WAYLAND: true
      # DRINODE: /dev/dri/renderD128 # NOTE: Permission denied
      DRI_NODE: /dev/dri/renderD128
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:3000 || exit 1"]
      start_period: 15s
      interval: 1m
      timeout: 5s
      retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.firefox-rtr.entrypoints: "websecure"
      traefik.http.routers.firefox-rtr.rule: "Host(`firefox.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.firefox-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.firefox-rtr.service: "firefox-svc"
      traefik.http.services.firefox-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.firefox.config.domain: "firefox.$DOMAINNAME"
      tinyauth.apps.firefox.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Firefox"
      homepage.icon: "firefox.svg"
      homepage.href: "https://firefox.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Firefox - Containerized"
    # For Nvidia Zero Copy Rendering
    group_add:
      - "44" # video
      - "992" # render
    devices:
      - /dev/dri:/dev/dri
      # - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics, display]