networks:
  forgejo_ci:
    internal: true
  forgejo_dind_egress:

services:
  forgejo-db:
    image: postgres:16.4
    container_name: forgejo-db
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - forgejo
    environment:
      PGDATA: /pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - t3_proxy
    expose:
      - "5432"
    volumes:
      - $REPO_PATH/data/forgejo-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  forgejo-dind:
    image: docker:29-dind
    container_name: forgejo-dind
    privileged: true
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - forgejo
    networks:
      - forgejo_dind_egress
      - forgejo_ci
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    healthcheck:
      test: ["CMD-SHELL", "docker -H tcp://127.0.0.1:2375 info > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  # NOTE: Create `$REPO_PATH/data/forgejo/runner` dir with current user beforehand.
  # NOTE: First run without the daemon command to initialize the runner, then use the daemon command one.
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:12
    container_name: forgejo-runner
    user: $PUID:$PGID
    restart: $RESTART_POLICY_PROGRAMMING
    # command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon --config /config.yml"'
    security_opt:
      - no-new-privileges:true
    depends_on:
      forgejo-dind:
        condition: service_healthy
    profiles:
      - programming
      - forgejo
    networks:
      - t3_proxy
      - forgejo_ci
    environment:
      DOCKER_HOST: tcp://forgejo-dind:2375
    volumes:
      - $REPO_PATH/data/forgejo/runner:/data
      - $REPO_PATH/configs/forgejo/runner/config.yml:/config.yml

  # NOTE: Create `$REPO_PATH/data/forgejo/gitea` and `$REPO_PATH/data/forgejo/conf` dirs with current user beforehand.
  # NOTE: Configuration is located in: $REPO_PATH/data/forgejo/gitea/custom/conf/app.ini
  forgejo:
    image: codeberg.org/forgejo/forgejo:14-rootless
    container_name: forgejo
    user: $PUID:$PGID
    cpus: "1.5"
    mem_reservation: "512M"
    mem_limit: "2G"
    restart: $RESTART_POLICY_PROGRAMMING
    depends_on:
      forgejo-db:
        condition: service_healthy
      forgejo-runner:
        condition: service_started
    profiles:
      - programming
      - forgejo
    networks:
      - t3_proxy
    ports:
      - "2222:2222"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/data/forgejo/gitea:/var/lib/gitea
      - $REPO_PATH/data/forgejo/conf:/etc/gitea
    environment:
      USER_UID: $PUID
      USER_GID: $PGID
      TZ: $TZ
      FORGEJO__server__ROOT_URL: https://git.$DOMAINNAME
      FORGEJO__server__DOMAIN: git.$DOMAINNAME
      FORGEJO__server__SSH_DOMAIN: git.$DOMAINNAME
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo-db:5432
      FORGEJO__database__NAME: postgres
      FORGEJO__database__USER: postgres
      FORGEJO__database__PASSWD: postgres
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.forgejo-rtr.entrypoints: "websecure"
      traefik.http.routers.forgejo-rtr.rule: "Host(`git.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.forgejo-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.forgejo-rtr.service: "forgejo-svc"
      traefik.http.services.forgejo-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.forgejo.config.domain: "git.$DOMAINNAME"
      tinyauth.apps.forgejo.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "forgejo"
      homepage.icon: "forgejo.png"
      homepage.href: "https://git.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Self-hosted Git service"
      ####### GLANCE #######
      glance.name: "forgejo"
      glance.icon: "sh:forgejo"
      glance.url: "https://git.$DOMAINNAME"
      glance.description: "Self-hosted Git service"
