networks:
  forgejo_ci:
    internal: true
  forgejo_dind_egress:

services:
  forgejo-db:
    image: postgres:18.3@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    container_name: forgejo-db
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - custom-user
      - programming
      - forgejo
    networks:
      - t3_proxy
    expose:
      - "5432"
    user: "999:999"
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/data/forgejo/db:/pgdata
    environment:
      PGDATA: /pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  # NOTE: Create `$REPO_PATH/data/forgejo/gitea` and `$REPO_PATH/data/forgejo/conf` dirs with current user beforehand.
  # NOTE: Configuration is located in: $REPO_PATH/data/forgejo/gitea/custom/conf/app.ini
  forgejo:
    image: codeberg.org/forgejo/forgejo:14-rootless@sha256:bca6943cdd8a50f5befaf1d654bec32c9a3b6da400d23a77a829bd41f88a7263
    container_name: forgejo
    user: $PUID:$PGID
    cpus: "1.5"
    mem_reservation: "512M"
    mem_limit: "2G"
    restart: $RESTART_POLICY_PROGRAMMING
    depends_on:
      forgejo-db:
        condition: service_healthy
      # forgejo-runner:
      #   condition: service_started
    profiles:
      - programming
      - forgejo
    networks:
      - t3_proxy
    ports:
      - "2222:2222"
    read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/data/forgejo/gitea:/var/lib/gitea
      - $REPO_PATH/data/forgejo/conf:/etc/gitea
    environment:
      USER_UID: $PUID
      USER_GID: $PGID
      TZ: $TZ
      FORGEJO__server__ROOT_URL: https://git.$DOMAINNAME
      FORGEJO__server__DOMAIN: git.$DOMAINNAME
      FORGEJO__server__SSH_DOMAIN: git.$DOMAINNAME
      FORGEJO__server__LANDING_PAGE: login
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: forgejo-db:5432
      FORGEJO__database__NAME: postgres
      FORGEJO__database__USER: postgres
      FORGEJO__database__PASSWD: postgres
      FORGEJO__service__DISABLE_REGISTRATION: false
      FORGEJO__service__REQUIRE_SIGNIN_VIEW: false
      FORGEJO__service__ENABLE_INTERNAL_SIGNIN: false
      FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      FORGEJO__openid__ENABLE_OPENID_SIGNIN: false
      FORGEJO__webhook__ALLOWED_HOST_LIST: doco-cd.$DOMAINNAME
      FORGEJO__cron.cleanup_packages__SCHEDULE: "@every 6h"

    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.forgejo-rtr.entrypoints: "websecure"
      traefik.http.routers.forgejo-rtr.rule: "Host(`git.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.forgejo-rtr.middlewares: "chain-no-auth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.forgejo-rtr.service: "forgejo-svc"
      traefik.http.services.forgejo-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.forgejo.config.domain: "git.$DOMAINNAME"
      tinyauth.apps.forgejo.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "forgejo"
      homepage.icon: "forgejo.png"
      homepage.href: "https://git.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Self-hosted Git service"
      ####### GLANCE #######
      glance.name: "forgejo"
      glance.icon: "sh:forgejo"
      glance.url: "https://git.$DOMAINNAME"
      glance.description: "Self-hosted Git service"
