services:
  gatus-db:
    image: postgres:16.13@sha256:86f4d9ad58cb9023f6d36ac428555680a4aac6daccce4d3e2b0768c15b1bb092
    container_name: gatus-db
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - custom-user
      - not-used
      # - monitoring
      - gatus
    environment:
      PGDATA: /pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - t3_proxy
    expose:
      - "5432"
    user: "999:999"
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/data/gatus-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  gatus:
    image: ghcr.io/twin/gatus:stable@sha256:21609f31be8c4e680ce3004b24276305666239c99aff58391503f3fb6142f39d
    container_name: gatus
    restart: $RESTART_POLICY_MAINTENANCE
    # depends_on:
    #   gatus-db:
    #     condition: service_healthy
    profiles:
      - monitoring
      - gatus
    networks:
      - t3_proxy
      # - socket_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/gatus:/config
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DB_HOST: gatus-db
      DB_PORT: 5432
      TITLE: $GATUS_TITLE
      DOMAINNAME: $DOMAINNAME
      GOTIFY_NOTIFICATION_TOKEN: $GOTIFY_GATUS_NOTIFICATION_TOKEN
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.gatus-rtr.entrypoints: "websecure"
      traefik.http.routers.gatus-rtr.rule: "Host(`gatus.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.gatus-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.gatus-rtr.service: "gatus-svc"
      traefik.http.services.gatus-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.gatus.config.domain: "gatus.$DOMAINNAME"
      tinyauth.apps.gatus.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "Gatus"
      homepage.icon: "gatus.svg"
      homepage.href: "https://gatus.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Automated developer-oriented status page"
      homepage.widget.type: "gatus"
      homepage.widget.url: "http://gatus:8080"
      ####### GLANCE #######
      glance.name: "gatus"
      glance.icon: "sh:gatus"
      glance.url: "https://gatus.$DOMAINNAME"
      glance.description: "Automated developer-oriented status page"
