services:
  # FIXME: To show wifi network usage, we need `network_mode: host`. But this way, we can't use traefik.
  # FIXME: Find a way to show GPU stats
  glances:
    # image: nicolargo/glances:ubuntu-latest-full
    image: nicolargo/glances:dev
    container_name: glances
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
    # network_mode: host
    networks:
      - t3_proxy
      - socket_proxy
    # - hostnet
    privileged: true
    # security_opt:
    #   - no-new-privileges:true
    pid: host
    volumes:
      # - $REPO_PATH/configs/glances/glances.conf:/glances/conf/glances.conf # Use this if you want to add a glances.conf file
      - $USERDIR:/data/home:ro
    environment:
      TZ: "${TZ}"
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      # GLANCES_OPT: "-w" # "-C /glances/conf/glances.conf --export influxdb"
      GLANCES_OPT: "-C /glances/conf/glances.conf -w"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.glances-rtr.entrypoints: "websecure"
      traefik.http.routers.glances-rtr.rule: "Host(`glances.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.glances-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.glances-rtr.service: "glances-svc"
      traefik.http.services.glances-svc.loadbalancer.server.port: "61208"
      ####### TINYAUTH #######
      tinyauth.apps.glances.config.domain: "glances.$DOMAINNAME"
      tinyauth.apps.glances.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "Glances"
      homepage.icon: "glances.svg"
      homepage.href: "https://glances.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "System Monitor"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]