services:
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    depends_on:
      - prometheus
    restart: $RESTART_POLICY_MAINTENANCE
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - "$GRAFANA_PORT:3000"
    user: "0"
    volumes:
      - $REPO_PATH/appdata/grafana:/var/lib/grafana
      - $REPO_PATH/configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $REPO_PATH/configs/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_PLUGINS_PREINSTALL: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_LOG_LEVEL: "debug"
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role==manager
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.grafana-rtr.entrypoints: "websecure"
      traefik.http.routers.grafana-rtr.rule: "Host(`grafana.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.grafana-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.grafana-rtr.service: "grafana-svc"
      traefik.http.services.grafana-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.grafana.config.domain: "grafana.$DOMAINNAME"
      tinyauth.apps.grafana.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "Grafana"
      homepage.icon: "grafana.svg"
      homepage.href: "https://grafana.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Observability and Data Visualization Platform"
    profiles:
      - monitoring
