services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
    container_name: homepage
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy_read
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,uid=$PUID,gid=$PGID,mode=1777
      - /run:rw,noexec,nosuid,nodev,size=32m,uid=$PUID,gid=$PGID,mode=775
      - /app/.next/cache:rw,noexec,nosuid,nodev,size=128m,uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/configs/homepage:/app/config
      - $REPO_PATH/configs/homepage/icons:/app/public/icons
      - $REPO_PATH/logs/homepage:/app/config/logs
      # - /mnt/d:/mnt/d  # NOTE: Need for Disk usage widget
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_MY_HOSTNAME: $MY_HOSTNAME
      HOMEPAGE_ALLOWED_HOSTS: homepage.$DOMAINNAME
      HOMEPAGE_VAR_BASE_DOMAINNAME: $BASE_DOMAINNAME
      HOMEPAGE_VAR_DOMAINNAME: $DOMAINNAME
      # HOMEPAGE_VAR_CALENDAR_GMAIL_ICAL_SECRET_ADDRESS: $CALENDAR_GMAIL_ICAL_SECRET_ADDRESS
      # HOMEPAGE_VAR_BESZEL_EMAIL: $BESZEL_EMAIL
      # HOMEPAGE_VAR_BESZEL_PASSWORD: $BESZEL_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:$${PORT:-3000}/api/healthcheck || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 45s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homepage-rtr.entrypoints: "websecure"
      traefik.http.routers.homepage-rtr.rule: "Host(`homepage.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homepage-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homepage-rtr.service: "homepage-svc"
      traefik.http.services.homepage-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.homepage.config.domain: "homepage.$DOMAINNAME"
      tinyauth.apps.homepage.ip.bypass: "$LOCAL_IPS"
      ####### GLANCE #######
      glance.name: "homepage"
      glance.icon: "si:homepage"
      glance.url: "https://homepage.$DOMAINNAME"
      glance.description: "Alternative homepage"
