services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    container_name: homepage
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /app/.next/cache
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/homepage:/app/config
      - $REPO_PATH/configs/homepage/icons:/app/public/icons
      - $REPO_PATH/logs/homepage:/app/config/logs
      # - /mnt/d:/mnt/d  # NOTE: Need for Disk usage widget
    environment:
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_MY_HOSTNAME: $MY_HOSTNAME
      HOMEPAGE_ALLOWED_HOSTS: homepage.$DOMAINNAME
      HOMEPAGE_VAR_BASE_DOMAINNAME: $BASE_DOMAINNAME
      HOMEPAGE_VAR_DOMAINNAME: $DOMAINNAME
      # HOMEPAGE_VAR_CALENDAR_GMAIL_ICAL_SECRET_ADDRESS: $CALENDAR_GMAIL_ICAL_SECRET_ADDRESS
      # HOMEPAGE_VAR_BESZEL_EMAIL: $BESZEL_EMAIL
      # HOMEPAGE_VAR_BESZEL_PASSWORD: $BESZEL_PASSWORD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homepage-rtr.entrypoints: "websecure"
      traefik.http.routers.homepage-rtr.rule: "Host(`homepage.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homepage-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homepage-rtr.service: "homepage-svc"
      traefik.http.services.homepage-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.homepage.config.domain: "homepage.$DOMAINNAME"
      tinyauth.apps.homepage.ip.bypass: "$LOCAL_IPS"
      ####### GLANCE #######
      glance.name: "homepage"
      glance.icon: "si:homepage"
      glance.url: "https://homepage.$DOMAINNAME"
      glance.description: "Alternative homepage"
