services:
  homeserver-api-redis:
    image: redis:8
    container_name: homeserver-api-redis
    restart: $RESTART_POLICY_OTHERS
    hostname: "homeserver-api-redis"
    command: redis-server --requirepass "${HOMESERVER_API_REDIS_PASSWORD}"
    profiles:
      - others
      - homeserver-api
    networks:
      - t3_proxy
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${HOMESERVER_API_REDIS_PASSWORD}", "ping"]
      interval: 1s
      timeout: 3s
      retries: 50

  homeserver-api-rabbitmq:
    image: rabbitmq:4-management
    container_name: homeserver-api-rabbitmq
    restart: $RESTART_POLICY_OTHERS
    hostname: "homeserver-api-rabbitmq"
    profiles:
      - others
      - homeserver-api
    networks:
      - t3_proxy
    expose:
      - "5672" # RabbitMQ AMQP port
      - "15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: $HOMESERVER_API_RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $HOMESERVER_API_RABBITMQ_PASSWORD
      RABBITMQ_VHOST: "/"
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: "2GB"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homeserver-api-rabbitmq-rtr.entrypoints: "websecure"
      traefik.http.routers.homeserver-api-rabbitmq-rtr.rule: "Host(`api-rabbitmq.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homeserver-api-rabbitmq-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homeserver-api-rabbitmq-rtr.service: "homeserver-api-rabbitmq-svc"
      traefik.http.services.homeserver-api-rabbitmq-svc.loadbalancer.server.port: "15672"
      ####### TINYAUTH #######
      tinyauth.apps.api-rabbitmq.config.domain: "api-rabbitmq.$DOMAINNAME"
      tinyauth.apps.api-rabbitmq.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-rabbitmq"
      homepage.icon: "rabbitmq.png"
      homepage.href: "https://api-rabbitmq.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Homeserver API RabbitMQ"

  homeserver-api-head:
    image: homeserver-api:latest
    container_name: homeserver-api-head
    restart: $RESTART_POLICY_OTHERS
    tty: true
    depends_on:
      - homeserver-api-redis
      - homeserver-api-rabbitmq
    build:
      context: $DIR_MYREPOS/homeserver-api
      dockerfile: $DIR_MYREPOS/homeserver-api/docker/Dockerfile
      target: development
    profiles:
      - others
      - homeserver-api
      - custom-build
    networks:
      - t3_proxy
    expose:
      - "8000" # API port
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    command: ["uv", "run", "--module", "app.__main__"]
    volumes:
      - $DIR_MYREPOS/homeserver-api/app:/app/app
    env_file:
      - $DIR_MYREPOS/homeserver-api/.env
    environment:
      - INSTANCE_TYPE=API
      - HOST=0.0.0.0
      - PORT=8000
      - RABBITMQ_HOST=homeserver-api-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=homeserver-api-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$HOMESERVER_API_REDIS_PASSWORD
      - OTEL_SERVICE_NAME=homeserver-api-head
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector-agent:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=apps,service.instance.id=${MY_HOSTNAME:-unknown},deployment.environment.name=${OTEL_DEPLOYMENT_ENVIRONMENT:-production}
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.homeserver-api-head-rtr.entrypoints: "websecure"
      traefik.http.routers.homeserver-api-head-rtr.rule: "Host(`api.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.homeserver-api-head-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.homeserver-api-head-rtr.service: "homeserver-api-head-svc"
      traefik.http.services.homeserver-api-head-svc.loadbalancer.server.port: "8000"
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-head"
      homepage.icon: "homeserver-api.png"
      homepage.href: "https://api.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Homeserver API Head"

  homeserver-api-worker:
    image: homeserver-api:latest
    container_name: homeserver-api-worker
    restart: $RESTART_POLICY_OTHERS
    tty: true
    depends_on:
      - homeserver-api-redis
      - homeserver-api-rabbitmq
    build:
      context: $DIR_MYREPOS/homeserver-api
      dockerfile: $DIR_MYREPOS/homeserver-api/docker/Dockerfile
      target: development
    profiles:
      - others
      - homeserver-api
      - custom-build
    networks:
      - t3_proxy
    # command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    command:
      - "uv"
      - "run"
      - "--module"
      - "taskiq"
      - "worker"
      - "app.worker.broker:broker"
      - "--use-process-pool"
      - "--workers"
      - "5"
      - "-fsd"
      - "-tp"
      - "[app/worker/tasks/*.py]"
    # <<: *gpu-all-deploy
    volumes:
      - $DIR_MYREPOS/homeserver-api/app:/app/app
    env_file:
      - $DIR_MYREPOS/homeserver-api/.env
    environment:
      - INSTANCE_TYPE=WORKER
      - RABBITMQ_HOST=homeserver-api-rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=homeserver-api-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$HOMESERVER_API_REDIS_PASSWORD
      - OTEL_SERVICE_NAME=homeserver-api-worker
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector-agent:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=apps,service.instance.id=${MY_HOSTNAME:-unknown},deployment.environment.name=${OTEL_DEPLOYMENT_ENVIRONMENT:-production}
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Others"
      homepage.name: "homeserver-api-worker"
      homepage.icon: "homeserver-api.png"
      homepage.target: "_blank"
      homepage.description: "Homeserver API Worker"
