services:
  # Change URL in immich settings -> admin/system-settings?isOpen=machine-learning
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5-openvino@sha256:71cd5a681823c4b818f4b24b3f05816eccc3d085559e7615f695bde77e64f1f2
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    restart: $RESTART_POLICY_MEDIA
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    ports:
      - "3003:3003"
    healthcheck:
      disable: false
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $REPO_PATH/appdata/immich-ml/model-cache:/cache
    environment:
      MACHINE_LEARNING_CACHE_FOLDER: /cache
      OMP_NUM_THREADS: 8
