# NOTE: Change URL in immich settings -> admin/system-settings?isOpen=machine-learning
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.5-cuda@sha256:304142175e345f0155d7642f637cfdceae60e89075ff03938cb2886d52c65a62
    container_name: immich-machine-learning
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    ports:
      - "3003:3003"
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 2G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/immich-ml/model-cache:/cache
    environment:
      MACHINE_LEARNING_CACHE_FOLDER: /cache
    healthcheck:
      disable: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]
