# TODO: Harden
# Env variables: https://immich.app/docs/install/environment-variables
services:
  immich-redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    healthcheck:
      test: redis-cli ping || exit 1

  immich-postgres:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0@sha256:1a078b237c1d9b420b0ee59147386b4aa60d3a07a8e6a402fc84a57e41b043a4
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/immich-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $IMMICH_DB_PASSWORD
      POSTGRES_USER: $IMMICH_DB_USERNAME
      POSTGRES_DB: $IMMICH_DB_DATABASE_NAME
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PG_DATA: /var/lib/postgresql/data
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - immich-redis
      - immich-postgres
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    healthcheck:
      disable: false
    volumes:
      - $IMMICH_UPLOAD_LOCATION:/usr/src/app/upload
      - $DIR_PHOTOS/Pictures:/mnt/media/Photos/Pictures
      - $DIR_PHOTOS/Videos:/mnt/media/Photos/Videos:ro
      # - $DIR_PHOTOS/Pictures:/mnt/media/Photos/Pictures
      # - $DIR_PHOTOS/Videos:/mnt/media/Photos/Videos
    environment:
      UPLOAD_LOCATION: $IMMICH_UPLOAD_LOCATION
      IMMICH_LOG_LEVEL: ${IMMICH_LOG_LEVEL:-error}
      REDIS_HOSTNAME: $IMMICH_REDIS_HOSTNAME
      DB_HOSTNAME: $IMMICH_DB_HOSTNAME
      DB_USERNAME: $IMMICH_DB_USERNAME
      DB_PASSWORD: $IMMICH_DB_PASSWORD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.immich-server-rtr.entrypoints: "websecure"
      traefik.http.routers.immich-server-rtr.rule: "Host(`photos.$DOMAINNAME`)"
      # - "traefik.http.routers.immich-server-rtr.rule=Host(`photos.$DOMAINNAME`) && Pathprefix(`/api`)"
      ## Middlewares
      traefik.http.routers.immich-server-rtr.middlewares: "chain-tinyauth-relaxed@file" # NOTE: relaxed needed for `Map` tab to work
      # traefik.http.routers.immich-server-rtr.middlewares: "chain-no-auth-relaxed@file" # NOTE: relaxed needed for `Map` tab to work
      # - "traefik.http.routers.immich-server-rtr.middlewares=add-api"
      # - "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
      ## HTTP Services
      traefik.http.routers.immich-server-rtr.service: "immich-server-svc"
      traefik.http.services.immich-server-svc.loadbalancer.server.port: "2283"
      ####### TINYAUTH #######
      tinyauth.apps.photos.config.domain: "photos.$DOMAINNAME"
      tinyauth.apps.photos.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Immich"
      homepage.icon: "immich.svg"
      homepage.href: "https://photos.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Selfhosted Photo App"
      homepage.widget.type: "immich"
      homepage.widget.url: "http://immich-server:2283"
      homepage.widget.key: "$IMMICH_API_KEY"
      homepage.widget.version: "2"

  ##############################################
  # https://github.com/Salvoxia/immich-folder-album-creator
  immich-folder-album-creator:
    container_name: immich-folder-album-creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: "no"
    depends_on:
      - immich-server
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY: $IMMICH_API_KEY
      ROOT_PATH: /mnt/media/Photos/Pictures
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Istanbul
      ALBUM_LEVELS: 1
      LOG_LEVEL: INFO
      SYNC_MODE: "2" # Remove offline assets and delete empty albums after each run
      # RUN_IMMEDIATELY: "true" # Run the script immediately after start

  # NOTE: On Immich -> Admin -> Settings -> Server Settings -> External Domain
  immich-public-proxy:
    container_name: immich-public-proxy
    image: alangrainger/immich-public-proxy:latest
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - immich-server
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
    ports:
      - "1003:3000"
    environment:
      IMMICH_URL: http://immich-server:2283
    # healthcheck:
    #   test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
    #   start_period: 10s
    #   timeout: 5s
    volumes:
      - $REPO_PATH/configs/immich-public-proxy/config.json:/app/config.json:ro
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Immich-Public-Proxy"
      homepage.icon: "immich.svg"
