# Official compose: https://github.com/immich-app/immich/blob/main/docker/docker-compose.rootless.yml
# Env variables: https://immich.app/docs/install/environment-variables

networks:
  immich_backend:

services:
  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:8436e10bc65c94886a91d4415b6a6dfa9cb5a306fb3b996e5bb67cd2b4854193
    container_name: immich-redis
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - immich
    networks:
      - immich_backend
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - $REPO_PATH/appdata/immich-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 10s

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-postgres
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - immich
    networks:
      - immich_backend
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    shm_size: 128mb
    pids_limit: 512
    cpus: "2.0"
    mem_limit: "2G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/immich-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $IMMICH_DB_PASSWORD
      POSTGRES_USER: $IMMICH_DB_USERNAME
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PG_DATA: /var/lib/postgresql/data
      DB_STORAGE_TYPE: "SSD" # Change to "HDD" if your database isn't stored on SSDs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m

  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
    container_name: immich-server
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - immich-redis
      - immich-postgres
    profiles:
      - media
      - immich
    networks:
      - t3_proxy
      - immich_backend
    expose:
      - 2283
    # NOTE: For dell machine only
    # ports:
    #   - "2283:2283"
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    pids_limit: 1024
    cpus: "4.0"
    mem_limit: "6G"
    ulimits:
      nofile:
        soft: 8192
        hard: 16384
    volumes:
      - $IMMICH_THUMBS_PATH:/data/thumbs
      - $IMMICH_DATA_PATH:/data
      - $DIR_PHOTOS/Pictures:/mnt/media/Photos/Pictures
      - $DIR_PHOTOS/Videos:/mnt/media/Photos/Videos:ro
    environment:
      TZ: $TZ
      IMMICH_ENV: production
      IMMICH_LOG_LEVEL: ${IMMICH_LOG_LEVEL:-error}
      IMMICH_LOG_FORMAT: console
      IMMICH_MEDIA_LOCATION: /data
      # IMMICH_CONFIG_FILE: DUMMY
      NO_COLOR: false
      IMMICH_API_METRICS_PORT: 8081
      IMMICH_MICROSERVICES_METRICS_PORT: 8082
      IMMICH_PROCESS_INVALID_IMAGES: false
      IMMICH_ALLOW_SETUP: false
      ## Ports
      IMMICH_HOST: 0.0.0.0
      IMMICH_PORT: 2283
      ## Database
      DB_HOSTNAME: immich-postgres
      DB_PORT: 5432
      DB_USERNAME: $IMMICH_DB_USERNAME
      DB_PASSWORD: $IMMICH_DB_PASSWORD
      DB_DATABASE_NAME: immich
      DB_SKIP_MIGRATIONS: false
      ## Redis
      REDIS_HOSTNAME: immich-redis
      REDIS_PORT: 6379
      # REDIS_USERNAME: DUMMY
      # REDIS_PASSWORD: DUMMY
      # REDIS_DBINDEX: 0
      ## Prometheus
      # IMMICH_TELEMETRY_INCLUDE: "all" # host, api, io, repo, job
      # IMMICH_TELEMETRY_EXCLUDE: DUMMY # host, api, io, repo, job
    healthcheck:
      disable: false
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 2m
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.immich-server-rtr.entrypoints: "websecure"
      traefik.http.routers.immich-server-rtr.rule: "Host(`photos.$DOMAINNAME`)"
      # - "traefik.http.routers.immich-server-rtr.rule=Host(`photos.$DOMAINNAME`) && Pathprefix(`/api`)"
      ## Middlewares
      traefik.http.routers.immich-server-rtr.middlewares: "chain-tinyauth-relaxed@file" # NOTE: relaxed needed for `Map` tab to work
      # traefik.http.routers.immich-server-rtr.middlewares: "chain-no-auth-relaxed@file" # NOTE: relaxed needed for `Map` tab to work
      # - "traefik.http.routers.immich-server-rtr.middlewares=add-api"
      # - "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
      ## HTTP Services
      traefik.http.routers.immich-server-rtr.service: "immich-server-svc"
      traefik.http.services.immich-server-svc.loadbalancer.server.port: "2283"
      ####### TINYAUTH #######
      tinyauth.apps.photos.config.domain: "photos.$DOMAINNAME"
      tinyauth.apps.photos.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Immich"
      homepage.icon: "immich.svg"
      homepage.href: "https://photos.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Selfhosted Photo App"
      homepage.widget.type: "immich"
      homepage.widget.url: "http://immich-server:2283"
      homepage.widget.key: "$IMMICH_API_KEY"
      homepage.widget.version: "2"
      ####### GLANCE #######
      glance.name: "Immich"
      glance.icon: "sh:immich-server"
      glance.url: "https://photos.$DOMAINNAME"
      glance.description: "Selfhosted Photo App"

  ##############################################
  # https://github.com/Salvoxia/immich-folder-album-creator
  immich-folder-album-creator:
    image: salvoxia/immich-folder-album-creator:0.25.2@sha256:79b82f9818ded34c8dcfc5df0502126fdaff698b94ddad4b20ac1f0c3a7dcba2
    container_name: immich-folder-album-creator
    restart: "no"
    depends_on:
      - immich-server
    profiles:
      - media
      - immich
    networks:
      - immich_backend
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY: $IMMICH_API_KEY
      ROOT_PATH: /mnt/media/Photos/Pictures
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Istanbul
      ALBUM_LEVELS: 1
      LOG_LEVEL: INFO
      SYNC_MODE: "2" # Remove offline assets and delete empty albums after each run
      # RUN_IMMEDIATELY: "true" # Run the script immediately after start

  # NOTE: On Immich -> Admin -> Settings -> Server Settings -> External Domain
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:1.15.6@sha256:48c4ea4884b04c77a4a4ec93e190dea6cb7dc1b38acb005a35dd56f68212d85a
    container_name: immich-public-proxy
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - immich-server
    profiles:
      - media
      - immich
    networks:
      - immich_backend
    ports:
      - "1003:3000"
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:3000/share/healthcheck >/dev/null || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - $REPO_PATH/configs/immich-public-proxy/config.json:/app/config.json:ro
    environment:
      IMMICH_URL: http://immich-server:2283
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Immich-Public-Proxy"
      homepage.icon: "immich.svg"
      ####### GLANCE #######
      glance.name: "Immich-Public-Proxy"
      glance.icon: "sh:immich-public-proxy"
