services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    container_name: it-tools
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /var/cache/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/run:uid=$PUID,gid=$PGID,mode=775
      - /var/log/nginx:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes: []
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.it-tools-rtr.entrypoints: "websecure"
      traefik.http.routers.it-tools-rtr.rule: "Host(`it-tools.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.it-tools-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.it-tools-rtr.service: "it-tools-svc"
      traefik.http.services.it-tools-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "It-Tools"
      homepage.icon: "it-tools.svg"
      homepage.href: "https://it-tools.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "It Tools"
      ####### GLANCE #######
      glance.name: It-Tools
      glance.icon: sh:it-tools
      glance.url: https://it-tools.$DOMAINNAME
      glance.description: It Tools
