services:
  jdownloader:
    image: jlesage/jdownloader-2:latest@sha256:3d6cb102bd9bacff12ab1ca5136a38cb8f93d6595a7ccf5bce60aac4df138ebd
    container_name: jdownloader
    restart: $RESTART_POLICY_MEDIA
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/jdownloader:/config:rw
      - $DIR_MEDIA/Downloads:/output:rw
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      # VNC_PASSWORD: $JDOWN_VNC_PASSWD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.jdownloader-rtr.entrypoints: "websecure"
      traefik.http.routers.jdownloader-rtr.rule: "Host(`jdownloader.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.jdownloader-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.jdownloader-rtr.service: "jdownloader-svc"
      traefik.http.services.jdownloader-svc.loadbalancer.server.port: "5800"
      ####### TINYAUTH #######
      tinyauth.apps.jdownloader.config.domain: "jdownloader.$DOMAINNAME"
      tinyauth.apps.jdownloader.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Jdownloader"
      homepage.icon: "jdownloader.svg"
      homepage.href: "https://jdownloader.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Download Management Tool"
    profiles:
      - media
