services:
  # TODO: Harden
  # NOTE: Install in Jellyfin UI https://github.com/arnesacnussem/jellyfin-plugin-meilisearch
  jellyfin-meilisearch:
    image: getmeili/meilisearch:v1.32.1@sha256:54dfe0a03e81078d401a144ab6a798e4c210bea7d2ee54b7f7a6cdb456040bea
    container_name: jellyfin-meilisearch
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - custom-user
      - media
      - jellyfin
    networks:
      - t3_proxy
    # user: "65534:65534"
    # read_only: true
    tmpfs:
      - /tmp
    expose:
      - "7700"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/jellyfin-meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: "1234"
    labels:
      ####### GLANCE #######
      glance.name: "jellyfin-meilisearch"
      glance.parent: "jellyfin"

  # FIXME: middlewares-secure-headers doesn't work for `feishin`
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:latest@sha256:93227545077893cc9516f28b3adb733b67bc4691f41b6167428a2a0e3220b81c
    container_name: jellyfin
    # cpus: "0.5"
    mem_reservation: "2048M"
    mem_limit: "2048M"
    restart: $RESTART_POLICY_MEDIA
    depends_on:
      - jellyfin-meilisearch
    profiles:
      - media
      - jellyfin
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.161
    ports:
      - "1002:8096"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/jellyfin:/config
      - $REPO_PATH/appdata/jellyfin/cache:/cache
      - $REPO_PATH/data/jellyfin/metadata:/config/metadata
      - $REPO_PATH/data/downloads:/media/downloads:ro
      - $DIR_MEDIA:/media/local:ro
      # - $ONEDRIVEDIR:/media/onedrive:ro
    environment:
      MEILI_URL: http://jellyfin-meilisearch:7700
      MEILI_MASTER_KEY: "1234"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.jellyfin-rtr.entrypoints: "websecure"
      traefik.http.routers.jellyfin-rtr.rule: "Host(`jellyfin.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.jellyfin-rtr.middlewares: "chain-tinyauth-relaxed@file"
      # traefik.http.routers.jellyfin-rtr.middlewares: "chain-no-auth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.jellyfin-rtr.service: "jellyfin-svc"
      traefik.http.services.jellyfin-svc.loadbalancer.server.port: "8096"
      ####### TINYAUTH #######
      tinyauth.apps.jellyfin.config.domain: "jellyfin.$DOMAINNAME"
      tinyauth.apps.jellyfin.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Jellyfin"
      homepage.icon: "jellyfin.svg"
      homepage.href: "https://jellyfin.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Media Server"
      homepage.widget.type: "jellyfin"
      # homepage.widget.version: "2"
      homepage.widget.url: "http://jellyfin:8096"
      homepage.widget.key: "$JELLYFIN_API_KEY"
      homepage.widget.enableBlocks: "true"
      homepage.widget.enableNowPlaying: "false"
      ####### GLANCE #######
      glance.name: "jellyfin"
      glance.icon: "sh:jellyfin"
      glance.url: "https://jellyfin.$DOMAINNAME"
      glance.description: "Media Server"
      glance.id: "jellyfin"
