services:
  # Optional: You can also use postgres as db instead of sqlite, which is the default.
  # NOTE: At the first setup, use jellyfin url as: http://jellyfin:8096
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: $RESTART_POLICY_MEDIA
    # depends_on:
    #   - jellyfin
    profiles:
      - media
      - jellyfin
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/jellyseerr:/app/config
    environment:
      TZ: $TZ
      LOG_LEVEL: debug
      PORT: 5055
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.jellyseerr-rtr.entrypoints: "websecure"
      traefik.http.routers.jellyseerr-rtr.rule: "Host(`jellyseerr.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.jellyseerr-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.jellyseerr-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.jellyseerr-rtr.service: "jellyseerr-svc"
      traefik.http.services.jellyseerr-svc.loadbalancer.server.port: "5055"
      ####### TINYAUTH #######
      tinyauth.apps.jellyseerr.config.domain: "jellyseerr.$DOMAINNAME"
      tinyauth.apps.jellyseerr.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Jellyseerr"
      homepage.icon: "jellyseerr.svg"
      homepage.href: "https://jellyseerr.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Media Request Manager for Jellyfin"
      homepage.widget.type: "jellyseerr"
      homepage.widget.url: "http://jellyseerr:5055"
      homepage.widget.key: "$JELLYSEERR_API_KEY"
      ####### GLANCE #######
      glance.name: "jellyseerr"
      glance.parent: "jellyfin"
