services:
  kasm:
    container_name: kasm
    image: lscr.io/linuxserver/kasm:latest@sha256:ebe5a902f8ebc3a59c042c97a61eb8ee82ccf6c345b17042f2753924967105da
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    privileged: true
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/kasm/opt:/opt
    #   - /path/to/profiles:/profiles #optional
    #   - /dev/input:/dev/input #optional
    #   - /run/udev/data:/run/udev/data #optional
    ports:
      - 3030:3000
      # - 4443:4443
    # expose:
    #   - 4443
    environment:
      KASM_PORT: 4433
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.kasm-rtr.entrypoints: "websecure"
      traefik.http.routers.kasm-rtr.rule: "Host(`kasm.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.kasm-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.kasm-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.kasm-rtr.service: "kasm-svc"
      traefik.http.services.kasm-svc.loadbalancer.server.port: "4443"
      ####### TINYAUTH #######
      tinyauth.apps.kasm.config.domain: "kasm.$DOMAINNAME"
      tinyauth.apps.kasm.ip.bypass: "$LOCAL_IPS"
      # NOTE: https://docs.linuxserver.io/faq#strict-proxy
      traefik.http.services.kasm-svc.loadbalancer.serverstransport: "ignorecert@file"
      traefik.http.services.kasm-svc.loadbalancer.server.scheme: "https"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Kasm Workspaces"
      homepage.icon: "kasm.svg"
      homepage.href: "https://kasm.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Workspaces for delivering browser-based access to desktop applications"
    profiles:
      - desktop_apps
