# NOTE: Don't forget to create a bucket named "langfuse" in Minio.

services:
  # NOTE: Create related dirs
  ## sudo mkdir -p $REPO_PATH/data/langfuse/clickhouse/data
  ## sudo mkdir -p $REPO_PATH/data/langfuse/clickhouse/logs
  ## sudo chown -R 101:101 $REPO_PATH/data/langfuse/clickhouse
  langfuse-clickhouse:
    image: clickhouse/clickhouse-server
    container_name: langfuse-clickhouse
    restart: $RESTART_POLICY_PROGRAMMING
    user: "101:101"
    profiles:
      - programming
      - langfuse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: $LANGFUSE_CLICKHOUSE_USER
      CLICKHOUSE_PASSWORD: $LANGFUSE_CLICKHOUSE_PASSWORD
    volumes:
      - $REPO_PATH/data/langfuse/clickhouse/data:/var/lib/clickhouse
      - $REPO_PATH/data/langfuse/clickhouse/logs:/var/log/clickhouse-server
    networks:
      - t3_proxy
    expose:
      - 8123
      - 9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s

  langfuse-db:
    image: postgres:16.4
    container_name: langfuse-db
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - langfuse
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /pgdata
    networks:
      - t3_proxy
    expose:
      - 5432
    volumes:
      - $REPO_PATH/data/langfuse/langfuse-db:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3


  langfuse-redis:
    image: redis:7
    container_name: langfuse-redis
    restart: $RESTART_POLICY_PROGRAMMING
    command: >
      --requirepass $LANGFUSE_REDIS_PASSWORD
    profiles:
      - programming
      - langfuse
    networks:
      - t3_proxy
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    container_name: langfuse-worker
    restart: $RESTART_POLICY_PROGRAMMING
    depends_on: &langfuse-depends-on
      langfuse-clickhouse:
        condition: service_healthy
      langfuse-db:
        condition: service_healthy
      langfuse-redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    profiles:
      - programming
      - langfuse
    networks:
      - t3_proxy
    expose:
      - 3030
    environment: &langfuse-worker-env
      DATABASE_URL: postgresql://postgres:postgres@langfuse-db:5432/postgres
      SALT: $LANGFUSE_SALT
      ENCRYPTION_KEY: $LANGFUSE_ENCRYPTION_KEY
      TELEMETRY_ENABLED: false
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: true
      CLICKHOUSE_MIGRATION_URL: ${CLICKHOUSE_MIGRATION_URL:-clickhouse://langfuse-clickhouse:9000}
      CLICKHOUSE_URL: ${CLICKHOUSE_URL:-http://langfuse-clickhouse:8123}
      CLICKHOUSE_USER: $LANGFUSE_CLICKHOUSE_USER
      CLICKHOUSE_PASSWORD: $LANGFUSE_CLICKHOUSE_PASSWORD
      CLICKHOUSE_CLUSTER_ENABLED: ${CLICKHOUSE_CLUSTER_ENABLED:-false}
      LANGFUSE_USE_AZURE_BLOB: ${LANGFUSE_USE_AZURE_BLOB:-false}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: ${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}
      LANGFUSE_S3_EVENT_UPLOAD_REGION: ${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: $MINIO_ROOT_USER
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: $MINIO_ROOT_PASSWORD
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: ${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9000}
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: ${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: ${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: ${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: ${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: $MINIO_ROOT_USER
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: $MINIO_ROOT_PASSWORD
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: ${LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT:-http://localhost:9090}
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: ${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}
      LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: ${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}
      LANGFUSE_S3_BATCH_EXPORT_ENABLED: ${LANGFUSE_S3_BATCH_EXPORT_ENABLED:-false}
      LANGFUSE_S3_BATCH_EXPORT_BUCKET: ${LANGFUSE_S3_BATCH_EXPORT_BUCKET:-langfuse}
      LANGFUSE_S3_BATCH_EXPORT_PREFIX: ${LANGFUSE_S3_BATCH_EXPORT_PREFIX:-exports/}
      LANGFUSE_S3_BATCH_EXPORT_REGION: ${LANGFUSE_S3_BATCH_EXPORT_REGION:-auto}
      LANGFUSE_S3_BATCH_EXPORT_ENDPOINT: ${LANGFUSE_S3_BATCH_EXPORT_ENDPOINT:-http://minio:9000}
      LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT: ${LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT:-http://localhost:9090}
      LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID: $MINIO_ROOT_USER
      LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY: $MINIO_ROOT_PASSWORD
      LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE: ${LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE:-true}
      LANGFUSE_INGESTION_QUEUE_DELAY_MS: ${LANGFUSE_INGESTION_QUEUE_DELAY_MS:-}
      LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS: ${LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS:-}
      REDIS_HOST: ${REDIS_HOST:-langfuse-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_AUTH: $LANGFUSE_REDIS_PASSWORD
      REDIS_TLS_ENABLED: ${REDIS_TLS_ENABLED:-false}
      REDIS_TLS_CA: ${REDIS_TLS_CA:-/certs/ca.crt}
      REDIS_TLS_CERT: ${REDIS_TLS_CERT:-/certs/redis.crt}
      REDIS_TLS_KEY: ${REDIS_TLS_KEY:-/certs/redis.key}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-}
      SMTP_CONNECTION_URL: ${SMTP_CONNECTION_URL:-}

  langfuse-web:
    image: langfuse/langfuse:3
    container_name: langfuse-web
    restart: $RESTART_POLICY_PROGRAMMING
    depends_on: *langfuse-depends-on
    profiles:
      - programming
      - langfuse
    networks:
      - t3_proxy
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_URL: https://langfuse.$DOMAINNAME
      NEXTAUTH_SECRET: $LANGFUSE_SALT_NEXTAUTH_SECRET
      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID:-}
      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME:-}
      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID:-}
      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME:-}
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}
      LANGFUSE_INIT_USER_EMAIL: $LANGFUSE_INIT_USER_EMAIL
      LANGFUSE_INIT_USER_NAME: $LANGFUSE_INIT_USER_NAME
      LANGFUSE_INIT_USER_PASSWORD: $LANGFUSE_INIT_USER_PASSWORD
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.langfuse-web-rtr.entrypoints: "websecure"
      traefik.http.routers.langfuse-web-rtr.rule: "Host(`langfuse.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.langfuse-web-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.langfuse-web-rtr.service: "langfuse-web-svc"
      traefik.http.services.langfuse-web-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.langfuse.config.domain: "langfuse.$DOMAINNAME"
      tinyauth.apps.langfuse.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "langfuse"
      homepage.icon: "langfuse.svg"
      homepage.href: "https://langfuse.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "LLM engineering platform: LLM Observability, metrics, evals, prompt management, playground, datasets"
      ####### GLANCE #######
      glance.name: "langfuse"
      glance.icon: "sh:langfuse"
      glance.url: "https://langfuse.$DOMAINNAME"
      glance.description: "LLM engineering platform: LLM Observability, metrics, evals, prompt management, playground, datasets"