services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian@sha256:ac577f75b95965d212cdf3ae39a81fd2992e2da46f9698bc9102bd71643fd08a
    container_name: lazylibrarian
    restart: unless-stopped
    # profiles:
    # - media
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #  - "$LAZYLIBRARIAN_PORT:5299"
    volumes:
      - $REPO_PATH/appdata/lazylibrarian:/config
      - $REPO_PATH/data/downloads:/data/downloads
      - $REPO_PATH/appdata/calibre/books:/books:rw
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: linuxserver/calibre-web:calibre # set the path to converter tool to /app/calibre/ebook-convert
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.lazylibrarian-rtr.entrypoints: "websecure"
      traefik.http.routers.lazylibrarian-rtr.rule: "Host(`lazy.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.lazylibrarian-rtr.middlewares: "chain-oauth@file"
      ## HTTP Services
      traefik.http.routers.lazylibrarian-rtr.service: "lazylibrarian-svc"
      traefik.http.services.lazylibrarian-svc.loadbalancer.server.port: "5299"
      ####### TINYAUTH #######
      tinyauth.apps.lazy.config.domain: "lazy.$DOMAINNAME"
      tinyauth.apps.lazy.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "LazyLibrarian"
      homepage.icon: "lazylibrarian.svg"
      homepage.href: "https://lazylibrarian.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Follow Authors and Grab Metadata for All Your Digital Reading Needs"
    profiles:
      - reading
