services:
  loggifly:
    image: ghcr.io/clemcer/loggifly:latest
    container_name: loggifly
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
      - socket_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/loggifly:/config:ro
    environment:
      DOCKER_HOST: $DOCKER_REMOTE_HOSTS
      TZ: $TZ
      APPRISE_URL: $GOTIFY_LOGGIFLY_APPRISE_URL
      LOG_LEVEL: "INFO"
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "loggifly"
      homepage.icon: "loggifly.png"
      homepage.target: "_blank"
      homepage.description: "Get Alerts from your Docker Container Logs"
      ####### GLANCE #######
      glance.name: "loggifly"
      glance.icon: "sh:loggifly"
      glance.description: "Get Alerts from your Docker Container Logs"
