services:
  mazanoke:
    image: ghcr.io/civilblur/mazanoke:latest@sha256:e43dc48de575b7a032bbefd96b890d69c1f141417e43d5d096469aa1398711d6
    container_name: mazanoke
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /var/cache/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/run:uid=$PUID,gid=$PGID,mode=775
      - /var/log/nginx:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.mazanoke-rtr.entrypoints: "websecure"
      traefik.http.routers.mazanoke-rtr.rule: "Host(`mazanoke.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.mazanoke-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.mazanoke-rtr.service: "mazanoke-svc"
      traefik.http.services.mazanoke-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.mazanoke.config.domain: "mazanoke.$DOMAINNAME"
      tinyauth.apps.mazanoke.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "mazanoke"
      homepage.icon: "mazanoke.png"
      homepage.href: "https://mazanoke.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A local image optimizer that runs in your browser"
      ####### GLANCE #######
      glance.name: "mazanoke"
      glance.icon: "sh:mazanoke"
      glance.url: "https://mazanoke.$DOMAINNAME"
      glance.description: "A local image optimizer that runs in your browser"
