services:
  mazanoke:
    image: ghcr.io/civilblur/mazanoke:v1.1.6@sha256:92cc7474deb789af6549318563b7a9ee750131f9f7b297cc9c87ab67e656c22c
    container_name: mazanoke
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /var/cache/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/run:uid=$PUID,gid=$PGID,mode=775
      - /var/log/nginx:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes: []
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.mazanoke-rtr.entrypoints: "websecure"
      traefik.http.routers.mazanoke-rtr.rule: "Host(`mazanoke.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.mazanoke-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.mazanoke-rtr.service: "mazanoke-svc"
      traefik.http.services.mazanoke-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "mazanoke"
      homepage.icon: "mazanoke.png"
      homepage.href: "https://mazanoke.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A local image optimizer that runs in your browser"
      ####### GLANCE #######
      glance.name: "mazanoke"
      glance.icon: "sh:mazanoke"
      glance.url: "https://mazanoke.$DOMAINNAME"
      glance.description: "A local image optimizer that runs in your browser"
