services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - youtube
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DIR_MEDIA/Youtube:/downloads
      - $DIR_MEDIA/Youtube/cookies:/cookies
    environment:
      UID: $PUID
      GID: $PGID
      CHOWN_DIRS: true
      LOGLEVEL: ${METUBE_LOGLEVEL:-INFO}
      PORT: 8081
      OUTPUT_TEMPLATE: '%(title)s [%(id)s].%(ext)s'
      # YTDL_OPTIONS: '{"writethumbnail": true, "writeinfojson": true}' # "writeinfojson": true,
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt"}'
      # Downloaded files are deleted on the server, when they are trashed from the "Completed" section of the UI
      DELETE_FILE_ON_TRASHCAN: ${METUBE_DELETE_FILE_ON_TRASHCAN:-true}
      MAX_CONCURRENT_DOWNLOADS: ${METUBE_MAX_CONCURRENT_DOWNLOADS:-10}
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.metube-rtr.entrypoints: "websecure"
      traefik.http.routers.metube-rtr.rule: "Host(`metube.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.metube-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.metube-rtr.service: "metube-svc"
      traefik.http.services.metube-svc.loadbalancer.server.port: "8081"
      ####### TINYAUTH #######
      tinyauth.apps.metube.config.domain: "metube.$DOMAINNAME"
      tinyauth.apps.metube.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "metube"
      homepage.icon: "metube.svg"
      homepage.href: "https://metube.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Self-hosted YouTube downloader"
