services:
  mkdocs-material:
    container_name: mkdocs-material
    image: squidfunk/mkdocs-material
    restart: $RESTART_POLICY_OTHERS
    command: serve --dev-addr=0.0.0.0:8000 --no-livereload
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DIR_NOTES/Markdown/Programming/Interview:/docs/docs/blog/posts:ro
      - $REPO_PATH/configs/mkdocs-material/mkdocs.yml:/docs/mkdocs.yml
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.mkdocs-material-rtr.entrypoints: "websecure"
      traefik.http.routers.mkdocs-material-rtr.rule: "Host(`mkdocs.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.mkdocs-material-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.mkdocs-material-rtr.service: "mkdocs-material-svc"
      traefik.http.services.mkdocs-material-svc.loadbalancer.server.port: "8000"
      ####### TINYAUTH #######
      tinyauth.apps.mkdocs.config.domain: "mkdocs.$DOMAINNAME"
      tinyauth.apps.mkdocs.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "mkdocs-material"
      homepage.icon: "mkdocs.svg"
      homepage.href: "https://mkdocs.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Mkdocs-Material"
    profiles:
      - reading
