services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
    container_name: mosquitto
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
    networks:
      - t3_proxy
    ports:
      - "1883:1883" # default mqtt port
      - "9001:9001" # default mqtt port for websockets
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/mosquitto:/mosquitto/config
      - $REPO_PATH/data/mosquitto:/mosquitto/data
      - $REPO_PATH/logs/mosquitto:/mosquitto/log
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "mosquitto"
      homepage.icon: "mosquitto.png"
      homepage.href: "#"
      homepage.target: "_blank"
      homepage.description: "Message broker that implements MQTT version 5, 3.1.1 and 3.1"
      ####### GLANCE #######
      glance.name: "mosquitto"
      glance.icon: "sh:mosquitto"
      glance.url: "#"
      glance.description: "Message broker that implements MQTT version 5, 3.1.1 and 3.1"
