services:
  # TODO: Not completed !!
  movie-web:
    container_name: movie-web
    build: $GITHUBREPOSDIR/movie-web
    image: movie-web:4.2.0
    # image: ghcr.io/movie-web/movie-web # NOTE: There is no pushed docker image
    restart: $MEDIA_RESTART_POLICY
    networks:
      - t3_proxy
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.movieweb-rtr.entrypoints: "websecure"
      traefik.http.routers.movieweb-rtr.rule: "Host(`movieweb.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.movieweb-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.movieweb-rtr.service: "movieweb-svc"
      traefik.http.services.movieweb-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.movieweb.config.domain: "movieweb.$DOMAINNAME"
      tinyauth.apps.movieweb.ip.bypass: "$LOCAL_IPS"
    profiles:
      - media
