services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: $RESTART_POLICY_MAINTENANCE
    pid: host
    networks:
      - t3_proxy
    hostname: $DOMAINNAME # set to fqdn of host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - $REPO_PATH/appdata/netdata/netdataconfig:/etc/netdata
      - $REPO_PATH/appdata/netdata/netdatalib:/var/lib/netdata
      - $REPO_PATH/appdata/netdata/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.netdata-rtr.entrypoints: "websecure"
      traefik.http.routers.netdata-rtr.rule: "Host(`netdata.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.netdata-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.netdata-rtr.service: "netdata-svc"
      traefik.http.services.netdata-svc.loadbalancer.server.port: "19999"
      ####### TINYAUTH #######
      tinyauth.apps.netdata.config.domain: "netdata.$DOMAINNAME"
      tinyauth.apps.netdata.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "Netdata"
      homepage.icon: "netdata.svg"
      homepage.href: "https://netdata.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Monitoring and troubleshooting, transformed"
    profiles:
      - monitoring
