services:
  # NOTE: Recent file location: /config/.local/share/okular/docdata/
  okular:
    container_name: okular
    image: okular:latest
    build:
      context: $REPO_PATH/Dockerfiles/DesktopApps/Okular
      dockerfile: $REPO_PATH/Dockerfiles/DesktopApps/Okular/Dockerfile
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/okular:/config
      - $DIR_MEDIA/Books:/books
      - $DIR_HARDDISKROOT/School/Thesis/Papers:/thesis
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.okular-rtr.entrypoints: "websecure"
      traefik.http.routers.okular-rtr.rule: "Host(`okular.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.okular-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.okular-rtr.service: "okular-svc"
      traefik.http.services.okular-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.okular.config.domain: "okular.$DOMAINNAME"
      tinyauth.apps.okular.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Okular"
      homepage.icon: "/icons/okular.png"
      homepage.href: "https://okular.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Pdf Viewing"
    profiles:
      - desktop_apps
