services:
  omni-tools:
    image: iib0011/omni-tools:latest@sha256:437e7f6f2ddf12bbe5a3d2d00cb853af40c3768d0e2b8b62780e05ba6c4ce61d
    container_name: omni-tools
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /var/cache/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/run:uid=$PUID,gid=$PGID,mode=775
      - /var/log/nginx:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes: []
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.omni-tools-rtr.entrypoints: "websecure"
      traefik.http.routers.omni-tools-rtr.rule: "Host(`omni-tools.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.omni-tools-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.omni-tools-rtr.service: "omni-tools-svc"
      traefik.http.services.omni-tools-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "omni-tools"
      homepage.icon: "omni-tools.png"
      homepage.href: "https://omni-tools.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Web-based tools for everyday tasks"
      ####### GLANCE #######
      glance.name: "omni-tools"
      glance.icon: "sh:omni-tools"
      glance.url: "https://omni-tools.$DOMAINNAME"
      glance.description: "Web-based tools for everyday tasks"
