# NOTE: Chown the directory.
# mkdir -p $REPO_PATH/appdata/pgadmin
# sudo chown 5050:5050 $REPO_PATH/appdata/pgadmin
# NOTE: Add internal databases only using their docker container names (http:// shouldn't be included)
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: $RESTART_POLICY_MAINTENANCE
    user: 5050:5050
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.pgadmin-rtr.entrypoints: "websecure"
      traefik.http.routers.pgadmin-rtr.rule: "Host(`pgadmin.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.pgadmin-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.pgadmin-rtr.service: "pgadmin-svc"
      traefik.http.services.pgadmin-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.pgadmin.config.domain: "pgadmin.$DOMAINNAME"
      tinyauth.apps.pgadmin.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "pgadmin"
      homepage.icon: "pgadmin.png"
      homepage.href: "https://pgadmin.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "description"
      ####### GLANCE #######
      glance.name: "pgadmin"
      glance.icon: "sh:pgadmin"
      glance.url: "https://pgadmin.$DOMAINNAME"
      glance.description: "description"
