# TODO: Harden
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest@sha256:01b4f98aabaf3f5fe394213f7a32578c9e84e42080f52e2f8334021a4473b202
    container_name: pinchflat
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - custom-user
      - media
      - youtube
    networks:
      - t3_proxy
    user: $PUID:$PGID
    # read_only: true
    # tmpfs:
    #   - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/pinchflat:/config
      - $DIR_MEDIA/Youtube:/downloads
    environment:
      TZ: $TZ
      ENABLE_PROMETHEUS: false
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.pinchflat-rtr.entrypoints: "websecure"
      traefik.http.routers.pinchflat-rtr.rule: "Host(`pinchflat.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.pinchflat-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.pinchflat-rtr.service: "pinchflat-svc"
      traefik.http.services.pinchflat-svc.loadbalancer.server.port: "8945"
      ####### TINYAUTH #######
      tinyauth.apps.pinchflat.config.domain: "pinchflat.$DOMAINNAME"
      tinyauth.apps.pinchflat.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "pinchflat"
      homepage.icon: "pinchflat.png"
      homepage.href: "https://pinchflat.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Your next YouTube media manager"
      ####### GLANCE #######
      glance.name: "pinchflat"
      glance.icon: "sh:pinchflat"
      glance.url: "https://pinchflat.$DOMAINNAME"
      glance.description: "Your next YouTube media manager"
