# In initial setup, go to /login/setup
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.11.0@sha256:b7c37ab3044e53fd29b5f7295eebff5fdc0367dc043f36b41bcbe1815fcd965d
    container_name: pocket-id
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    ports:
      - "1000:1411"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/pocket-id:/app/data
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_URL: https://pocketid.$BASE_DOMAINNAME
      PORT: 1411
      ENCRYPTION_KEY: $POCKETID_ENCRYPTION_KEY
      DISABLE_RATE_LIMITING: true
      ANALYTICS_DISABLED: true
      TRUST_PROXY: true
      MAXMIND_LICENSE_KEY: $MAXMIND_LICENSE_KEY
      #  STATIC_API_KEY: your_api_key # Useful for declerative installations
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:1411/healthz >/dev/null || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      # traefik.enable: "true"
      # ## HTTP Routers
      # traefik.http.routers.pocket-id-rtr.entrypoints: "websecure"
      # traefik.http.routers.pocket-id-rtr.rule: "Host(`pocketid.$DOMAINNAME`)"
      # ## Middlewares
      # traefik.http.routers.pocket-id-rtr.middlewares: "chain-no-auth@file"
      # ## HTTP Services
      # traefik.http.routers.pocket-id-rtr.service: "pocket-id-svc"
      # traefik.http.services.pocket-id-svc.loadbalancer.server.port: "1411"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "pocket-id"
      homepage.icon: "pocket-id.svg"
      homepage.href: "https://pocketid.$BASE_DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "OIDC provider using only passkeys"
      ####### GLANCE #######
      glance.name: "pocket-id"
      glance.icon: "sh:pocket-id-dark"
      glance.url: "https://pocketid.$BASE_DOMAINNAME"
      glance.description: "OIDC provider using only passkeys"
