# TODO: Harden
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.0-develop@sha256:2df9ae57c475bf4341abd833e56a9268bb02167cc5f3f828a8347d2d8628f652
    container_name: prowlarr
    # depends_on:
    #   - transmission
    #   - sabnzbd
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - root
      - media
      - arr
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    pids_limit: 256
    cpus: "1.0"
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/prowlarr:/config
      - $DIR_MEDIA/Downloads:/data/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: ["CMD", "curl", "-fsS", "--max-time", "3", "-o", "/dev/null", "http://127.0.0.1:9696/ping"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.prowlarr-rtr.entrypoints: "websecure"
      traefik.http.routers.prowlarr-rtr.rule: "Host(`prowlarr.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.prowlarr-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.prowlarr-rtr.service: "prowlarr-svc"
      traefik.http.services.prowlarr-svc.loadbalancer.server.port: "9696"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Prowlarr"
      homepage.icon: "prowlarr.svg"
      homepage.href: "https://prowlarr.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Indexer Manager"
