services:
  readeck:
    image: codeberg.org/readeck/readeck:0.23.2@sha256:32bd82e457a3a9a3fffb161f55cfebf0fd7ffbc87ddf2fe7a321361905348f0a
    container_name: readeck
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - reading
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,uid=$PUID,gid=$PGID,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: "1.0"
    mem_limit: "1G"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/readeck:/readeck
    environment:
      READECK_LOG_LEVEL: info
      READECK_SERVER_HOST: "0.0.0.0"
      READECK_SERVER_PORT: "8000"
      READECK_SERVER_BASE_URL: https://readeck.$DOMAINNAME
      READECK_LOG_FORMAT: text
      # READECK_ALLOWED_HOSTS: readeck.$DOMAINNAME # NOTE: It is working without this.
      ## OIDC
      READECK_AUTH_OIDC_PROVIDERS_0_NAME: Pocket ID
      READECK_AUTH_OIDC_PROVIDERS_0_URL: https://pocketid.$BASE_DOMAINNAME
      READECK_AUTH_OIDC_PROVIDERS_0_CLIENT_ID: $READECK_CLIENT_ID
      READECK_AUTH_OIDC_PROVIDERS_0_CLIENT_SECRET: $READECK_CLIENT_SECRET
      READECK_AUTH_OIDC_PROVIDERS_0_GROUPS: "admin=admin"
      READECK_AUTH_OIDC_PROVIDERS_0_PROVISIONING: false
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.readeck-rtr.entrypoints: "websecure"
      traefik.http.routers.readeck-rtr.rule: "Host(`readeck.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.readeck-rtr.middlewares: "middlewares-scalar-openapi-cors@file,chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.readeck-rtr.service: "readeck-svc"
      traefik.http.services.readeck-svc.loadbalancer.server.port: "8000"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "readeck"
      homepage.icon: "readeck.png"
      homepage.href: "https://readeck.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Read it later app"
      ####### GLANCE #######
      glance.name: "readeck"
      glance.icon: "sh:readeck"
      glance.url: "https://readeck.$DOMAINNAME"
      glance.description: "Read it later app"
