services:
  rsshub-browserless:
    image: browserless/chrome@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
    container_name: rsshub-browserless
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - custom-user
      - reading
      - rsshub
    networks:
      - t3_proxy
    user: blessuser
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    ulimits:
      core:
        hard: 0
        soft: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      ####### GLANCE #######
      glance.name: "rsshub-browserless"
      glance.parent: "rsshub"

  rsshub-redis:
    image: redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
    container_name: rsshub-redis
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - custom-user
      - reading
      - rsshub
    networks:
      - t3_proxy
    user: redis
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/rsshub-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 5s
    labels:
      ####### GLANCE #######
      glance.name: "rsshub-redis"
      glance.parent: "rsshub"

  rsshub:
    image: ghcr.io/diygod/rsshub:latest@sha256:a2734f3b884b9cf493ccc60a80e2750165862c9ddffc2c6d4520fa6fc21096f3
    container_name: rsshub
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - custom-user
      - reading
      - rsshub
    networks:
      - t3_proxy
    user: node
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    depends_on:
      - rsshub-redis
      - rsshub-browserless
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://rsshub-redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://rsshub-browserless:3000"
      TWITTER_AUTH_TOKEN: $TWITTER_AUTH_TOKEN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.rsshub-rtr.entrypoints: "websecure"
      traefik.http.routers.rsshub-rtr.rule: "Host(`rsshub.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.rsshub-rtr.middlewares: "chain-tinyauth@file" # NOTE: use chain-no-auth for https glance access
      ## HTTP Services
      traefik.http.routers.rsshub-rtr.service: "rsshub-svc"
      traefik.http.services.rsshub-svc.loadbalancer.server.port: "1200"
      ####### TINYAUTH #######
      tinyauth.apps.rsshub.config.domain: "rsshub.$DOMAINNAME"
      tinyauth.apps.rsshub.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "rsshub"
      homepage.icon: "rsshub.png"
      homepage.href: "https://rsshub.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Everything is RSSible"
      ####### GLANCE #######
      glance.name: "rsshub"
      glance.icon: "sh:rsshub"
      glance.url: "https://rsshub.$DOMAINNAME"
      glance.description: "Everything is RSSible"
      glance.id: "rsshub"
