# Use with: drun rustic <COMMAND>
# Commands:
#  - init: Initialize a new remote repository
#      init -r /repos/TestRepo
#  - backup: Backup the local repository to the remote repository
#  - restore: Restore the remote repository to a local directory
#       -r /repos/TestRepo restore latest /restores/RestoreTest
#  - snapshots: List all snapshots in the remote repository
services:
  rustic:
    container_name: rustic
    hostname: ${MY_HOSTNAME}
    image: ghcr.io/rustic-rs/rustic:latest
    # user: $PUID:$PGID
    # build:
    #   context: $REPO_PATH/Dockerfiles/Rustic
    #   args:
    #     RUSTIC_VERSION: v0.9.5
    # restart: $RESTART_POLICY_MAINTENANCE
    restart: "no"
    command: help
    profiles:
      # - maintenance # NOTE: Commented out so that docker-manage script excludes it
      - custom-tool
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/configs/rustic/rustic.toml:/etc/rustic/rustic.toml:ro
      - $REPO_PATH/logs/rustic:/logs:rw
      # - $REPO_PATH/configs/rclone:/root/.config/rclone:rw
      - $DIR_BACKUP/RUSTIC/Repos/TestRepo:/repos/TestRepo:rw
      - $DIR_BACKUP/RUSTIC/Restores:/restores:rw
      - $DIR_BACKUP/RUSTIC/BackupTest:/backups/BackupTest:ro
      - $REPO_PATH/data/vaultwarden-backup:/backups/Vaultwarden:ro
      # - $REPO_PATH/configs:/backups/docker_configs:ro
      # - $DIR_NOTES/Markdown:/backups/Markdown:ro
    environment:
      TZ: $TZ
      RUSTIC_PASSWORD: /run/secrets/rustic_password
      # - RCLONE_CONFIG=/root/.config/rclone/rclone.conf
    secrets:
      - rustic_password
