# TODO: Harden
# NOTE: In sabnzb.ini file -> host_whitelist add: sabnzbd.$DOMAINNAME, sabnzbd
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: $RESTART_POLICY_MEDIA
    hostname: sabnzbd.$DOMAINNAME
    profiles:
      - media
      - arr
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.159
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/sabnzbd:/config
      - $DIR_MEDIA/Downloads/complete:/config/Downloads/complete
      - $DIR_MEDIA/Downloads/incomplete:/config/Downloads/incomplete
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sabnzbd-rtr.entrypoints: "websecure"
      traefik.http.routers.sabnzbd-rtr.rule: "Host(`sabnzbd.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sabnzbd-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.sabnzbd-rtr.service: "sabnzbd-svc"
      traefik.http.services.sabnzbd-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.sabnzbd.config.domain: "sabnzbd.$DOMAINNAME"
      tinyauth.apps.sabnzbd.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "sabnzbd"
      homepage.icon: "sabnzbd.png"
      homepage.href: "https://sabnzbd.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "The automated Usenet download tool"
      homepage.widget.type: "sabnzbd"
      homepage.widget.url: "http://sabnzbd:8080"
      homepage.widget.key: "$SABNZBD_API_KEY"
      ####### GLANCE #######
      glance.name: "sabnzbd"
      glance.icon: "sh:sabnzbd"
      glance.url: "https://sabnzbd.$DOMAINNAME"
      glance.description: "The automated Usenet download tool"
