# TODO: Harden
# NOTE: In sabnzb.ini file -> host_whitelist add: sabnzbd.$DOMAINNAME, sabnzbd
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5-ls249@sha256:7ac6fe8a521c7099e1768af90529dfee5976b87c7dccffdcc9ced00149e1aedb
    container_name: sabnzbd
    restart: $RESTART_POLICY_MEDIA
    hostname: sabnzbd.$DOMAINNAME
    profiles:
      - media
      - arr
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.159
    security_opt:
      - no-new-privileges:true
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/sabnzbd:/config
      - $DIR_MEDIA/Downloads/complete:/config/Downloads/complete
      - $DIR_MEDIA/Downloads/incomplete:/config/Downloads/incomplete
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:8080/api?mode=version >/dev/null || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sabnzbd-rtr.entrypoints: "websecure"
      traefik.http.routers.sabnzbd-rtr.rule: "Host(`sabnzbd.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sabnzbd-rtr.middlewares: "chain-tinyauth-relaxed@file"
      ## HTTP Services
      traefik.http.routers.sabnzbd-rtr.service: "sabnzbd-svc"
      traefik.http.services.sabnzbd-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.sabnzbd.config.domain: "sabnzbd.$DOMAINNAME"
      tinyauth.apps.sabnzbd.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "sabnzbd"
      homepage.icon: "sabnzbd.png"
      homepage.href: "https://sabnzbd.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "The automated Usenet download tool"
      homepage.widget.type: "sabnzbd"
      homepage.widget.url: "http://sabnzbd:8080"
      homepage.widget.key: "$SABNZBD_API_KEY"
      ####### GLANCE #######
      glance.name: "sabnzbd"
      glance.icon: "sh:sabnzbd"
      glance.url: "https://sabnzbd.$DOMAINNAME"
      glance.description: "The automated Usenet download tool"
