services:
  sd-next:
    container_name: sd-next
    image: vladmandic/sdnext-cuda:latest
    restart: $RESTART_POLICY_ML
    profiles:
      - programming
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/sd-next:/mnt/data:rw
      - $MLMODELSDIR/sdnext:/mnt/models:ro
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sdnext-rtr.entrypoints: "websecure"
      traefik.http.routers.sdnext-rtr.rule: "Host(`sdnext.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.sdnext-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.sdnext-rtr.service: "sdnext-svc"
      traefik.http.services.sdnext-svc.loadbalancer.server.port: "7860"
      ####### TINYAUTH #######
      tinyauth.apps.sdnext.config.domain: "sdnext.$DOMAINNAME"
      tinyauth.apps.sdnext.ip.bypass: "$LOCAL_IPS"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics]