services:
  searxng:
    image: docker.io/searxng/searxng:latest@sha256:37c616a774b90fb5df9239eb143f1b11866ddf7b830cd1ebcca6ba11b38cc2bf
    container_name: searxng
    restart: $RESTART_POLICY_PROGRAMMING
    depends_on:
      - searxng-valkey
    profiles:
      - programming
      - searxng
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/configs/searxng:/etc/searxng:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      SEARXNG_BASE_URL: https://searxng.$DOMAINNAME
      UWSGI_WORKERS: 4
      UWSGI_THREADS: 4
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.searxng-rtr.entrypoints: "websecure"
      traefik.http.routers.searxng-rtr.rule: "Host(`searxng.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.searxng-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.searxng-rtr.service: "searxng-svc"
      traefik.http.services.searxng-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.searxng.config.domain: "searxng.$DOMAINNAME"
      tinyauth.apps.searxng.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "searxng"
      homepage.icon: "searxng.png"
      homepage.href: "https://searxng.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Free internet metasearch engine"
      ####### GLANCE #######
      glance.name: "searxng"
      glance.icon: "sh:searxng"
      glance.url: "https://searxng.$DOMAINNAME"
      glance.description: "Free internet metasearch engine"

  searxng-valkey:
    image: docker.io/valkey/valkey:8-alpine@sha256:1cb6b20b70d927560cc4cc5397b5f045e74aa603ff7696274778880bb6fadc75
    container_name: searxng-valkey
    command: valkey-server --save 30 1 --loglevel warning
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - searxng
    networks:
      - t3_proxy
    expose:
      - "6379"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/searxng-valkey:/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
