services:
  silverbullet-test:
    image: ghcr.io/silverbulletmd/silverbullet
    container_name: silverbullet-test
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - reading
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/silverbullet-test:/space
    environment:
      PUID: $PUID
      PGID: $PGID
      SB_HOSTNAME: 0.0.0.0
      SB_PORT: 3000
      SB_FOLDER: /space
      SB_INDEX_PAGE: index
      # SB_READ_ONLY: true
      # SB_USER: admin:admin
      # SB_LOG_PUSH: 1
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.silverbullet-test-rtr.entrypoints: "websecure"
      traefik.http.routers.silverbullet-test-rtr.rule: "Host(`notes-test.$DOMAINNAME`)"
      ## Middlewares
      # traefik.http.routers.silverbullet-test-rtr.middlewares: chain-silverbullet@file
      traefik.http.routers.silverbullet-test-rtr.middlewares: "chain-silverbullet-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.silverbullet-test-rtr.service: "silverbullet-test-svc"
      traefik.http.services.silverbullet-test-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.silverbullet-test.config.domain: "notes-test.$DOMAINNAME"
      tinyauth.apps.silverbullet-test.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "silverbullet-test"
      homepage.icon: "silverbullet.png"
      homepage.href: "https://notes-test.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
      ####### GLANCE #######
      glance.name: "silverbullet-test"
      glance.icon: "sh:silverbullet"
      glance.url: "https://notes-test.$DOMAINNAME"
      glance.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
