# NOTE: env variables: https://silverbullet.md/Install/Configuration
services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:2.8.0@sha256:43ec44276d809a8acb3890f63a66d7229d9a778e7b3bad12fcd379415042494e
    container_name: silverbullet
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - reading
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $DIR_NOTES/Markdown:/space
    environment:
      PUID: $PUID
      PGID: $PGID
      SB_HOSTNAME: 0.0.0.0
      SB_PORT: 3000
      SB_FOLDER: /space
      SB_INDEX_PAGE: index
      # SB_READ_ONLY: true
      # SB_USER: admin:admin
      # SB_LOG_PUSH: 1
      # SB_DISABLE_SERVICE_WORKER: 1
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --timeout=3 --spider http://127.0.0.1:3000/ || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.silverbullet-rtr.entrypoints: "websecure"
      traefik.http.routers.silverbullet-rtr.rule: "Host(`notes.$DOMAINNAME`)"
      ## Middlewares
      # traefik.http.routers.silverbullet-rtr.middlewares: chain-silverbullet-no-auth@file
      traefik.http.routers.silverbullet-rtr.middlewares: "chain-silverbullet-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.silverbullet-rtr.service: "silverbullet-svc"
      traefik.http.services.silverbullet-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.silverbullet.config.domain: "notes.$DOMAINNAME"
      tinyauth.apps.silverbullet.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Reading"
      homepage.name: "silverbullet"
      homepage.icon: "silverbullet.png"
      homepage.href: "https://notes.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
      ####### GLANCE #######
      glance.name: "silverbullet"
      glance.icon: "sh:silverbullet"
      glance.url: "https://notes.$DOMAINNAME"
      glance.description: "Offline first web based Markdown editor, turbo charged with the scripting power of Lua"
