services:
  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: lscr.io/linuxserver/socket-proxy:latest
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
    profiles:
      - core
    networks:
      socket_proxy:
        ipv4_address: 192.168.91.254 # You can specify a static IP
    privileged: true
    ports:
      # - "127.0.0.1:2375:2375"
      - "2375:2375" # NOTE: Use this if you want to expose docker socket in LAN.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOG_LEVEL: info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access. 1 to grant access.
      ALLOW_START: 0
      ALLOW_STOP: 0
      ALLOW_RESTARTS: 0
      AUTH: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1 # For Homepage, Dozzle, Arcane
      DISABLE_IPV6: 0
      DISTRIBUTION: 0
      EVENTS: 1
      EXEC: 1 # For Arcane
      IMAGES: 1 # For Arcane
      INFO: 1  # For Dozzle, Arcane
      NETWORKS: 1 # For Arcane
      NODES: 0
      PING: 1
      PLUGINS: 0
      POST: 1 # For Arcane
      PROXY_READ_TIMEOUT: 240
      SECRETS: 0
      SERVICES: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 0
      VERSION: 1
      VOLUMES: 1 # For Arcane
