services:
  # Set url_base in the settings if using PathPrefix
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.17.2952-ls308@sha256:e6c9a091735fede0c2a205c69e7d4c2f0188eaf2bec7e42d8a26c017e5f2a910
    container_name: sonarr
    restart: $RESTART_POLICY_MEDIA
    # profiles:
    # - media
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.167
    security_opt:
      - no-new-privileges:true
    # ports:
    #  - "$SONARR_PORT:8989"
    volumes:
      - $REPO_PATH/appdata/sonarr:/config
      # Optional. See why MediaCover is mounted as volume https://github.com/htpcBeginner/docker-traefik/discussions/147
      - $REPO_PATH/data/sonarr/MediaCover:/config/MediaCover
      - $REPO_PATH/data/downloads:/data/downloads
      - $REPO_PATH/data/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      # HTTP Routers Auth Bypass
      traefik.http.routers.sonarr-rtr-bypass.entrypoints: "websecure"
      #- "traefik.http.routers.sonarr-rtr-bypass.rule=Host(`sonarr.$DOMAINNAME`) && (Header(`X-Api-Key`, `$SONARR_API_KEY`) || Query(`apikey`, `$SONARR_API_KEY`))"
      traefik.http.routers.sonarr-rtr-bypass.rule: "Host(`sonarr.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth
      traefik.http.routers.sonarr-rtr-bypass.priority: "100"
      # HTTP Routers Auth
      traefik.http.routers.sonarr-rtr.entrypoints: "websecure"
      traefik.http.routers.sonarr-rtr.rule: "Host(`sonarr.$DOMAINNAME`)"
      traefik.http.routers.sonarr-rtr.priority: "99"
      # Middlewares
      traefik.http.routers.sonarr-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.sonarr-rtr-bypass.middlewares: "chain-no-auth@file"
      # HTTP Services
      traefik.http.routers.sonarr-rtr.service: "sonarr-svc"
      traefik.http.routers.sonarr-rtr-bypass.service: "sonarr-svc"
      traefik.http.services.sonarr-svc.loadbalancer.server.port: "8989"
      ####### TINYAUTH #######
      tinyauth.apps.sonarr.config.domain: "sonarr.$DOMAINNAME"
      tinyauth.apps.sonarr.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Sonarr"
      homepage.icon: "sonarr.svg"
      homepage.href: "https://sonarr.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "TV Show Manager"
    profiles:
      - media
      - arr
