# NOTE: Dashboard images not working on Firefox
# TODO: If possible, serve api in port 11470 using PathPrefix(`/api/`) to avoid CORS workaround with the web app.
# TODO: Self Host AIOmetadata
services:
  stremio:
    image: tsaridas/stremio-docker:v1.3.6@sha256:f0de8290286b08e1c98ac875cba5c2ec62c6603f2b81b444ff850f63c2810eda
    container_name: stremio
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - media
      - arr
    networks:
      - t3_proxy
    expose:
      - "8080" # web
      - "11470" # api
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp:uid=$PUID,gid=$PGID,mode=1777
      - /run:uid=$PUID,gid=$PGID,mode=775
      - /run/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/lib/nginx:uid=$PUID,gid=$PGID,mode=775
      - /var/lib/nginx/logs:uid=$PUID,gid=$PGID,mode=775
      - /var/lib/nginx/tmp:uid=$PUID,gid=$PGID,mode=775
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/configs/stremio:/.stremio-server
      - $REPO_PATH/appdata/stremio:/srv/stremio-server
    environment:
      NO_CORS: 1
      APP_PATH: /.stremio-server
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--timeout=3", "--spider", "http://127.0.0.1:8080/"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 1m
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth - Web UI
      traefik.http.routers.stremio-rtr.entrypoints: "websecure"
      traefik.http.routers.stremio-rtr.rule: "Host(`stremio.$DOMAINNAME`)"
      ## Middlewares - Web UI
      traefik.http.routers.stremio-rtr.middlewares: "chain-tinyauth-original@file"
      ## HTTP Services - Web UI
      traefik.http.routers.stremio-rtr.service: "stremio-svc"
      traefik.http.services.stremio-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.stremio.config.domain: "stremio.$DOMAINNAME"
      tinyauth.apps.stremio.ip.bypass: "$LOCAL_IPS"
      ## HTTP Routers - API
      traefik.http.routers.stremio-api-rtr.entrypoints: "websecure"
      traefik.http.routers.stremio-api-rtr.rule: "Host(`stremio-api.$DOMAINNAME`)"
      ## Middlewares - API
      traefik.http.routers.stremio-api-rtr.middlewares: "cors-stremio,chain-tinyauth@file"
      # traefik.http.routers.stremio-api-rtr.middlewares: "cors-stremio,chain-no-auth@file"
      ## HTTP Services - API
      traefik.http.routers.stremio-api-rtr.service: "stremio-api-svc"
      traefik.http.services.stremio-api-svc.loadbalancer.server.port: "11470"
      ## CORS Middleware Definition for API
      traefik.http.middlewares.cors-stremio.headers.accessControlAllowCredentials: "false"
      traefik.http.middlewares.cors-stremio.headers.accessControlAllowHeaders: "*"
      traefik.http.middlewares.cors-stremio.headers.accessControlAllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
      traefik.http.middlewares.cors-stremio.headers.accessControlAllowOriginList: "https://stremio.$DOMAINNAME"
      traefik.http.middlewares.cors-stremio.headers.accessControlMaxAge: "86400"
      traefik.http.middlewares.cors-stremio.headers.addVaryHeader: "true"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Stremio"
      homepage.icon: "stremio.svg"
      homepage.href: "https://stremio.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Online Streaming Platform"
      ####### GLANCE #######
      glance.name: Stremio
      glance.icon: sh:stremio
      glance.url: https://stremio.$DOMAINNAME
      glance.description: Online Streaming Platform

  stremio-server:
    image: stremio/server:v4.20.18@sha256:93aaee2de288456e2394028eab3125cfe66ea86cb3e0f286e0406124a7efbc2d
    container_name: stremio-server
    restart: $RESTART_POLICY_MEDIA
    profiles:
      # - media
      # - arr
      - not-used
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/stremio-server:/.stremio-server
    environment:
      NO_CORS: 1
      APP_PATH: /.stremio-server
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 --timeout=3 --spider http://127.0.0.1:11470/settings || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 1m
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.stremio-server-rtr.entrypoints: "websecure"
      traefik.http.routers.stremio-server-rtr.rule: "Host(`stremio-server.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.stremio-server-rtr.middlewares: "chain-tinyauth-relaxed@file" # NOTE: Not working currently
      ## HTTP Services
      traefik.http.routers.stremio-server-rtr.service: "stremio-server-svc"
      traefik.http.services.stremio-server-svc.loadbalancer.server.port: "11470"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Stremio"
      homepage.icon: "stremio.svg"
      homepage.href: "https://stremio-server.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Online Streaming Platform"
      tinyauth.apps.stremio-server.config.domain: stremio-server.$DOMAINNAME
      tinyauth.apps.stremio-server.ip.bypass: $LOCAL_IPS
      ####### GLANCE #######
      glance.name: Stremio
      glance.icon: sh:stremio-server
      glance.url: https://stremio-server.$DOMAINNAME
      glance.description: Online Streaming Platform
