# TODO: Harden
# NOTE: 22000:22000/tcp port is probably needed for other devices to see this device.
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:v2.0.16-ls214@sha256:de6958feb8caf81217832744ae9a4843efbb4dd432c6cea90077ed7a0cf97fc3
    container_name: syncthing
    restart: $RESTART_POLICY_OTHERS
    profiles:
      - maintenance
    networks:
      - t3_proxy
    ports:
      - 22000:22000/tcp # TCP file transfers
    #   - 8384:8384 # Web UI
    #   - 22000:22000/udp # QUIC file transfers
    #   - 21027:21027/udp # Receive local discovery broadcasts
    security_opt:
      - no-new-privileges:true
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/syncthing:/config
      - $DIR_NOTES/Markdown:/notes
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:8384/rest/noauth/health | grep -q OK"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.syncthing-rtr.entrypoints: "websecure"
      traefik.http.routers.syncthing-rtr.rule: "Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.syncthing-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.syncthing-rtr.service: "syncthing-svc"
      traefik.http.services.syncthing-svc.loadbalancer.server.port: "8384"
      ####### TINYAUTH #######
      tinyauth.apps.syncthing.config.domain: "syncthing.$DOMAINNAME"
      tinyauth.apps.syncthing.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Syncthing"
      homepage.icon: "syncthing.svg"
      homepage.href: "https://syncthing.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "File Synchronization"
      homepage.widget.type: "customapi"
      homepage.widget.url: "http://syncthing:8384/rest/svc/report"
      homepage.widget.headers.X-API-Key: "$SYNCTHING_API_KEY"
      homepage.widget.mappings.0.field: "numDevices"
      homepage.widget.mappings.0.label: "Devices"
      homepage.widget.mappings.0.format: "number"
      homepage.widget.mappings.1.field: "numFolders"
      homepage.widget.mappings.1.label: "Folders"
      homepage.widget.mappings.1.format: "number"
      homepage.widget.mappings.2.field: "totFiles"
      homepage.widget.mappings.2.label: "Files"
      homepage.widget.mappings.2.format: "number"
      homepage.widget.mappings.3.field: "totMiB"
      homepage.widget.mappings.3.label: "MB"
      homepage.widget.mappings.3.format: "number"
      ####### GLANCE #######
      glance.name: "syncthing"
      glance.icon: "sh:syncthing"
      glance.url: "https://syncthing.$DOMAINNAME"
      glance.description: "File Synchronization"
