services:
  termix:
    image: ghcr.io/lukegus/termix:latest@sha256:6fe521f60ac4e3b85d80b3c3d496ae955d2968c7b0f0e1fcecc8f54b56381aee
    container_name: termix
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/termix:/app/data
    environment:
      PORT: "8080"
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.termix-rtr.entrypoints: "websecure"
      traefik.http.routers.termix-rtr.rule: "Host(`ssh.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.termix-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.termix-rtr.service: "termix-svc"
      traefik.http.services.termix-svc.loadbalancer.server.port: "8080"
      ####### TINYAUTH #######
      tinyauth.apps.termix.config.domain: "ssh.$DOMAINNAME"
      tinyauth.apps.termix.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "termix"
      homepage.icon: "termix.png"
      homepage.href: "https://ssh.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A web-based server management platform with SSH terminal, tunneling, and file editing capabilities."
      ####### GLANCE #######
      glance.name: "termix"
      glance.icon: "sh:termix"
      glance.url: "https://ssh.$DOMAINNAME"
      glance.description: "A web-based server management platform with SSH terminal, tunneling, and file editing capabilities."
