# Create user: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 user create --interactive
# Create SECRET: openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
# Create TOTP: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 totp generate --interactive
services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v4
    container_name: tinyauth
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      DOCKER_HOST: "tcp://docker-socket-proxy:2375"
      # DOCKER_API_VERSION: 1.48
      APP_TITLE: Single Sign-On
      APP_URL: https://tinyauth.$DOMAINNAME
      SECURE_COOKIE: "true"
      LOG_LEVEL: "info"
      DISABLE_ANALYTICS: "false"
      USERS: $TINYAUTH_USERS
      # USERS_FILE: users_file
      LOGIN_MAX_RETRIES: 5
      ## OIDC CLIENT CONFIGURATION
      PROVIDERS_POCKETID_NAME: PocketID
      PROVIDERS_POCKETID_CLIENT_ID: $TINYAUTH_CLIENT_ID
      PROVIDERS_POCKETID_CLIENT_SECRET: $TINYAUTH_CLIENT_SECRET
      PROVIDERS_POCKETID_AUTH_URL: https://pocketid.$BASE_DOMAINNAME/authorize
      PROVIDERS_POCKETID_TOKEN_URL: https://pocketid.$BASE_DOMAINNAME/api/oidc/token
      PROVIDERS_POCKETID_USER_INFO_URL: https://pocketid.$BASE_DOMAINNAME/api/oidc/userinfo
      PROVIDERS_POCKETID_SCOPES: openid email profile groups
      PROVIDERS_POCKETID_INSECURE_SKIP_VERIFY: "true"
      # OAUTH_AUTO_REDIRECT: generic # To automatically redirected to Pocket ID
      # OAUTH_WHITELIST: $POCKETID_WHITELIST_USERS
      ## ACL Env example
      # TINYAUTH_APPS_WHOAMI_CONFIG_DOMAIN: whoami.example.com
      # TINYAUTH_APPS_WHOAMI_USERS_ALLOW: john
    volumes:
      - $REPO_PATH/data/tinyauth:/data
      # - $REPO_PATH/secrets/tinyauth_users:/tinyauth/users_file
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.tinyauth-rtr.entrypoints: "websecure"
      traefik.http.routers.tinyauth-rtr.rule: "Host(`tinyauth.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.tinyauth-rtr.middlewares: "chain-no-auth@file"
      ## Forward Auth - Commented out because it is handled inside treafik middleware chain file
      # - "traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "tinyauth"
      homepage.icon: "tinyauth.png"
      homepage.href: "https://tinyauth.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "The simplest way to protect your apps with a login screen"
      ####### GLANCE #######
      glance.name: "tinyauth"
      glance.icon: "sh:tinyauth"
      glance.url: "https://tinyauth.$DOMAINNAME"
      glance.description: "The simplest way to protect your apps with a login screen"
