# Create user: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v5 user create --interactive
# Create SECRET: openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
# Create TOTP: docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v5 totp generate --interactive
services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5
    container_name: tinyauth
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
      - socket_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    # https://tinyauth.app/docs/reference/configuration/
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy-read:2375
      ## General Configuration
      TINYAUTH_APPURL: https://tinyauth.$DOMAINNAME
      ## Analytics Configuration
      TINYAUTH_ANALYTICS_ENABLED: false
      ## Authentication Configuration
      TINYAUTH_AUTH_IP_ALLOW: $LOCAL_IPS
      # TINYAUTH_AUTH_IP_BLOCK: ""
      TINYAUTH_AUTH_USERS: $TINYAUTH_USERS
      TINYAUTH_AUTH_SECURECOOKIE: true
      TINYAUTH_AUTH_LOGINMAXRETRIES: 3
      ## ACLs Configuration
      # TINYAUTH_APPS_WHOAMI_CONFIG_DOMAIN: whoami.example.com
      # TINYAUTH_APPS_WHOAMI_USERS_ALLOW: john
      ## OAuth Configuration
      # TINYAUTH_OAUTH_WHITELIST: $POCKETID_WHITELIST_USERS
      # TINYAUTH_OAUTH_AUTOREDIRECT: pocketid # Auto redirect to PocketID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: PocketID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: $TINYAUTH_CLIENT_ID
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: $TINYAUTH_CLIENT_SECRET
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://pocketid.$BASE_DOMAINNAME/authorize
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://pocketid.$BASE_DOMAINNAME/api/oidc/token
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://pocketid.$BASE_DOMAINNAME/api/oidc/userinfo
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: openid email profile groups
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_INSECURE: true
      ## OIDC Configuration
      # TINYAUTH_OIDC_CLIENTS_WHOAMI_CLIENTID: replace-me-with-a-random-string
      # TINYAUTH_OIDC_CLIENTS_WHOAMI_CLIENTSECRET: replace-me-with-a-random-string
      # TINYAUTH_OIDC_CLIENTS_WHOAMI_TRUSTEDREDIRECTURIS: https://whoami.$DOMAINNAME/callback
      # TINYAUTH_OIDC_CLIENTS_WHOAMI_NAME: My WHOAMI App
      ## UI Configuration
      TINYAUTH_UI_TITLE: Single Sign-On
      # TINYAUTH_UI_BACKGROUNDIMAGE: ""
      ## Logging Configuration
      TINYAUTH_LOG_LEVEL: info
    volumes:
      - $REPO_PATH/data/tinyauth:/data
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.tinyauth-rtr.entrypoints: "websecure"
      traefik.http.routers.tinyauth-rtr.rule: "Host(`tinyauth.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.tinyauth-rtr.middlewares: "chain-no-auth@file"
      ## Forward Auth - Commented out because it is handled inside treafik middleware chain file
      # - "traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "tinyauth"
      homepage.icon: "tinyauth.png"
      homepage.href: "https://tinyauth.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "The simplest way to protect your apps with a login screen"
      ####### GLANCE #######
      glance.name: "tinyauth"
      glance.icon: "sh:tinyauth"
      glance.url: "https://tinyauth.$DOMAINNAME"
      glance.description: "The simplest way to protect your apps with a login screen"
