# TODO: Harden
services:
  # Diffent GUIs in web home:
  # /combustion-release/ -- /transmission-web-control/ -- /kettu/ -- /flood-for-transmission/
  transmission:
    image: lscr.io/linuxserver/transmission:4.1.1-r1-ls340@sha256:dd888c17f97eca1a2dda4aa7986c9080fe1b69a61aef845440f1bd9285aa3708
    container_name: transmission
    restart: $RESTART_POLICY_MEDIA
    profiles:
      - root
      - media
      - arr
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.160
    ports:
      - "487:487"
      # - "51413:51413"
    security_opt:
      - no-new-privileges:true
    pids_limit: 256
    cpus: '1.0'
    mem_limit: "4096M"
    mem_reservation: "4096M"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/transmission:/config
      - $DIR_MEDIA/Downloads:/data/downloads
      # - $DIR_MEDIA/Downloads/test:/downloads
      # If not set, tranmission creates reduntant volumes
      - $DIR_MEDIA/Downloads/torrent_files:/watch
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    healthcheck:
      test: ["CMD", "transmission-remote", "127.0.0.1:9091", "--session-info"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.transmission-rtr.entrypoints: "websecure"
      traefik.http.routers.transmission-rtr.rule: "Host(`torrent.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.transmission-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.transmission-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.transmission-rtr.service: "transmission-svc"
      traefik.http.services.transmission-svc.loadbalancer.server.port: "9091"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "Transmission"
      homepage.icon: "transmission.svg"
      homepage.href: "https://torrent.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Torrent Client"
      homepage.widget.type: "transmission"
      homepage.widget.url: "http://transmission:9091"
      ####### GLANCE #######
      glance.name: Transmission
      glance.icon: sh:transmission
      glance.url: https://torrent.$DOMAINNAME
      glance.description: Torrent Client
