services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: $RESTART_POLICY_MEDIA
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/tubesync:/config
      - $DIR_MEDIA/Youtube:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # - HTTP_USER=admin
      # - HTTP_PASS=admin
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.tubesync-rtr.entrypoints: "websecure"
      traefik.http.routers.tubesync-rtr.rule: "Host(`tubesync.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.tubesync-rtr.middlewares: "chain-tinyauth@file"
      #      - "traefik.http.routers.transmission-rtr.middlewares=middlewares-rate-limit@file"
      ## HTTP Services
      traefik.http.routers.tubesync-rtr.service: "tubesync-svc"
      traefik.http.services.tubesync-svc.loadbalancer.server.port: "4848"
      ####### TINYAUTH #######
      tinyauth.apps.tubesync.config.domain: "tubesync.$DOMAINNAME"
      tinyauth.apps.tubesync.ip.bypass: "$LOCAL_IPS"
    profiles:
      - media
