# NOTE: argod2id token generation (don't forget to add extra $ in the password)
# docker exec -it vaultwarden /vaultwarden hash
services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.0@sha256:e6443e3d5ed8fcee2204b89ec778d7f24d0173bcc42d1ea34f990304f5f63f51
    container_name: vaultwarden
    restart: $RESTART_POLICY_CORE
    profiles:
      - core
    networks:
      - t3_proxy
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/data/vaultwarden:/data/
    environment:
      ADMIN_TOKEN: $VAULTWARDEN_ADMIN_TOKEN
      DATA_FOLDER: data
      DOMAIN: https://vaultwarden.$DOMAINNAME
      TRASH_AUTO_DELETE_DAYS: 30
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: false
      SIGNUPS_DOMAINS_WHITELIST: $BASE_DOMAINNAME
      EMAIL_CHANGE_ALLOWED: false
      REQUIRE_DEVICE_EMAIL: false
      LOG_LEVEL: info
      # LOG_LEVEL: info,vaultwarden::sso=debug
      SMTP_DEBUG: false
      ## OIDC
      SSO_ENABLED: true
      SSO_ONLY: false
      SSO_SIGNUPS_MATCH_EMAIL: true
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: false
      SSO_AUTHORITY: https://pocketid.$BASE_DOMAINNAME
      SSO_SCOPES: openid profile email
      SSO_PKCE: true
      SSO_CLIENT_ID: $VAULTWARDEN_CLIENT_ID
      SSO_CLIENT_SECRET: $VAULTWARDEN_CLIENT_SECRET
      SSO_CLIENT_CACHE_EXPIRATION: 0
      SSO_DEBUG_TOKENS: false
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1/alive >/dev/null || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.vaultwarden-rtr.entrypoints: "websecure"
      traefik.http.routers.vaultwarden-rtr.rule: "Host(`vaultwarden.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.vaultwarden-rtr.middlewares: "chain-tinyauth@file"
      # traefik.http.routers.vaultwarden-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Services
      traefik.http.routers.vaultwarden-rtr.service: "vaultwarden-svc"
      traefik.http.services.vaultwarden-svc.loadbalancer.server.port: "80"
      ####### HOMEPAGE #######
      homepage.group: "Core"
      homepage.name: "Vaultwarden"
      homepage.icon: "vaultwarden.svg"
      homepage.href: "https://vaultwarden.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Password Manager"
      ####### GLANCE #######
      glance.name: "Vaultwarden"
      glance.icon: "sh:vaultwarden"
      glance.url: "https://vaultwarden.$DOMAINNAME"
      glance.description: "Password Manager"
