services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.140.0@sha256:5ea06e3a567249f8a23181208755f36dabd3b515f7023e9eb570fd4ae6c29203
    container_name: victoriametrics
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
      - crowdsec
    networks:
      - crowdsec_lapi
    expose:
      - 8428
    # TODO: Should we expose this or use traefik?
    ports:
      - "8428:8428"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 1G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/victoriametrics:/victoria-metrics-data
    command:
      - "--storageDataPath=/victoria-metrics-data"
      - "--httpListenAddr=:8428"
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "victoriametrics"
      homepage.icon: "victoriametrics.png"
      homepage.target: "_blank"
      homepage.description: "Fast, cost-effective monitoring solution and time series database"
      ####### GLANCE #######
      glance.name: "victoriametrics"
      glance.icon: "sh:victoriametrics"
      glance.description: "Fast, cost-effective monitoring solution and time series database"
