services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.138.0@sha256:b9b667f6709f20044328ddefae8869c56ced840ebafdf89bc3bba1f28f2d7e60
    container_name: victoriametrics
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
      - crowdsec
    networks:
      - crowdsec_lapi
    expose:
      - 8428
    # TODO: Should we expose this or use traefik?
    ports:
      - "8428:8428"
    user: $PUID:$PGID
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    volumes:
      - $REPO_PATH/appdata/victoriametrics:/victoria-metrics-data
    command:
      - "--storageDataPath=/victoria-metrics-data"
      - "--httpListenAddr=:8428"
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "victoriametrics"
      homepage.icon: "victoriametrics.png"
      homepage.target: "_blank"
      homepage.description: "Fast, cost-effective monitoring solution and time series database"
      ####### GLANCE #######
      glance.name: "victoriametrics"
      glance.icon: "sh:victoriametrics"
      glance.description: "Fast, cost-effective monitoring solution and time series database"
