services:
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - maintenance
    security_opt:
      - no-new-privileges:true
    # cap_add:
    #   - IPC_LOCK
    # shm_size: "1gb"
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/vscodium:/config
      - $REPO_PATH:/config/workspace/docker
      - $DIR_NOTES:/config/workspace/notes
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.vscodium-rtr.entrypoints: "websecure"
      traefik.http.routers.vscodium-rtr.rule: "Host(`vscodium.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.vscodium-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.vscodium-rtr.service: "vscodium-svc"
      traefik.http.services.vscodium-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.vscodium.config.domain: "vscodium.$DOMAINNAME"
      tinyauth.apps.vscodium.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "VSCodium"
      homepage.icon: "vscode.svg"
      homepage.href: "https://vscodium.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Code Editor"
