# TODO: Harden
services:
  vscodium:
    image: lscr.io/linuxserver/vscodium:1.116.02821@sha256:5db09ef55a62175a848a848efe9d7e645608a73c796f11c761e24e246f3ca6a8
    container_name: vscodium
    restart: $RESTART_POLICY_PROGRAMMING
    profiles:
      - programming
      - desktop_apps
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # NOTE: Required for keyring functionality.
    cap_add:
      - IPC_LOCK
    shm_size: "1gb"
    pids_limit: 256
    cpus: '1.0'
    mem_limit: 4G
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    volumes:
      - $REPO_PATH/appdata/vscodium:/config
      - $REPO_PATH:/config/workspace/docker
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Vscode
      PIXELFLUX_WAYLAND: true
      # DRI_NODE: /dev/dri/renderD128 # NOTE: Don't set this. It breaks HW.
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --max-time 3 http://127.0.0.1:3000/ >/dev/null || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 1m
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.vscodium-rtr.entrypoints: "websecure"
      traefik.http.routers.vscodium-rtr.rule: "Host(`code.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.vscodium-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.vscodium-rtr.service: "vscodium-svc"
      traefik.http.services.vscodium-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.vscodium.config.domain: "code.$DOMAINNAME"
      tinyauth.apps.vscodium.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Programming"
      homepage.name: "VSCodium"
      homepage.icon: "vscode.svg"
      homepage.href: "https://code.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Code Editor"
      ####### GLANCE #######
      glance.name: "VSCodium"
      glance.icon: "sh:vscodium"
      glance.url: "https://code.$DOMAINNAME"
      glance.description: "Code Editor"
    # For Nvidia Zero Copy Rendering
    group_add:
      # - "44" # video
      - "992" # render
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, graphics, utility]
