services:
  #  Optional, local themes and icons
  wyl-node-bootstrap:
    image: ghcr.io/aceberg/node-bootstrap:latest
    container_name: node-bootstrap
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
    networks:
      - t3_proxy
    ports:
      - 8850:8850

  watchyourlan:
    image: ghcr.io/aceberg/watchyourlan:latest
    container_name: watchyourlan
    restart: $RESTART_POLICY_MAINTENANCE
    profiles:
      - monitoring
    # command: "-n http://$LOCAL_STATIC_IP:8850"
    command: "-n https://lan.$DOMAINNAME"
    depends_on:
      - wyl-node-bootstrap
    network_mode: "host"
    expose:
      - 8840
    volumes:
      - $REPO_PATH/appdata/watchyourlan:/data/WatchYourLAN
    environment:
      TZ: $TZ
      IFACES: $NETWORK_INTERFACE_NAMES # required: 1 or more interface
      HOST: 0.0.0.0
      PORT: 8840
      TIMEOUT: 120
      SHOUTRRR_URL: "" # optional
      THEME: "sand" # optional
      COLOR: "dark" # optional
    labels:
      ####### HOMEPAGE #######
      homepage.group: "Monitoring"
      homepage.name: "WatchYourLAN"
      homepage.icon: "watchyourlan.svg"
      homepage.href: "https://watchyourlan.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Network Device Monitor"