services:
  webtop:
    container_name: webtop
    # image: lscr.io/linuxserver/webtop:debian-i3
    image: lscr.io/linuxserver/webtop:debian-kde
    restart: $RESTART_POLICY_DESKTOP_IMAGES
    shm_size: "1gb"
    mem_limit: 6g
    profiles:
      - desktop_apps
    privileged: true
    # security_opt:
    #   # - no-new-privileges:true
    #   - seccomp:unconfined
    networks:
      - t3_proxy
    volumes:
      - $REPO_PATH/appdata/webtop:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TITLE: Debian on the Browser
      PIXELFLUX_WAYLAND: true
      # DRI_NODE: /dev/dri/renderD128 # NOTE: Don't set this. It breaks HW.
      DISABLE_ZINK: true
      DISABLE_IPV6: true
      DISABLE_DRI3: true
      # Linuxserver Docker Mods
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: htop|nvtop
      # Selkies related variables
      # SELKIES_USE_CPU: "False|locked"
      SHELL: /bin/bash
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.webtop-rtr.entrypoints: "websecure"
      traefik.http.routers.webtop-rtr.rule: "Host(`kde.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.webtop-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.webtop-rtr.service: "webtop-svc"
      traefik.http.services.webtop-svc.loadbalancer.server.port: "3000"
      ####### TINYAUTH #######
      tinyauth.apps.webtop.config.domain: "kde.$DOMAINNAME"
      tinyauth.apps.webtop.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "DesktopApps"
      homepage.name: "Webtop"
      homepage.icon: "webtop.svg"
      homepage.href: "https://kde.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Debian Desktop in Browser"
    # For Nvidia Zero Copy Rendering
    group_add:
      # - "44" # video
      - "992" # render
    devices:
      # - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video, graphics, display]