services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: $MAINTENANCE_RESTART_POLICY
    profiles:
      - maintenance
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.whoami-rtr.entrypoints: "websecure"
      traefik.http.routers.whoami-rtr.rule: "Host(`whoami.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.whoami-rtr.middlewares: "chain-tinyauth@file"
      # - "tinyauth.oauth.groups=admins" # NOTE: Not working currently
      ## HTTP Services
      traefik.http.routers.whoami-rtr.service: "whoami-svc"
      traefik.http.services.whoami-svc.loadbalancer.server.port: "80"
      ####### TINYAUTH #######
      tinyauth.apps.whoami.config.domain: "whoami.$DOMAINNAME"
      tinyauth.apps.whoami.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Maintenance"
      homepage.name: "Whoami"
      homepage.icon: "whoami.svg"
      homepage.href: "https://whoami.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "Tiny Go webserver that prints OS information and HTTP request to output"
      ####### GLANCE #######
      glance.name: "whoami"
      glance.icon: "sh:whoami"
      glance.url: "https://whoami.$DOMAINNAME"
      glance.description: "Tiny Go webserver that prints OS information and HTTP request to output"
