# NOTE: Create folders before starting the container
# mkdir $REPO_PATH/appdata/ytptube
# mkdir $REPO_PATH/logs/ytptube
services:
  ytptube:
    image: ghcr.io/arabcoders/ytptube:latest@sha256:eb043fe0b0037b6d4998de08ed3499adb1043ebe060d2b675f8382c145b226b3
    container_name: ytptube
    restart: $RESTART_POLICY_MEDIA
    user: $PUID:$PGID
    profiles:
      - media
      - youtube
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $REPO_PATH/appdata/ytptube:/config:rw
      - $REPO_PATH/logs/ytptube:/config/logs:rw
      - $DIR_MEDIA/Youtube:/downloads:rw
    tmpfs:
      - /tmp
    environment:
      YTP_PORT: 8081
      YTP_DOWNLOAD_PATH: "/downloads"
      YTP_INSTANCE_TITLE: "Youtube Downloader"
      YTP_OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
      YTP_LOG_LEVEL: "info"
      YTP_BROWSER_ENABLED: "false"
      YTP_YTDLP_AUTO_UPDATE: "true"
    labels:
      traefik.enable: "true"
      ## HTTP Routers Auth
      traefik.http.routers.ytptube-rtr.entrypoints: "websecure"
      traefik.http.routers.ytptube-rtr.rule: "Host(`ytptube.$DOMAINNAME`)"
      ## Middlewares
      traefik.http.routers.ytptube-rtr.middlewares: "chain-tinyauth@file"
      ## HTTP Services
      traefik.http.routers.ytptube-rtr.service: "ytptube-svc"
      traefik.http.services.ytptube-svc.loadbalancer.server.port: "8081"
      ####### TINYAUTH #######
      tinyauth.apps.ytptube.config.domain: "ytptube.$DOMAINNAME"
      tinyauth.apps.ytptube.ip.bypass: "$LOCAL_IPS"
      ####### HOMEPAGE #######
      homepage.group: "Media"
      homepage.name: "ytptube"
      homepage.icon: "ytptube.svg"
      homepage.href: "https://ytptube.$DOMAINNAME"
      homepage.target: "_blank"
      homepage.description: "A Web Frontend for yt-dlp, youtube downloader"
      ####### GLANCE #######
      glance.name: "ytptube"
      glance.icon: "sh:ytptube"
      glance.url: "https://ytptube.$DOMAINNAME"
      glance.description: "A Web Frontend for yt-dlp, youtube downloader"
