name: ml

networks:
  t2_proxy:
    external: true

x-deploy: &gpu-deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, utility]
            # capabilities: [compute, utility]

services:
  stable-diffusion:
    container_name: stable-diffusion
    build: $GITHUBREPOSDIR/stable-diffusion-webui-docker/services/AUTOMATIC1111
    image: stablediff-auto:71
    restart: $ML_RESTART_POLICY
    # compute, utility
    <<: *gpu-deploy
    stop_signal: SIGINT
    tty: true
    networks:
      - t2_proxy
    volumes:
      - $GITHUBREPOSDIR/stable-diffusion-webui-docker/data:/data
      - $GITHUBREPOSDIR/stable-diffusion-webui-docker/output:/output
      # - $GITHUBREPOSDIR/stable-diffusion-webui-docker/services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
    environment:
      # - ATTN_PRECISION=fp16
      - CLI_ARGS=--allow-code --enable-insecure-extension-access --medvram-sdxl # --api --xformers --no-half-vae
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.stablediffusion-rtr.entrypoints=https"
      - "traefik.http.routers.stablediffusion-rtr.rule=Host(`stablediffusion.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.stablediffusion-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.stablediffusion-rtr.service=stablediffusion-svc"
      - "traefik.http.services.stablediffusion-svc.loadbalancer.server.port=7860"

  sd-next:
    container_name: sd-next
    image: holaflenain/stable-diffusion:latest
    restart: $ML_RESTART_POLICY
    <<: *gpu-deploy
    # runtime: nvidia # NOTE: Not working
    networks:
      - t2_proxy
    ports:
      - "9999:9000/tcp"
    volumes:
      - $DOCKERDIR/appdata/sd-next:/config:rw
      - $MLMODELSDIR:/config/models/stable-diffusion:ro
    environment:
      - WEBUI_VERSION=04
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      # - CLEAN_ENV=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sdnext-rtr.entrypoints=https"
      - "traefik.http.routers.sdnext-rtr.rule=Host(`sdnext.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.sdnext-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.sdnext-rtr.service=sdnext-svc"
      - "traefik.http.services.sdnext-svc.loadbalancer.server.port=9000"

  whisper-api:
    container_name: whisper-api
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: $ML_RESTART_POLICY
    <<: *gpu-deploy
    networks:
      - t2_proxy
    # ports:
    #   - "9000:9000"
    volumes:
      - $DOCKERDIR/appdata/whisper-api:/app
    environment:
      - ASR_MODEL=base 
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whisper-api-rtr.entrypoints=https"
      - "traefik.http.routers.whisper-api-rtr.rule=Host(`whisperapi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.whisper-api-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.whisper-api-rtr.service=whisper-api-svc"
      - "traefik.http.services.whisper-api-svc.loadbalancer.server.port=9000"

  ## NOTE: If you don't have ChatML-tuned models, you must use openapi-server
  llama-cpp-server:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    container_name: llama-cpp-server
    restart: $ML_RESTART_POLICY
    <<: *gpu-deploy
    networks:
      - t2_proxy
    environment:
      LLAMA_ARG_HOST: 0.0.0.0
      LLAMA_ARG_PORT: 8000
      LLAMA_ARG_MODEL: /models/tinyllma-1.1b-chat-v1.0.Q8_0.gguf
      LLAMA_ARG_ALIAS: tinyllma-1.1b-chat-v1.0.Q8_0.gguf
      LLAMA_ARG_CTX_SIZE: 4096
      LLAMA_ARG_N_GPU_LAYERS: 10
      LLAMA_ARG_FLASH_ATTN: 1
      LLAMA_ARG_N_PREDICT: -1 # infinity
      LLAMA_ARG_NO_WEBUI: 0
      # LLAMA_ARG_ENDPOINT_METRICS: 1
      # HF_TOKEN: $HF_TOKEN
    volumes:
     - "$MLMODELSDIR/LLM:/models:ro"
    healthcheck:
      test: "curl -f http://llama-cpp:8000/health"
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.llama-cpp-server-rtr.entrypoints=https"
      - "traefik.http.routers.llama-cpp-server-rtr.rule=Host(`llamapi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.llama-cpp-server-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.llama-cpp-server-openapi-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.llama-cpp-server-rtr.service=llama-cpp-server-svc"
      - "traefik.http.services.llama-cpp-server-svc.loadbalancer.server.port=8000"

  # FIXME: No API key found error when using inside open-webui
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: $ML_RESTART_POLICY
    networks:
      - t2_proxy
    # ports:
    #   - "8080:8080"
    volumes:
      - $DOCKERDIR/appdata/searxng:/etc/searxng   

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest # :ollama
    restart: $ML_RESTART_POLICY
    # depends_on:
    #   - searxng
    # <<: *gpu-deploy
    networks:
      - t2_proxy
    # ports:
    #   - "9000:9000"
    volumes:
      - $DOCKERDIR/appdata/open-webui:/app/backend/data
      # - ollama:/root/.ollama
    environment:
      # - WEBUI_AUTH=False
      - OPENAI_API_KEY=$OPENAI_API_KEY
      # - OPENAI_API_BASE_URLS="https://api.openai.com/v1;URL2"
      # - OPENAI_API_KEYS="KEY1;KEY2"
      # - ENABLE_RAG_WEB_SEARCH=True
      # - RAG_WEB_SEARCH_ENGINE="searxng"
      # - RAG_WEB_SEARCH_RESULT_COUNT=3
      # - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      # - SEARXNG_QUERY_URL="http://searxng:8080/search?q=<query>"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.open-webui-rtr.entrypoints=https"
      - "traefik.http.routers.open-webui-rtr.rule=Host(`chat.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.open-webui-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.open-webui-rtr.service=open-webui-svc"
      - "traefik.http.services.open-webui-svc.loadbalancer.server.port=8080"

  open-webui-betus:
    container_name: open-webui-betus
    image: ghcr.io/open-webui/open-webui:latest # :ollama
    restart: $ML_RESTART_POLICY
    # depends_on:
    #   - searxng
    # <<: *gpu-deploy
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/open-webui-betus:/app/backend/data
      # - ollama:/root/.ollama
    environment:
      - WEBUI_AUTH=False
      - OPENAI_API_KEY=$OPENAI_API_KEY
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.open-webui-betus-rtr.entrypoints=https"
      - "traefik.http.routers.open-webui-betus-rtr.rule=Host(`betus.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.open-webui-betus-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.open-webui-betus-rtr.service=open-webui-betus-svc"
      - "traefik.http.services.open-webui-betus-svc.loadbalancer.server.port=8080"