version: "3.9"
name: others

networks:
  t2_proxy:
    external: true
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.22.0/24

# secrets:
#   firefly_app_key:
#     file: $DOCKERDIR/secrets/firefly_app_key

services:
  # wg-easy:
  #   image: weejewel/wg-easy
  #   container_name: wg-easy
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   volumes:
  #     - $DOCKERDIR/appdata/wg-easy:/etc/wireguard
  #   environment:
  #     - WG_HOST=$SERVER_IP
  #     # - PASSWORD=ilker
  #     # - WG_PORT=51820
  #     # - WG_DEFAULT_ADDRESS=10.8.0.x
  #     # - WG_DEFAULT_DNS=1.1.1.1
  #     # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
  #   ports:
  #     - "51820:51820/udp"
  #     # - "51821:51821/tcp"
  #   #    security_opt:
  #   # - no-new-privileges:true
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.ip_forward=1
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.wg-easy-rtr.entrypoints=https"
  #     - "traefik.http.routers.wg-easy-rtr.rule=Host(`wireguard.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.wg-easy-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.wg-easy-rtr.service=wg-easy-svc"
  #     - "traefik.http.services.wg-easy-svc.loadbalancer.server.port=51821"

  ######### RSS #########

  # freshrss:
  #   container_name: freshrss
  #   image: lscr.io/linuxserver/freshrss
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/freshrss:/config
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.freshrss-rtr.entrypoints=https"
  #     - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.freshrss-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
  #     - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

  miniflux-db:
    container_name: miniflux-db
    image: postgres:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - internal
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=miniflux
    volumes:
      - $DOCKERDIR/appdata/miniflux-db:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "miniflux"]
    #   interval: 10s
    #   start_period: 30s

    # Fever api endpoint: fever/?api
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:latest
    restart: $OTHERS_RESTART_POLICY
    depends_on:
      - miniflux-db
    networks:
      - t2_proxy
      - internal
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - $DOCKERDIR/appdata/miniflux:/config
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=miniflux
      - ADMIN_PASSWORD=miniflux
      - BASE_URL=https://miniflux.$DOMAINNAME
      # - "POCKET_CONSUMER_KEY=YOUR_POCKET_CONSUMER_KEY"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.miniflux-rtr.entrypoints=https"
      - "traefik.http.routers.miniflux-rtr.rule=Host(`miniflux.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.miniflux-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.miniflux-rtr.service=miniflux-svc"
      - "traefik.http.services.miniflux-svc.loadbalancer.server.port=8080"

  # https://github.com/AbdBarho/stable-diffusion-webui-docker
  stable-diffusion:
    container_name: stable-diffusion
    build: $STABLEDIFFUSIONDIR/services/AUTOMATIC1111
    image: sd-auto:49
    restart: $OTHERS_RESTART_POLICY
    stop_signal: SIGINT
    networks:
      - t2_proxy
    # ports:
    #   - "7860:7860"
    volumes:
      - $STABLEDIFFUSIONDIR/data:/data
      - $STABLEDIFFUSIONDIR/output:/output
      # - $STABLEDIFFUSIONDIR/services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
      # - $STABLEDIFFUSIONDIR/embeddings:/stable-diffusion-webui/embeddings
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sd-rtr.entrypoints=https"
      - "traefik.http.routers.sd-rtr.rule=Host(`sd.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.sd-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.sd-rtr.service=sd-svc"
      - "traefik.http.services.sd-svc.loadbalancer.server.port=7860"
  whisper-api:
    container_name: whisper-api
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    # ports:
    #   - "9000:9000"
    volumes:
      - $DOCKERDIR/appdata/whisper-api:/app
    environment:
      - ASR_MODEL=base 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              # device_ids: [ '0' ]
              # capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whisper-api-rtr.entrypoints=https"
      - "traefik.http.routers.whisper-api-rtr.rule=Host(`whisperapi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.whisper-api-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.whisper-api-rtr.service=whisper-api-svc"
      - "traefik.http.services.whisper-api-svc.loadbalancer.server.port=9000"

  darktable:
    container_name: darktable
    image: lscr.io/linuxserver/darktable:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $MEDIADIR/Photos:/photos
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - DOCKER_MODS=linuxserver/mods:universal-git
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.darktable-rtr.entrypoints=https"
      - "traefik.http.routers.darktable-rtr.rule=Host(`darktable.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.darktable-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.darktable-rtr.service=darktable-svc"
      - "traefik.http.services.darktable-svc.loadbalancer.server.port=3000"

  kasm:
    container_name: kasm
    image: lscr.io/linuxserver/kasm:latest
    restart: $OTHERS_RESTART_POLICY
    privileged: true
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/kasm/opt:/opt
    #   - /path/to/profiles:/profiles #optional
    #   - /dev/input:/dev/input #optional
    #   - /run/udev/data:/run/udev/data #optional
    ports:
      - 3030:3000
      # - 4443:4443
    # expose:
    #   - 4443
    environment:
      - KASM_PORT=4433
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kasm-rtr.entrypoints=https"
      - "traefik.http.routers.kasm-rtr.rule=Host(`kasm.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.kasm-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.kasm-rtr.service=kasm-svc"
      - "traefik.http.services.kasm-svc.loadbalancer.server.port=4443"
      # NOTE: https://docs.linuxserver.io/faq#strict-proxy
      - traefik.http.services.kasm-svc.loadbalancer.serverstransport=ignorecert@file
      - traefik.http.services.kasm-svc.loadbalancer.server.scheme=https

  ## TODO: Not Complete
  ## TODO: Is it possible only run kasmvnc as a server without kasmweb ui?
  ## echo -n "kasm_user:yourmostawesomepasswordhere" | base64
  ## a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ==
  # kasmvnc:
  #   container_name: kasmvnc
  #   image: kasmweb/desktop::latest
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   # volumes:
  #     # - $DOCKERDIR/appdata/kasmvnc:/TODO
  #   environment:
  #     - VNC_PW=yourmostawesomepasswordhere
  #     - TZ=$TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.kasmvnc-rtr.entrypoints=https"
  #     - "traefik.http.routers.kasmvnc-rtr.rule=Host(`kasmvnc.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.kasmvnc-rtr.middlewares=chain-no-auth@file"
  #     - "traefik.http.middlewares.kasmauth.headers.customrequestheaders.Authorization=Basic a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ=="
  #     ## HTTP Services
  #     - "traefik.http.routers.kasmvnc-rtr.service=kasmvnc-svc"
  #     - "traefik.http.services.kasmvnc-svc.loadbalancer.server.port=6901"
  #     # NOTE: https://docs.linuxserver.io/faq#strict-proxy
  #     # - traefik.http.services.kasmvnc-svc.loadbalancer.serverstransport=ignorecert@file
  #     # - traefik.http.services.kasmvnc-svc.loadbalancer.server.scheme=https

  #Expanse Tracker
  # firefly:
  #   container_name: firefly
  #   image: fireflyiii/core:latest
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/freshrss:/config
  #   environment:
  #     - TZ=$TZ
  #     - APP_KEY_FILE=/run/secrets/firefly_app_key
  #     - AUTHENTICATION_GUARD="web" # remote_user_guard
  #   #  - AUTHENTICATION_GUARD_HEADER=REMOTE_USER # HTTP_REMOTE_USER
  #     - DB_CONNECTION=sqlite # Options: pgsql, mysql
  #   secrets:
  #     - firefly_app_key
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.firefly-rtr.entrypoints=https"
  #     - "traefik.http.routers.firefly-rtr.rule=Host(`firefly.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.firefly-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.firefly-rtr.service=firefly-svc"
  #     - "traefik.http.services.firefly-svc.loadbalancer.server.port=8080"
