version: "3.9"
name: others

networks:
  t2_proxy:
    external: true
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.22.0/24

# secrets:
#   firefly_app_key:
#     file: $DOCKERDIR/secrets/firefly_app_key

services:
  # wg-easy:
  #   image: weejewel/wg-easy
  #   container_name: wg-easy
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   volumes:
  #     - $DOCKERDIR/appdata/wg-easy:/etc/wireguard
  #   environment:
  #     - WG_HOST=$SERVER_IP
  #     # - PASSWORD=ilker
  #     # - WG_PORT=51820
  #     # - WG_DEFAULT_ADDRESS=10.8.0.x
  #     # - WG_DEFAULT_DNS=1.1.1.1
  #     # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
  #   ports:
  #     - "51820:51820/udp"
  #     # - "51821:51821/tcp"
  #   #    security_opt:
  #   # - no-new-privileges:true
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.ip_forward=1
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers Auth
  #     - "traefik.http.routers.wg-easy-rtr.entrypoints=https"
  #     - "traefik.http.routers.wg-easy-rtr.rule=Host(`wireguard.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.wg-easy-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.wg-easy-rtr.service=wg-easy-svc"
  #     - "traefik.http.services.wg-easy-svc.loadbalancer.server.port=51821"

  ######### RSS #########

  # freshrss:
  #   container_name: freshrss
  #   image: lscr.io/linuxserver/freshrss
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/freshrss:/config
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.freshrss-rtr.entrypoints=https"
  #     - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.freshrss-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
  #     - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

  miniflux-db:
    container_name: miniflux-db
    image: postgres:latest
    restart: $OTHERS_RESTART_POLICY
    networks:
      - internal
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=miniflux
    volumes:
      - $DOCKERDIR/appdata/miniflux-db:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "miniflux"]
    #   interval: 10s
    #   start_period: 30s

    # Fever api endpoint: fever/?api
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:latest
    restart: $OTHERS_RESTART_POLICY
    depends_on:
      - miniflux-db
    networks:
      - t2_proxy
      - internal
    security_opt:
      - no-new-privileges:true
    # volumes:
    #   - $DOCKERDIR/appdata/miniflux:/config
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=miniflux
      - ADMIN_PASSWORD=miniflux
      - BASE_URL=https://miniflux.$DOMAINNAME
      # - "POCKET_CONSUMER_KEY=YOUR_POCKET_CONSUMER_KEY"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.miniflux-rtr.entrypoints=https"
      - "traefik.http.routers.miniflux-rtr.rule=Host(`miniflux.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.miniflux-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.miniflux-rtr.service=miniflux-svc"
      - "traefik.http.services.miniflux-svc.loadbalancer.server.port=8080"

  stable-diffusion:
    container_name: stable-diffusion
    build: $GITHUBREPOSDIR/stable-diffusion-webui-docker/services/AUTOMATIC1111
    image: stablediff-auto:71
    restart: $OTHERS_RESTART_POLICY
    stop_signal: SIGINT
    tty: true
    networks:
      - t2_proxy
    volumes:
      - $GITHUBREPOSDIR/stable-diffusion-webui-docker/data:/data
      - $GITHUBREPOSDIR/stable-diffusion-webui-docker/output:/output
      # - $GITHUBREPOSDIR/stable-diffusion-webui-docker/services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json
    environment:
      # - ATTN_PRECISION=fp16
      - CLI_ARGS=--allow-code --enable-insecure-extension-access --medvram-sdxl # --api --xformers --no-half-vae
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              # capabilities: [ gpu ]
              capabilities: [compute, utility]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.stablediffusion-rtr.entrypoints=https"
      - "traefik.http.routers.stablediffusion-rtr.rule=Host(`stablediffusion.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.stablediffusion-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.stablediffusion-rtr.service=stablediffusion-svc"
      - "traefik.http.services.stablediffusion-svc.loadbalancer.server.port=7860"

  sd-next:
    container_name: sd-next
    image: holaflenain/stable-diffusion:latest
    restart: $OTHERS_RESTART_POLICY
    # runtime: nvidia # NOTE: Not working
    networks:
      - t2_proxy
    ports:
      - "9999:9000/tcp"
    volumes:
      - $DOCKERDIR/appdata/sd-next:/config:rw
      - $MLMODELSDIR:/config/models/stable-diffusion:ro
    environment:
      - WEBUI_VERSION=04
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      # - CLEAN_ENV=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [compute, utility]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sdnext-rtr.entrypoints=https"
      - "traefik.http.routers.sdnext-rtr.rule=Host(`sdnext.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.sdnext-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.sdnext-rtr.service=sdnext-svc"
      - "traefik.http.services.sdnext-svc.loadbalancer.server.port=9000"

  # NOTE: Not completed yet !!!
  # https://github.com/Atinoda/text-generation-webui-docker
  text-generation:
    container_name: text-generation
    image: atinoda/text-generation-webui:default
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    volumes:
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/characters:/app/characters
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/loras:/app/loras
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/models:/app/models
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/presets:/app/presets
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/prompts:/app/prompts
      - $GITHUBREPOSDIR/text-generation-webui-docker/config/training:/app/training
#      - $GITHUBREPOSDIR/text-generation-webui-docker/config/extensions:/app/extensions  # Persist all extensions
#      - $GITHUBREPOSDIR/text-generation-webui-docker/config/extensions/silero_tts:/app/extensions/silero_tts  # Persist a single extension
    environment:
      - EXTRA_LAUNCH_ARGS="--listen --verbose --model MODEL_NAME" # Custom launch args (e.g., --model MODEL_NAME)
#      - BUILD_EXTENSIONS_LIVE="silero_tts whisper_stt" # Install named extensions during every container launch. THIS WILL SIGNIFICANLTLY SLOW LAUNCH TIME.
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.textgen-rtr.entrypoints=https"
      - "traefik.http.routers.textgen-rtr.rule=Host(`textgen.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.textgen-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.textgen-rtr.service=textgen-svc"
      - "traefik.http.services.textgen-svc.loadbalancer.server.port=7860"

  llama-cpp:
    container_name: llama-cpp
    # image: ghcr.io/ggerganov/llama.cpp:full-cuda # light - full - light-cuda - full-cuda
    image: llama.cpp:lite-cuda12
    build:
      dockerfile: $DOCKERDIR/stacks/others/llmacpp_lite_cuda12.Dockerfile
      context: $GITHUBREPOSDIR/llama.cpp
      args:
        - CUDA_VERSION=12.3.1
        - CUDA_DOCKER_ARCH=all
    # command: ["--run", "-m", "/models/tinyllma-1.1b-chat-v1.0.Q8_0.gguf", "-p", "Building a website can be done in 10 simple steps:", "-n", "512", "--n-gpu-layers", "50"]
    command: ["--server", "-m", "/models/tinyllma-1.1b-chat-v1.0.Q8_0.gguf", "--port", "8080", "--host", "0.0.0.0", "-c", "2048", "--n-gpu-layers", "50"]
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    # ports:
    #   - "8081:8080"
    volumes:
     - "$MLMODELSDIR/LLM:/models:ro"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.llama-cpp-rtr.entrypoints=https"
      - "traefik.http.routers.llama-cpp-rtr.rule=Host(`llmapi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.llama-cpp-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.llama-cpp-rtr.service=llama-cpp-svc"
      - "traefik.http.services.llama-cpp-svc.loadbalancer.server.port=8080"
  
  whisper-api:
    container_name: whisper-api
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: $OTHERS_RESTART_POLICY
    networks:
      - t2_proxy
    # ports:
    #   - "9000:9000"
    volumes:
      - $DOCKERDIR/appdata/whisper-api:/app
    environment:
      - ASR_MODEL=base 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              # device_ids: [ '0' ]
              # capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whisper-api-rtr.entrypoints=https"
      - "traefik.http.routers.whisper-api-rtr.rule=Host(`whisperapi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.whisper-api-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.whisper-api-rtr.service=whisper-api-svc"
      - "traefik.http.services.whisper-api-svc.loadbalancer.server.port=9000"

  #Expanse Tracker
  # firefly:
  #   container_name: firefly
  #   image: fireflyiii/core:latest
  #   restart: $OTHERS_RESTART_POLICY
  #   networks:
  #     - t2_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/appdata/freshrss:/config
  #   environment:
  #     - TZ=$TZ
  #     - APP_KEY_FILE=/run/secrets/firefly_app_key
  #     - AUTHENTICATION_GUARD="web" # remote_user_guard
  #   #  - AUTHENTICATION_GUARD_HEADER=REMOTE_USER # HTTP_REMOTE_USER
  #     - DB_CONNECTION=sqlite # Options: pgsql, mysql
  #   secrets:
  #     - firefly_app_key
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.firefly-rtr.entrypoints=https"
  #     - "traefik.http.routers.firefly-rtr.rule=Host(`firefly.$DOMAINNAME`)"
  #     ## Middlewares
  #     - "traefik.http.routers.firefly-rtr.middlewares=chain-authelia@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.firefly-rtr.service=firefly-svc"
  #     - "traefik.http.services.firefly-svc.loadbalancer.server.port=8080"
