http:
  routers:
    sealskin-rtr:
      rule: "Host(`sealskin.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: sealskin-svc
    obsidian-rtr:
      rule: "Host(`obsidian.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: obsidian-svc

    bambustudio-rtr:
      rule: "Host(`bambustudio.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: bambustudio-svc

  services:
    sealskin-svc:
      loadBalancer:
        servers:
          - url: http://192.168.2.19:3001
    obsidian-svc:
      loadBalancer:
        servers:
          - url: http://192.168.2.19:3002
    bambustudio-svc:
      loadBalancer:
        servers:
          - url: http://192.168.2.19:3003