http:
  routers:
    t3code-rtr:
      rule: "Host(`t3code.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: t3code-svc

    marimo-local-rtr:
      rule: "Host(`marimo-local.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: marimo-local-svc

    homeserver-api-rtr:
      rule: "Host(`api-backend.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: homeserver-api-svc

    homeserver-api-ui-rtr:
      rule: "Host(`api.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: homeserver-api-ui-svc

    lgos-chainlit-rtr:
      rule: "Host(`lgos-chainlit.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: lgos-chainlit-svc

    lgos-bifrost-rtr:
      rule: "Host(`lgos-bifrost.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: lgos-bifrost-svc

    lgos-openwebui-rtr:
      rule: "Host(`lgos-openwebui.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: lgos-openwebui-svc

  services:
    t3code-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:3773"

    marimo-local-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:2718"

    homeserver-api-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:8000"

    homeserver-api-ui-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:5002"

    lgos-chainlit-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:3002"

    lgos-bifrost-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:3000"

    lgos-openwebui-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:3003"
