http:
  routers:
    t3code-rtr:
      rule: "Host(`t3code.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: t3code-svc

    homeserver-api-rtr:
      rule: "Host(`api-backend.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: homeserver-api-svc

    homeserver-api-ui-rtr:
      rule: "Host(`api.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: homeserver-api-ui-svc

  services:
    t3code-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:3773"

    homeserver-api-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:8000"

    homeserver-api-ui-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:5002"
