http:
  serversTransports:
    # NOTE: Proxmox redirect requests to https which causes redirect loop with traefik. This fixes it.
    proxmox-transport:
      serverName: ""
      insecureSkipVerify: true

  routers:
    openwrt-rtr:
      rule: "Host(`openwrt.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: openwrt-svc

    gpu-rtr:
      rule: "Host(`gpu.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: gpu-svc

    nas-rtr:
      rule: "Host(`nas.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: nas-svc

    adguardhome-rtr:
      rule: "Host(`adguardhome.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: adguardhome-svc

    home-assistant-rtr:
      rule: "Host(`smarthome.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: home-assistant-svc

    gotify-rtr:
      rule: "Host(`gotify.{{env "BASE_DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: gotify-svc

    cam0-rtr:
      rule: "Host(`cam0.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam0-svc

    cam1-rtr:
      rule: "Host(`cam1.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam1-svc

    cam2-rtr:
      rule: "Host(`cam2.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam2-svc

    cam3-rtr:
      rule: "Host(`cam3.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam3-svc

    cam4-rtr:
      rule: "Host(`cam4.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam4-svc

  services:
    openwrt-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.1"

    gpu-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.4:8006"
        serversTransport: proxmox-transport

    nas-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.7:8006"
        serversTransport: proxmox-transport

    adguardhome-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.12:81"

    home-assistant-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.12:8123"

    gotify-svc:
      loadBalancer:
        servers:
          - url: "http://100.64.0.4:1005"


    cam0-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.120"

    cam1-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.121"

    cam2-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.122"

    cam3-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.123"

    cam4-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.124"