http:
  routers:
    webfinger-rtr:
      rule: "Host(`{{env "DOMAINNAME"}}`) && PathPrefix(`/.well-known/webfinger`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
        - middlewares-rate-limit-webfinger
        - middlewares-webfinger
      service: webfinger-svc

    pocket-id-rtr:
      rule: "Host(`pocketid.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-pocket-id
      service: pocket-id-svc

    immich-public-proxy-rtr:
      rule: "Host(`share.{{env "DOMAINNAME"}}`) && PathPrefix(`/share`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: immich-public-proxy-svc

    public-catchall-rtr:
      rule: "PathPrefix(`/`)"
      priority: 1
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: noop@internal

  # middlewares:

  services:
    webfinger-svc:
      loadBalancer:
        servers:
          - url: "http://DUMMY"

    pocket-id-svc:
      loadBalancer:
        servers:
          - url: "http://100.64.0.12:1000"
        # healthCheck:
        #   path: "/healthz"
        #   interval: "30s"
        #   timeout: "5s"

    immich-public-proxy-svc:
      loadBalancer:
        servers:
          - url: "http://100.64.0.9:1003"
