http:
  serversTransports:
    # NOTE: Proxmox redirect requests to https which causes redirect loop with traefik. This fixes it.
    proxmox-transport:
      serverName: ""
      insecureSkipVerify: true

  routers:
    openwrt-rtr:
      rule: "Host(`openwrt.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: openwrt-svc

    gpu-rtr:
      rule: "Host(`gpu.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: gpu-svc

    nas-rtr:
      rule: "Host(`nas.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: nas-svc

    pbs-rtr:
      rule: "Host(`pbs.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: pbs-svc

    aile-rtr:
      rule: "Host(`aile.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: aile-svc

    adguardhome-rtr:
      rule: "Host(`adguardhome.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: adguardhome-svc

    home-assistant-rtr:
      rule: "Host(`smarthome.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-home-assistant
      service: home-assistant-svc

    cam0-rtr:
      rule: "Host(`cam0.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam0-svc

    cam0-ws-rtr:
      rule: "Host(`cam0.{{env "DOMAINNAME"}}`) && Header(`Upgrade`, `websocket`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: cam0-ws-svc

    frigate-rtr:
      rule: "Host(`frigate.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: frigate-svc

    watchyourlan-rtr:
      rule: "Host(`lan.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: watchyourlan-svc

    watchyourlan-assets-rtr:
      rule: "Host(`lan.{{env "DOMAINNAME"}}`) && PathPrefix(`/node_modules`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: watchyourlan-assets-svc

  services:
    openwrt-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.1"

    gpu-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.4:8006"
        serversTransport: proxmox-transport

    nas-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.7:8006"
        serversTransport: proxmox-transport

    pbs-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.22:8007"
        serversTransport: proxmox-transport

    aile-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.119:8006"
        serversTransport: proxmox-transport

    adguardhome-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.12:81"

    home-assistant-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.12:8123"

    cam0-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.120"

    cam0-ws-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.120"

    frigate-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.118:8971"

    watchyourlan-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:8840"

    watchyourlan-assets-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LOCAL_STATIC_IP"}}:8850"
