http:
  routers:
    adguardhome-rtr:
      rule: "Host(`adguardhome.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: adguardhome-svc
    pocket-id-rtr:
      rule: "Host(`pocketid.{{env "BASE_DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-pocket-id
      service: pocket-id-svc
    gotify-rtr:
      rule: "Host(`gotify.{{env "BASE_DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: gotify-svc
    aiostreams-rtr:
      rule: "Host(`aiostreams.{{env "BASE_DOMAINNAME"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth-relaxed
      service: aiostreams-svc

  services:
    adguardhome-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.13:81"
    pocket-id-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.2.12:1000"
        # healthCheck:
        #   path: "/healthz"
        #   interval: "30s"
        #   timeout: "5s"
    gotify-svc:
      loadBalancer:
        servers:
          - url: "http://100.64.0.1:1005"
    aiostreams-svc:
      loadBalancer:
        servers:
          - url: "http://100.64.0.1:1006"
