---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Proxmox Backup Client Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfiles/ProxmoxBackupClient/**
  pull_request:
    paths:
      - Dockerfiles/ProxmoxBackupClient/**
      - .github/workflows/custom-images-build.yml
      - .github/workflows/custom-images-proxmox-backup-client.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    uses: ./.github/workflows/custom-images-build.yml
    with:
      name: Proxmox Backup Client
      context: Dockerfiles/ProxmoxBackupClient
      repository: homeserver-proxmox-backup-client
      publish: false

  publish:
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/custom-images-build.yml
    with:
      name: Proxmox Backup Client
      context: Dockerfiles/ProxmoxBackupClient
      repository: homeserver-proxmox-backup-client
      publish: true
