- name: Cinema
  columns:
    - size: full
      widgets:
        # - type: search
        #   search-engine: google
        #   new-tab: true
        #   # FIXME: Not working because of the API key
        #   bangs:
        #     - title: TMDB Movie
        #       shortcut: "!movie"
        #       url: https://api.themoviedb.org/3/search/movie?query={QUERY}
        #       headers:
        #         Authorization: Bearer ${TMDB_API_READ_ACCESS_TOKEN}

        # NOTE: https://docs.rsshub.app/routes/multimedia#the-movie-database
        - type: group
          title: MOVIES
          widgets:
            - type: rss
              title: TRENDING
              style: horizontal-cards-2
              limit: 20
              cache: 2h
              feeds:
                - url: https://rsshub.gpu.${BASE_DOMAINNAME}/themoviedb/trending/movie/day/en-US
                  title: " "

            - type: rss
              title: UPCOMING
              style: horizontal-cards-2
              limit: 20
              cache: 2h
              feeds:
                - url: https://rsshub.gpu.${BASE_DOMAINNAME}/themoviedb/movie/upcoming/en-US
                  title: " "

            - type: rss
              title: TOP.RATED
              style: horizontal-cards-2
              limit: 20
              cache: 2h
              feeds:
                - url: https://rsshub.gpu.${BASE_DOMAINNAME}/themoviedb/movie/top-rated/en-US
                  title: " "

        - type: group
          title: TVSHOWS
          widgets:
            - type: rss
              title: TRENDING
              style: horizontal-cards-2
              limit: 20
              cache: 2h
              feeds:
                - url: https://rsshub.gpu.${BASE_DOMAINNAME}/themoviedb/trending/tv/day/en-US
                  title: " "

            - type: rss
              title: TOP.RATED
              style: horizontal-cards-2
              limit: 20
              cache: 2h
              feeds:
                - url: https://rsshub.gpu.${BASE_DOMAINNAME}/themoviedb/tv/top-rated/en-US
                  title: " "

        # - type: split-column
        #   widgets:
        #     - $include: custom-widgets/tmdb-popular-movies.yml
        #     - $include: custom-widgets/tmdb-popular-tvshows.yml

    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - $include: custom-widgets/trakt-history.yml
        # - $include: custom-widgets/jellyfin-history.yml
