- name: Services
  columns:
    # - size: small
    #   widgets:
    #     - $include: custom-widgets/beszel.yml

    - size: full
      widgets:
        # - type: server-stats
        #   servers:
        #     - type: local
        #       name: Homeserver
        #       # optionally override the sensor used to determine CPU temperature
        #       cpu-temp-sensor: k10temp_tctl
        #       hide-swap: true
        #       # optionally hide or rename mountpoints
        #       # mountpoints:
        #       #   "/boot/efi":
        #       #     hide: true
        #       #     name: EFI

        # - type: docker-containers
        #   hide-by-default: false
        #   # providers:
        #   #   - type: proxy
        #   #     host: tcp://docker-socket-proxy:2375

        - type: group
          widgets:
          - type: iframe
            title: HOMESERVER
            source: https://homepage.gpu.${BASE_DOMAINNAME}
            # source: http://homepage:3000
            height: 1000

          - type: iframe
            title: REMOTESERVER
            source: https://homepage.${BASE_DOMAINNAME}
            height: 1000

          - type: iframe
            title: NAS
            source: https://homepage.nas.${BASE_DOMAINNAME}
            height: 1000

          - type: iframe
            title: DOZZLE
            source: https://dozzle.gpu.${BASE_DOMAINNAME}
            # source: http://dozzle:8080
            height: 1000

          - type: iframe
            title: UPTIME
            source: https://gatus.${BASE_DOMAINNAME}
            height: 1000

    - size: small
      widgets:
        - type: group
          widgets:
          - $include: custom-widgets/headscale.yml