- name: Social
  columns:
    # - size: small
    #   widgets:

    - size: full
      widgets:
        - type: videos
          style: horizontal-cards # horizontal-cards, grid-cards
          title: YouTube
          channels:
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
            - UCbfYPyITQ-7l4upoX8nvctg # Two Minute Papers
            - UCsXVk37bltHxD1rDPwtNM8Q # Kurzgesagt
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            # - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            # - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
        
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: Piracy
              show-thumbnails: true
            - type: reddit
              subreddit: interestingasfuck
              show-thumbnails: true
            - type: reddit
              subreddit: Turkey
              show-thumbnails: true
            - type: reddit
              subreddit: TurkeyJerky
              show-thumbnails: true
            - type: reddit
              subreddit: svihs
              show-thumbnails: true
            - type: reddit
              subreddit: europe
              show-thumbnails: true
            - type: reddit
              subreddit: BambuLab
              show-thumbnails: true

        - type: rss
          limit: 20
          title: Twitter
          collapse-after: 4
          cache: 6h
          feeds:
            - url: http://rsshub:1200/twitter/user/karpathy/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150  
              title: karpathy
            - url: http://rsshub:1200/twitter/user/AndrewYNg/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150  
              title: AndrewYNg
            - url: http://rsshub:1200/twitter/user/charliermarsh/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150  
              title: charliermarsh